/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.1
Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


// OpenChannelMessagePriorityAPIService OpenChannelMessagePriorityAPI service
type OpenChannelMessagePriorityAPIService service

type ApiAddOpenChannelLowPriorityMessageTypeListRequest struct {
	ctx context.Context
	ApiService *OpenChannelMessagePriorityAPIService
	openChannelLowPriorityMessageTypeListRequest *OpenChannelLowPriorityMessageTypeListRequest
}

func (r ApiAddOpenChannelLowPriorityMessageTypeListRequest) OpenChannelLowPriorityMessageTypeListRequest(openChannelLowPriorityMessageTypeListRequest OpenChannelLowPriorityMessageTypeListRequest) ApiAddOpenChannelLowPriorityMessageTypeListRequest {
	r.openChannelLowPriorityMessageTypeListRequest = &openChannelLowPriorityMessageTypeListRequest
	return r
}

func (r ApiAddOpenChannelLowPriorityMessageTypeListRequest) Execute() (*CodeOnlyResponse, *http.Response, error) {
	return r.ApiService.AddOpenChannelLowPriorityMessageTypeListExecute(r)
}

/*
AddOpenChannelLowPriorityMessageTypeList Add low-priority message types

Rate limit: 100/sec.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiAddOpenChannelLowPriorityMessageTypeListRequest
*/
func (a *OpenChannelMessagePriorityAPIService) AddOpenChannelLowPriorityMessageTypeList(ctx context.Context) ApiAddOpenChannelLowPriorityMessageTypeListRequest {
	return ApiAddOpenChannelLowPriorityMessageTypeListRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return CodeOnlyResponse
func (a *OpenChannelMessagePriorityAPIService) AddOpenChannelLowPriorityMessageTypeListExecute(r ApiAddOpenChannelLowPriorityMessageTypeListRequest) (*CodeOnlyResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CodeOnlyResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OpenChannelMessagePriorityAPIService.AddOpenChannelLowPriorityMessageTypeList")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v4/open-channel/low-priority-message-type-list/add"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.openChannelLowPriorityMessageTypeListRequest == nil {
		return localVarReturnValue, nil, reportError("openChannelLowPriorityMessageTypeListRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.openChannelLowPriorityMessageTypeListRequest
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["NexconnSignature"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["App-Key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetOpenChannelLowPriorityMessageTypeListRequest struct {
	ctx context.Context
	ApiService *OpenChannelMessagePriorityAPIService
	body *map[string]interface{}
}

func (r ApiGetOpenChannelLowPriorityMessageTypeListRequest) Body(body map[string]interface{}) ApiGetOpenChannelLowPriorityMessageTypeListRequest {
	r.body = &body
	return r
}

func (r ApiGetOpenChannelLowPriorityMessageTypeListRequest) Execute() (*OpenChannelMessageTypeListResponse, *http.Response, error) {
	return r.ApiService.GetOpenChannelLowPriorityMessageTypeListExecute(r)
}

/*
GetOpenChannelLowPriorityMessageTypeList Query low-priority message types

Rate limit: 100/sec.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetOpenChannelLowPriorityMessageTypeListRequest
*/
func (a *OpenChannelMessagePriorityAPIService) GetOpenChannelLowPriorityMessageTypeList(ctx context.Context) ApiGetOpenChannelLowPriorityMessageTypeListRequest {
	return ApiGetOpenChannelLowPriorityMessageTypeListRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return OpenChannelMessageTypeListResponse
func (a *OpenChannelMessagePriorityAPIService) GetOpenChannelLowPriorityMessageTypeListExecute(r ApiGetOpenChannelLowPriorityMessageTypeListRequest) (*OpenChannelMessageTypeListResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *OpenChannelMessageTypeListResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OpenChannelMessagePriorityAPIService.GetOpenChannelLowPriorityMessageTypeList")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v4/open-channel/low-priority-message-type-list/get"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarBodyValue := map[string]interface{}{}
	if r.body != nil {
		localVarBodyValue = *r.body
		if localVarBodyValue == nil {
			localVarBodyValue = map[string]interface{}{}
		}
	}
	// body params
	localVarPostBody = localVarBodyValue
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["NexconnSignature"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["App-Key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiRemoveOpenChannelLowPriorityMessageTypeListRequest struct {
	ctx context.Context
	ApiService *OpenChannelMessagePriorityAPIService
	openChannelLowPriorityMessageTypeListRequest *OpenChannelLowPriorityMessageTypeListRequest
}

func (r ApiRemoveOpenChannelLowPriorityMessageTypeListRequest) OpenChannelLowPriorityMessageTypeListRequest(openChannelLowPriorityMessageTypeListRequest OpenChannelLowPriorityMessageTypeListRequest) ApiRemoveOpenChannelLowPriorityMessageTypeListRequest {
	r.openChannelLowPriorityMessageTypeListRequest = &openChannelLowPriorityMessageTypeListRequest
	return r
}

func (r ApiRemoveOpenChannelLowPriorityMessageTypeListRequest) Execute() (*CodeOnlyResponse, *http.Response, error) {
	return r.ApiService.RemoveOpenChannelLowPriorityMessageTypeListExecute(r)
}

/*
RemoveOpenChannelLowPriorityMessageTypeList Remove low-priority message types

Rate limit: 100/sec.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiRemoveOpenChannelLowPriorityMessageTypeListRequest
*/
func (a *OpenChannelMessagePriorityAPIService) RemoveOpenChannelLowPriorityMessageTypeList(ctx context.Context) ApiRemoveOpenChannelLowPriorityMessageTypeListRequest {
	return ApiRemoveOpenChannelLowPriorityMessageTypeListRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return CodeOnlyResponse
func (a *OpenChannelMessagePriorityAPIService) RemoveOpenChannelLowPriorityMessageTypeListExecute(r ApiRemoveOpenChannelLowPriorityMessageTypeListRequest) (*CodeOnlyResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CodeOnlyResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "OpenChannelMessagePriorityAPIService.RemoveOpenChannelLowPriorityMessageTypeList")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v4/open-channel/low-priority-message-type-list/remove"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.openChannelLowPriorityMessageTypeListRequest == nil {
		return localVarReturnValue, nil, reportError("openChannelLowPriorityMessageTypeListRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.openChannelLowPriorityMessageTypeListRequest
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["NexconnSignature"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["App-Key"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
