/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the CommunityChannelMessageMetadataListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommunityChannelMessageMetadataListResponse{}

// CommunityChannelMessageMetadataListResponse struct for CommunityChannelMessageMetadataListResponse
type CommunityChannelMessageMetadataListResponse struct {
	Code int32 `json:"code"`
	Result *CommunityChannelMessageMetadataListResponseResult `json:"result,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CommunityChannelMessageMetadataListResponse CommunityChannelMessageMetadataListResponse

// NewCommunityChannelMessageMetadataListResponse instantiates a new CommunityChannelMessageMetadataListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommunityChannelMessageMetadataListResponse(code int32) *CommunityChannelMessageMetadataListResponse {
	this := CommunityChannelMessageMetadataListResponse{}
	this.Code = code
	return &this
}

// NewCommunityChannelMessageMetadataListResponseWithDefaults instantiates a new CommunityChannelMessageMetadataListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommunityChannelMessageMetadataListResponseWithDefaults() *CommunityChannelMessageMetadataListResponse {
	this := CommunityChannelMessageMetadataListResponse{}
	return &this
}

// GetCode returns the Code field value
func (o *CommunityChannelMessageMetadataListResponse) GetCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *CommunityChannelMessageMetadataListResponse) GetCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *CommunityChannelMessageMetadataListResponse) SetCode(v int32) {
	o.Code = v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *CommunityChannelMessageMetadataListResponse) GetResult() CommunityChannelMessageMetadataListResponseResult {
	if o == nil || IsNil(o.Result) {
		var ret CommunityChannelMessageMetadataListResponseResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityChannelMessageMetadataListResponse) GetResultOk() (*CommunityChannelMessageMetadataListResponseResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *CommunityChannelMessageMetadataListResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given CommunityChannelMessageMetadataListResponseResult and assigns it to the Result field.
func (o *CommunityChannelMessageMetadataListResponse) SetResult(v CommunityChannelMessageMetadataListResponseResult) {
	o.Result = &v
}

func (o CommunityChannelMessageMetadataListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommunityChannelMessageMetadataListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommunityChannelMessageMetadataListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommunityChannelMessageMetadataListResponse := _CommunityChannelMessageMetadataListResponse{}

	err = json.Unmarshal(data, &varCommunityChannelMessageMetadataListResponse)

	if err != nil {
		return err
	}

	*o = CommunityChannelMessageMetadataListResponse(varCommunityChannelMessageMetadataListResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "result")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommunityChannelMessageMetadataListResponse struct {
	value *CommunityChannelMessageMetadataListResponse
	isSet bool
}

func (v NullableCommunityChannelMessageMetadataListResponse) Get() *CommunityChannelMessageMetadataListResponse {
	return v.value
}

func (v *NullableCommunityChannelMessageMetadataListResponse) Set(val *CommunityChannelMessageMetadataListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCommunityChannelMessageMetadataListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCommunityChannelMessageMetadataListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommunityChannelMessageMetadataListResponse(val *CommunityChannelMessageMetadataListResponse) *NullableCommunityChannelMessageMetadataListResponse {
	return &NullableCommunityChannelMessageMetadataListResponse{value: val, isSet: true}
}

func (v NullableCommunityChannelMessageMetadataListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommunityChannelMessageMetadataListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


