/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OpenChannelParticipantMuteListAddRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenChannelParticipantMuteListAddRequest{}

// OpenChannelParticipantMuteListAddRequest struct for OpenChannelParticipantMuteListAddRequest
type OpenChannelParticipantMuteListAddRequest struct {
	ChannelId string `json:"channelId"`
	ParticipantIds []string `json:"participantIds"`
	DurationMinutes int32 `json:"durationMinutes"`
	// Notification extra payload in JSON string format.
	Extra *string `json:"extra,omitempty"`
	NeedNotify *bool `json:"needNotify,omitempty"`
}

type _OpenChannelParticipantMuteListAddRequest OpenChannelParticipantMuteListAddRequest

// NewOpenChannelParticipantMuteListAddRequest instantiates a new OpenChannelParticipantMuteListAddRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenChannelParticipantMuteListAddRequest(channelId string, participantIds []string, durationMinutes int32) *OpenChannelParticipantMuteListAddRequest {
	this := OpenChannelParticipantMuteListAddRequest{}
	this.ChannelId = channelId
	this.ParticipantIds = participantIds
	this.DurationMinutes = durationMinutes
	return &this
}

// NewOpenChannelParticipantMuteListAddRequestWithDefaults instantiates a new OpenChannelParticipantMuteListAddRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenChannelParticipantMuteListAddRequestWithDefaults() *OpenChannelParticipantMuteListAddRequest {
	this := OpenChannelParticipantMuteListAddRequest{}
	return &this
}

// GetChannelId returns the ChannelId field value
func (o *OpenChannelParticipantMuteListAddRequest) GetChannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value
// and a boolean to check if the value has been set.
func (o *OpenChannelParticipantMuteListAddRequest) GetChannelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelId, true
}

// SetChannelId sets field value
func (o *OpenChannelParticipantMuteListAddRequest) SetChannelId(v string) {
	o.ChannelId = v
}

// GetParticipantIds returns the ParticipantIds field value
func (o *OpenChannelParticipantMuteListAddRequest) GetParticipantIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ParticipantIds
}

// GetParticipantIdsOk returns a tuple with the ParticipantIds field value
// and a boolean to check if the value has been set.
func (o *OpenChannelParticipantMuteListAddRequest) GetParticipantIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParticipantIds, true
}

// SetParticipantIds sets field value
func (o *OpenChannelParticipantMuteListAddRequest) SetParticipantIds(v []string) {
	o.ParticipantIds = v
}

// GetDurationMinutes returns the DurationMinutes field value
func (o *OpenChannelParticipantMuteListAddRequest) GetDurationMinutes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DurationMinutes
}

// GetDurationMinutesOk returns a tuple with the DurationMinutes field value
// and a boolean to check if the value has been set.
func (o *OpenChannelParticipantMuteListAddRequest) GetDurationMinutesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DurationMinutes, true
}

// SetDurationMinutes sets field value
func (o *OpenChannelParticipantMuteListAddRequest) SetDurationMinutes(v int32) {
	o.DurationMinutes = v
}

// GetExtra returns the Extra field value if set, zero value otherwise.
func (o *OpenChannelParticipantMuteListAddRequest) GetExtra() string {
	if o == nil || IsNil(o.Extra) {
		var ret string
		return ret
	}
	return *o.Extra
}

// GetExtraOk returns a tuple with the Extra field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelParticipantMuteListAddRequest) GetExtraOk() (*string, bool) {
	if o == nil || IsNil(o.Extra) {
		return nil, false
	}
	return o.Extra, true
}

// HasExtra returns a boolean if a field has been set.
func (o *OpenChannelParticipantMuteListAddRequest) HasExtra() bool {
	if o != nil && !IsNil(o.Extra) {
		return true
	}

	return false
}

// SetExtra gets a reference to the given string and assigns it to the Extra field.
func (o *OpenChannelParticipantMuteListAddRequest) SetExtra(v string) {
	o.Extra = &v
}

// GetNeedNotify returns the NeedNotify field value if set, zero value otherwise.
func (o *OpenChannelParticipantMuteListAddRequest) GetNeedNotify() bool {
	if o == nil || IsNil(o.NeedNotify) {
		var ret bool
		return ret
	}
	return *o.NeedNotify
}

// GetNeedNotifyOk returns a tuple with the NeedNotify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelParticipantMuteListAddRequest) GetNeedNotifyOk() (*bool, bool) {
	if o == nil || IsNil(o.NeedNotify) {
		return nil, false
	}
	return o.NeedNotify, true
}

// HasNeedNotify returns a boolean if a field has been set.
func (o *OpenChannelParticipantMuteListAddRequest) HasNeedNotify() bool {
	if o != nil && !IsNil(o.NeedNotify) {
		return true
	}

	return false
}

// SetNeedNotify gets a reference to the given bool and assigns it to the NeedNotify field.
func (o *OpenChannelParticipantMuteListAddRequest) SetNeedNotify(v bool) {
	o.NeedNotify = &v
}

func (o OpenChannelParticipantMuteListAddRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenChannelParticipantMuteListAddRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channelId"] = o.ChannelId
	toSerialize["participantIds"] = o.ParticipantIds
	toSerialize["durationMinutes"] = o.DurationMinutes
	if !IsNil(o.Extra) {
		toSerialize["extra"] = o.Extra
	}
	if !IsNil(o.NeedNotify) {
		toSerialize["needNotify"] = o.NeedNotify
	}
	return toSerialize, nil
}

func (o *OpenChannelParticipantMuteListAddRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channelId",
		"participantIds",
		"durationMinutes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenChannelParticipantMuteListAddRequest := _OpenChannelParticipantMuteListAddRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenChannelParticipantMuteListAddRequest)

	if err != nil {
		return err
	}

	*o = OpenChannelParticipantMuteListAddRequest(varOpenChannelParticipantMuteListAddRequest)

	return err
}

type NullableOpenChannelParticipantMuteListAddRequest struct {
	value *OpenChannelParticipantMuteListAddRequest
	isSet bool
}

func (v NullableOpenChannelParticipantMuteListAddRequest) Get() *OpenChannelParticipantMuteListAddRequest {
	return v.value
}

func (v *NullableOpenChannelParticipantMuteListAddRequest) Set(val *OpenChannelParticipantMuteListAddRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenChannelParticipantMuteListAddRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenChannelParticipantMuteListAddRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenChannelParticipantMuteListAddRequest(val *OpenChannelParticipantMuteListAddRequest) *NullableOpenChannelParticipantMuteListAddRequest {
	return &NullableOpenChannelParticipantMuteListAddRequest{value: val, isSet: true}
}

func (v NullableOpenChannelParticipantMuteListAddRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenChannelParticipantMuteListAddRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


