/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.1
Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserChannelTagRemoveRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserChannelTagRemoveRequest{}

// UserChannelTagRemoveRequest struct for UserChannelTagRemoveRequest
type UserChannelTagRemoveRequest struct {
	UserId string `json:"userId"`
	TagIds []string `json:"tagIds"`
}

type _UserChannelTagRemoveRequest UserChannelTagRemoveRequest

// NewUserChannelTagRemoveRequest instantiates a new UserChannelTagRemoveRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserChannelTagRemoveRequest(userId string, tagIds []string) *UserChannelTagRemoveRequest {
	this := UserChannelTagRemoveRequest{}
	this.UserId = userId
	this.TagIds = tagIds
	return &this
}

// NewUserChannelTagRemoveRequestWithDefaults instantiates a new UserChannelTagRemoveRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserChannelTagRemoveRequestWithDefaults() *UserChannelTagRemoveRequest {
	this := UserChannelTagRemoveRequest{}
	return &this
}

// GetUserId returns the UserId field value
func (o *UserChannelTagRemoveRequest) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *UserChannelTagRemoveRequest) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *UserChannelTagRemoveRequest) SetUserId(v string) {
	o.UserId = v
}

// GetTagIds returns the TagIds field value
func (o *UserChannelTagRemoveRequest) GetTagIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.TagIds
}

// GetTagIdsOk returns a tuple with the TagIds field value
// and a boolean to check if the value has been set.
func (o *UserChannelTagRemoveRequest) GetTagIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TagIds, true
}

// SetTagIds sets field value
func (o *UserChannelTagRemoveRequest) SetTagIds(v []string) {
	o.TagIds = v
}

func (o UserChannelTagRemoveRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserChannelTagRemoveRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["userId"] = o.UserId
	toSerialize["tagIds"] = o.TagIds
	return toSerialize, nil
}

func (o *UserChannelTagRemoveRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"userId",
		"tagIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserChannelTagRemoveRequest := _UserChannelTagRemoveRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserChannelTagRemoveRequest)

	if err != nil {
		return err
	}

	*o = UserChannelTagRemoveRequest(varUserChannelTagRemoveRequest)

	return err
}

type NullableUserChannelTagRemoveRequest struct {
	value *UserChannelTagRemoveRequest
	isSet bool
}

func (v NullableUserChannelTagRemoveRequest) Get() *UserChannelTagRemoveRequest {
	return v.value
}

func (v *NullableUserChannelTagRemoveRequest) Set(val *UserChannelTagRemoveRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserChannelTagRemoveRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserChannelTagRemoveRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserChannelTagRemoveRequest(val *UserChannelTagRemoveRequest) *NullableUserChannelTagRemoveRequest {
	return &NullableUserChannelTagRemoveRequest{value: val, isSet: true}
}

func (v NullableUserChannelTagRemoveRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserChannelTagRemoveRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


