/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.0
Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CommunityChannelFreezeListSetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommunityChannelFreezeListSetRequest{}

// CommunityChannelFreezeListSetRequest struct for CommunityChannelFreezeListSetRequest
type CommunityChannelFreezeListSetRequest struct {
	ChannelId string `json:"channelId"`
	SubchannelId *string `json:"subchannelId,omitempty"`
	// Freeze status for the community channel or subchannel.
	Status bool `json:"status"`
}

type _CommunityChannelFreezeListSetRequest CommunityChannelFreezeListSetRequest

// NewCommunityChannelFreezeListSetRequest instantiates a new CommunityChannelFreezeListSetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommunityChannelFreezeListSetRequest(channelId string, status bool) *CommunityChannelFreezeListSetRequest {
	this := CommunityChannelFreezeListSetRequest{}
	this.ChannelId = channelId
	this.Status = status
	return &this
}

// NewCommunityChannelFreezeListSetRequestWithDefaults instantiates a new CommunityChannelFreezeListSetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommunityChannelFreezeListSetRequestWithDefaults() *CommunityChannelFreezeListSetRequest {
	this := CommunityChannelFreezeListSetRequest{}
	return &this
}

// GetChannelId returns the ChannelId field value
func (o *CommunityChannelFreezeListSetRequest) GetChannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value
// and a boolean to check if the value has been set.
func (o *CommunityChannelFreezeListSetRequest) GetChannelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelId, true
}

// SetChannelId sets field value
func (o *CommunityChannelFreezeListSetRequest) SetChannelId(v string) {
	o.ChannelId = v
}

// GetSubchannelId returns the SubchannelId field value if set, zero value otherwise.
func (o *CommunityChannelFreezeListSetRequest) GetSubchannelId() string {
	if o == nil || IsNil(o.SubchannelId) {
		var ret string
		return ret
	}
	return *o.SubchannelId
}

// GetSubchannelIdOk returns a tuple with the SubchannelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityChannelFreezeListSetRequest) GetSubchannelIdOk() (*string, bool) {
	if o == nil || IsNil(o.SubchannelId) {
		return nil, false
	}
	return o.SubchannelId, true
}

// HasSubchannelId returns a boolean if a field has been set.
func (o *CommunityChannelFreezeListSetRequest) HasSubchannelId() bool {
	if o != nil && !IsNil(o.SubchannelId) {
		return true
	}

	return false
}

// SetSubchannelId gets a reference to the given string and assigns it to the SubchannelId field.
func (o *CommunityChannelFreezeListSetRequest) SetSubchannelId(v string) {
	o.SubchannelId = &v
}

// GetStatus returns the Status field value
func (o *CommunityChannelFreezeListSetRequest) GetStatus() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CommunityChannelFreezeListSetRequest) GetStatusOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CommunityChannelFreezeListSetRequest) SetStatus(v bool) {
	o.Status = v
}

func (o CommunityChannelFreezeListSetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommunityChannelFreezeListSetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channelId"] = o.ChannelId
	if !IsNil(o.SubchannelId) {
		toSerialize["subchannelId"] = o.SubchannelId
	}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *CommunityChannelFreezeListSetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channelId",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommunityChannelFreezeListSetRequest := _CommunityChannelFreezeListSetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCommunityChannelFreezeListSetRequest)

	if err != nil {
		return err
	}

	*o = CommunityChannelFreezeListSetRequest(varCommunityChannelFreezeListSetRequest)

	return err
}

type NullableCommunityChannelFreezeListSetRequest struct {
	value *CommunityChannelFreezeListSetRequest
	isSet bool
}

func (v NullableCommunityChannelFreezeListSetRequest) Get() *CommunityChannelFreezeListSetRequest {
	return v.value
}

func (v *NullableCommunityChannelFreezeListSetRequest) Set(val *CommunityChannelFreezeListSetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCommunityChannelFreezeListSetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCommunityChannelFreezeListSetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommunityChannelFreezeListSetRequest(val *CommunityChannelFreezeListSetRequest) *NullableCommunityChannelFreezeListSetRequest {
	return &NullableCommunityChannelFreezeListSetRequest{value: val, isSet: true}
}

func (v NullableCommunityChannelFreezeListSetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommunityChannelFreezeListSetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


