/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the CommunityChannelSubchannelUserGroupListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommunityChannelSubchannelUserGroupListResponse{}

// CommunityChannelSubchannelUserGroupListResponse struct for CommunityChannelSubchannelUserGroupListResponse
type CommunityChannelSubchannelUserGroupListResponse struct {
	Code int32 `json:"code"`
	Result *CommunityChannelSubchannelUserGroupListResponseResult `json:"result,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CommunityChannelSubchannelUserGroupListResponse CommunityChannelSubchannelUserGroupListResponse

// NewCommunityChannelSubchannelUserGroupListResponse instantiates a new CommunityChannelSubchannelUserGroupListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommunityChannelSubchannelUserGroupListResponse(code int32) *CommunityChannelSubchannelUserGroupListResponse {
	this := CommunityChannelSubchannelUserGroupListResponse{}
	this.Code = code
	return &this
}

// NewCommunityChannelSubchannelUserGroupListResponseWithDefaults instantiates a new CommunityChannelSubchannelUserGroupListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommunityChannelSubchannelUserGroupListResponseWithDefaults() *CommunityChannelSubchannelUserGroupListResponse {
	this := CommunityChannelSubchannelUserGroupListResponse{}
	return &this
}

// GetCode returns the Code field value
func (o *CommunityChannelSubchannelUserGroupListResponse) GetCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *CommunityChannelSubchannelUserGroupListResponse) GetCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *CommunityChannelSubchannelUserGroupListResponse) SetCode(v int32) {
	o.Code = v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *CommunityChannelSubchannelUserGroupListResponse) GetResult() CommunityChannelSubchannelUserGroupListResponseResult {
	if o == nil || IsNil(o.Result) {
		var ret CommunityChannelSubchannelUserGroupListResponseResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityChannelSubchannelUserGroupListResponse) GetResultOk() (*CommunityChannelSubchannelUserGroupListResponseResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *CommunityChannelSubchannelUserGroupListResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given CommunityChannelSubchannelUserGroupListResponseResult and assigns it to the Result field.
func (o *CommunityChannelSubchannelUserGroupListResponse) SetResult(v CommunityChannelSubchannelUserGroupListResponseResult) {
	o.Result = &v
}

func (o CommunityChannelSubchannelUserGroupListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommunityChannelSubchannelUserGroupListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommunityChannelSubchannelUserGroupListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommunityChannelSubchannelUserGroupListResponse := _CommunityChannelSubchannelUserGroupListResponse{}

	err = json.Unmarshal(data, &varCommunityChannelSubchannelUserGroupListResponse)

	if err != nil {
		return err
	}

	*o = CommunityChannelSubchannelUserGroupListResponse(varCommunityChannelSubchannelUserGroupListResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "result")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommunityChannelSubchannelUserGroupListResponse struct {
	value *CommunityChannelSubchannelUserGroupListResponse
	isSet bool
}

func (v NullableCommunityChannelSubchannelUserGroupListResponse) Get() *CommunityChannelSubchannelUserGroupListResponse {
	return v.value
}

func (v *NullableCommunityChannelSubchannelUserGroupListResponse) Set(val *CommunityChannelSubchannelUserGroupListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCommunityChannelSubchannelUserGroupListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCommunityChannelSubchannelUserGroupListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommunityChannelSubchannelUserGroupListResponse(val *CommunityChannelSubchannelUserGroupListResponse) *NullableCommunityChannelSubchannelUserGroupListResponse {
	return &NullableCommunityChannelSubchannelUserGroupListResponse{value: val, isSet: true}
}

func (v NullableCommunityChannelSubchannelUserGroupListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommunityChannelSubchannelUserGroupListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


