/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the GroupChannelMemberListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupChannelMemberListResponse{}

// GroupChannelMemberListResponse struct for GroupChannelMemberListResponse
type GroupChannelMemberListResponse struct {
	Code int32 `json:"code"`
	Result *GroupChannelMemberListResponseResult `json:"result,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GroupChannelMemberListResponse GroupChannelMemberListResponse

// NewGroupChannelMemberListResponse instantiates a new GroupChannelMemberListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupChannelMemberListResponse(code int32) *GroupChannelMemberListResponse {
	this := GroupChannelMemberListResponse{}
	this.Code = code
	return &this
}

// NewGroupChannelMemberListResponseWithDefaults instantiates a new GroupChannelMemberListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupChannelMemberListResponseWithDefaults() *GroupChannelMemberListResponse {
	this := GroupChannelMemberListResponse{}
	return &this
}

// GetCode returns the Code field value
func (o *GroupChannelMemberListResponse) GetCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *GroupChannelMemberListResponse) GetCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *GroupChannelMemberListResponse) SetCode(v int32) {
	o.Code = v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *GroupChannelMemberListResponse) GetResult() GroupChannelMemberListResponseResult {
	if o == nil || IsNil(o.Result) {
		var ret GroupChannelMemberListResponseResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupChannelMemberListResponse) GetResultOk() (*GroupChannelMemberListResponseResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *GroupChannelMemberListResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given GroupChannelMemberListResponseResult and assigns it to the Result field.
func (o *GroupChannelMemberListResponse) SetResult(v GroupChannelMemberListResponseResult) {
	o.Result = &v
}

func (o GroupChannelMemberListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupChannelMemberListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GroupChannelMemberListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupChannelMemberListResponse := _GroupChannelMemberListResponse{}

	err = json.Unmarshal(data, &varGroupChannelMemberListResponse)

	if err != nil {
		return err
	}

	*o = GroupChannelMemberListResponse(varGroupChannelMemberListResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "result")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGroupChannelMemberListResponse struct {
	value *GroupChannelMemberListResponse
	isSet bool
}

func (v NullableGroupChannelMemberListResponse) Get() *GroupChannelMemberListResponse {
	return v.value
}

func (v *NullableGroupChannelMemberListResponse) Set(val *GroupChannelMemberListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupChannelMemberListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupChannelMemberListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupChannelMemberListResponse(val *GroupChannelMemberListResponse) *NullableGroupChannelMemberListResponse {
	return &NullableGroupChannelMemberListResponse{value: val, isSet: true}
}

func (v NullableGroupChannelMemberListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupChannelMemberListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


