/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the GroupChannelAliasGetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupChannelAliasGetRequest{}

// GroupChannelAliasGetRequest struct for GroupChannelAliasGetRequest
type GroupChannelAliasGetRequest struct {
	ChannelId string `json:"channelId"`
	UserId string `json:"userId"`
	AdditionalProperties map[string]interface{}
}

type _GroupChannelAliasGetRequest GroupChannelAliasGetRequest

// NewGroupChannelAliasGetRequest instantiates a new GroupChannelAliasGetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupChannelAliasGetRequest(channelId string, userId string) *GroupChannelAliasGetRequest {
	this := GroupChannelAliasGetRequest{}
	this.ChannelId = channelId
	this.UserId = userId
	return &this
}

// NewGroupChannelAliasGetRequestWithDefaults instantiates a new GroupChannelAliasGetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupChannelAliasGetRequestWithDefaults() *GroupChannelAliasGetRequest {
	this := GroupChannelAliasGetRequest{}
	return &this
}

// GetChannelId returns the ChannelId field value
func (o *GroupChannelAliasGetRequest) GetChannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value
// and a boolean to check if the value has been set.
func (o *GroupChannelAliasGetRequest) GetChannelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelId, true
}

// SetChannelId sets field value
func (o *GroupChannelAliasGetRequest) SetChannelId(v string) {
	o.ChannelId = v
}

// GetUserId returns the UserId field value
func (o *GroupChannelAliasGetRequest) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *GroupChannelAliasGetRequest) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *GroupChannelAliasGetRequest) SetUserId(v string) {
	o.UserId = v
}

func (o GroupChannelAliasGetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupChannelAliasGetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channelId"] = o.ChannelId
	toSerialize["userId"] = o.UserId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GroupChannelAliasGetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channelId",
		"userId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupChannelAliasGetRequest := _GroupChannelAliasGetRequest{}

	err = json.Unmarshal(data, &varGroupChannelAliasGetRequest)

	if err != nil {
		return err
	}

	*o = GroupChannelAliasGetRequest(varGroupChannelAliasGetRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "channelId")
		delete(additionalProperties, "userId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGroupChannelAliasGetRequest struct {
	value *GroupChannelAliasGetRequest
	isSet bool
}

func (v NullableGroupChannelAliasGetRequest) Get() *GroupChannelAliasGetRequest {
	return v.value
}

func (v *NullableGroupChannelAliasGetRequest) Set(val *GroupChannelAliasGetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupChannelAliasGetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupChannelAliasGetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupChannelAliasGetRequest(val *GroupChannelAliasGetRequest) *NullableGroupChannelAliasGetRequest {
	return &NullableGroupChannelAliasGetRequest{value: val, isSet: true}
}

func (v NullableGroupChannelAliasGetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupChannelAliasGetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


