/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.1
Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GroupChannelAllowedSenderListUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupChannelAllowedSenderListUpdateRequest{}

// GroupChannelAllowedSenderListUpdateRequest struct for GroupChannelAllowedSenderListUpdateRequest
type GroupChannelAllowedSenderListUpdateRequest struct {
	ChannelId string `json:"channelId"`
	UserIds []string `json:"userIds"`
}

type _GroupChannelAllowedSenderListUpdateRequest GroupChannelAllowedSenderListUpdateRequest

// NewGroupChannelAllowedSenderListUpdateRequest instantiates a new GroupChannelAllowedSenderListUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupChannelAllowedSenderListUpdateRequest(channelId string, userIds []string) *GroupChannelAllowedSenderListUpdateRequest {
	this := GroupChannelAllowedSenderListUpdateRequest{}
	this.ChannelId = channelId
	this.UserIds = userIds
	return &this
}

// NewGroupChannelAllowedSenderListUpdateRequestWithDefaults instantiates a new GroupChannelAllowedSenderListUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupChannelAllowedSenderListUpdateRequestWithDefaults() *GroupChannelAllowedSenderListUpdateRequest {
	this := GroupChannelAllowedSenderListUpdateRequest{}
	return &this
}

// GetChannelId returns the ChannelId field value
func (o *GroupChannelAllowedSenderListUpdateRequest) GetChannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value
// and a boolean to check if the value has been set.
func (o *GroupChannelAllowedSenderListUpdateRequest) GetChannelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelId, true
}

// SetChannelId sets field value
func (o *GroupChannelAllowedSenderListUpdateRequest) SetChannelId(v string) {
	o.ChannelId = v
}

// GetUserIds returns the UserIds field value
func (o *GroupChannelAllowedSenderListUpdateRequest) GetUserIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.UserIds
}

// GetUserIdsOk returns a tuple with the UserIds field value
// and a boolean to check if the value has been set.
func (o *GroupChannelAllowedSenderListUpdateRequest) GetUserIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserIds, true
}

// SetUserIds sets field value
func (o *GroupChannelAllowedSenderListUpdateRequest) SetUserIds(v []string) {
	o.UserIds = v
}

func (o GroupChannelAllowedSenderListUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupChannelAllowedSenderListUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channelId"] = o.ChannelId
	toSerialize["userIds"] = o.UserIds
	return toSerialize, nil
}

func (o *GroupChannelAllowedSenderListUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channelId",
		"userIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupChannelAllowedSenderListUpdateRequest := _GroupChannelAllowedSenderListUpdateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupChannelAllowedSenderListUpdateRequest)

	if err != nil {
		return err
	}

	*o = GroupChannelAllowedSenderListUpdateRequest(varGroupChannelAllowedSenderListUpdateRequest)

	return err
}

type NullableGroupChannelAllowedSenderListUpdateRequest struct {
	value *GroupChannelAllowedSenderListUpdateRequest
	isSet bool
}

func (v NullableGroupChannelAllowedSenderListUpdateRequest) Get() *GroupChannelAllowedSenderListUpdateRequest {
	return v.value
}

func (v *NullableGroupChannelAllowedSenderListUpdateRequest) Set(val *GroupChannelAllowedSenderListUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupChannelAllowedSenderListUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupChannelAllowedSenderListUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupChannelAllowedSenderListUpdateRequest(val *GroupChannelAllowedSenderListUpdateRequest) *NullableGroupChannelAllowedSenderListUpdateRequest {
	return &NullableGroupChannelAllowedSenderListUpdateRequest{value: val, isSet: true}
}

func (v NullableGroupChannelAllowedSenderListUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupChannelAllowedSenderListUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


