/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.0
Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserProfileSetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserProfileSetRequest{}

// UserProfileSetRequest struct for UserProfileSetRequest
type UserProfileSetRequest struct {
	UserId string
	// Basic profile payload. Either `userProfile` or `userExtProfile` must be provided.
	UserProfile map[string]interface{}
	// Extended profile payload. Keys are case-sensitive, should use the `ext_` prefix, and values must be strings. Either `userProfile` or `userExtProfile` must be provided. 
	UserExtProfile *map[string]string
}

type _UserProfileSetRequest UserProfileSetRequest

// NewUserProfileSetRequest instantiates a new UserProfileSetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserProfileSetRequest(userId string) *UserProfileSetRequest {
	this := UserProfileSetRequest{}
	return &this
}

// NewUserProfileSetRequestWithDefaults instantiates a new UserProfileSetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserProfileSetRequestWithDefaults() *UserProfileSetRequest {
	this := UserProfileSetRequest{}
	return &this
}

// GetUserId returns the UserId field value
func (o *UserProfileSetRequest) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *UserProfileSetRequest) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *UserProfileSetRequest) SetUserId(v string) {
	o.UserId = v
}

// GetUserProfile returns the UserProfile field value if set, zero value otherwise.
func (o *UserProfileSetRequest) GetUserProfile() map[string]interface{} {
	if o == nil || IsNil(o.UserProfile) {
		var ret map[string]interface{}
		return ret
	}
	return o.UserProfile
}

// GetUserProfileOk returns a tuple with the UserProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProfileSetRequest) GetUserProfileOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.UserProfile) {
		return map[string]interface{}{}, false
	}
	return o.UserProfile, true
}

// HasUserProfile returns a boolean if a field has been set.
func (o *UserProfileSetRequest) HasUserProfile() bool {
	if o != nil && !IsNil(o.UserProfile) {
		return true
	}

	return false
}

// SetUserProfile gets a reference to the given map[string]interface{} and assigns it to the UserProfile field.
func (o *UserProfileSetRequest) SetUserProfile(v map[string]interface{}) {
	o.UserProfile = v
}

// GetUserExtProfile returns the UserExtProfile field value if set, zero value otherwise.
func (o *UserProfileSetRequest) GetUserExtProfile() map[string]string {
	if o == nil || IsNil(o.UserExtProfile) {
		var ret map[string]string
		return ret
	}
	return *o.UserExtProfile
}

// GetUserExtProfileOk returns a tuple with the UserExtProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProfileSetRequest) GetUserExtProfileOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.UserExtProfile) {
		return nil, false
	}
	return o.UserExtProfile, true
}

// HasUserExtProfile returns a boolean if a field has been set.
func (o *UserProfileSetRequest) HasUserExtProfile() bool {
	if o != nil && !IsNil(o.UserExtProfile) {
		return true
	}

	return false
}

// SetUserExtProfile gets a reference to the given map[string]string and assigns it to the UserExtProfile field.
func (o *UserProfileSetRequest) SetUserExtProfile(v map[string]string) {
	o.UserExtProfile = &v
}

func (o UserProfileSetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserProfileSetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["userId"] = o.UserId
	if !IsNil(o.UserProfile) {
		toSerialize["userProfile"] = o.UserProfile
	}
	if !IsNil(o.UserExtProfile) {
		toSerialize["userExtProfile"] = o.UserExtProfile
	}
	return toSerialize, nil
}

func (o *UserProfileSetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"userId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserProfileSetRequest := _UserProfileSetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserProfileSetRequest)

	if err != nil {
		return err
	}

	*o = UserProfileSetRequest(varUserProfileSetRequest)

	return err
}

type NullableUserProfileSetRequest struct {
	value *UserProfileSetRequest
	isSet bool
}

func (v NullableUserProfileSetRequest) Get() *UserProfileSetRequest {
	return v.value
}

func (v *NullableUserProfileSetRequest) Set(val *UserProfileSetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserProfileSetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserProfileSetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserProfileSetRequest(val *UserProfileSetRequest) *NullableUserProfileSetRequest {
	return &NullableUserProfileSetRequest{value: val, isSet: true}
}

func (v NullableUserProfileSetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserProfileSetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


