/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChannelTypeMessageMetadataDeleteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelTypeMessageMetadataDeleteRequest{}

// ChannelTypeMessageMetadataDeleteRequest struct for ChannelTypeMessageMetadataDeleteRequest
type ChannelTypeMessageMetadataDeleteRequest struct {
	MessageId string `json:"messageId"`
	UserId string `json:"userId"`
	// Supports direct and group channels. Legacy field name is `conversationType`.
	ChannelType int32 `json:"channelType"`
	// Legacy `targetId`.
	ChannelId string `json:"channelId"`
	Keys []string `json:"keys"`
	// Legacy `syncToSender`. `0` by default.
	SyncToSender *int32 `json:"syncToSender,omitempty"`
}

type _ChannelTypeMessageMetadataDeleteRequest ChannelTypeMessageMetadataDeleteRequest

// NewChannelTypeMessageMetadataDeleteRequest instantiates a new ChannelTypeMessageMetadataDeleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelTypeMessageMetadataDeleteRequest(messageId string, userId string, channelType int32, channelId string, keys []string) *ChannelTypeMessageMetadataDeleteRequest {
	this := ChannelTypeMessageMetadataDeleteRequest{}
	this.MessageId = messageId
	this.UserId = userId
	this.ChannelType = channelType
	this.ChannelId = channelId
	this.Keys = keys
	return &this
}

// NewChannelTypeMessageMetadataDeleteRequestWithDefaults instantiates a new ChannelTypeMessageMetadataDeleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelTypeMessageMetadataDeleteRequestWithDefaults() *ChannelTypeMessageMetadataDeleteRequest {
	this := ChannelTypeMessageMetadataDeleteRequest{}
	return &this
}

// GetMessageId returns the MessageId field value
func (o *ChannelTypeMessageMetadataDeleteRequest) GetMessageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MessageId
}

// GetMessageIdOk returns a tuple with the MessageId field value
// and a boolean to check if the value has been set.
func (o *ChannelTypeMessageMetadataDeleteRequest) GetMessageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MessageId, true
}

// SetMessageId sets field value
func (o *ChannelTypeMessageMetadataDeleteRequest) SetMessageId(v string) {
	o.MessageId = v
}

// GetUserId returns the UserId field value
func (o *ChannelTypeMessageMetadataDeleteRequest) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *ChannelTypeMessageMetadataDeleteRequest) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *ChannelTypeMessageMetadataDeleteRequest) SetUserId(v string) {
	o.UserId = v
}

// GetChannelType returns the ChannelType field value
func (o *ChannelTypeMessageMetadataDeleteRequest) GetChannelType() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChannelType
}

// GetChannelTypeOk returns a tuple with the ChannelType field value
// and a boolean to check if the value has been set.
func (o *ChannelTypeMessageMetadataDeleteRequest) GetChannelTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelType, true
}

// SetChannelType sets field value
func (o *ChannelTypeMessageMetadataDeleteRequest) SetChannelType(v int32) {
	o.ChannelType = v
}

// GetChannelId returns the ChannelId field value
func (o *ChannelTypeMessageMetadataDeleteRequest) GetChannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value
// and a boolean to check if the value has been set.
func (o *ChannelTypeMessageMetadataDeleteRequest) GetChannelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelId, true
}

// SetChannelId sets field value
func (o *ChannelTypeMessageMetadataDeleteRequest) SetChannelId(v string) {
	o.ChannelId = v
}

// GetKeys returns the Keys field value
func (o *ChannelTypeMessageMetadataDeleteRequest) GetKeys() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Keys
}

// GetKeysOk returns a tuple with the Keys field value
// and a boolean to check if the value has been set.
func (o *ChannelTypeMessageMetadataDeleteRequest) GetKeysOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Keys, true
}

// SetKeys sets field value
func (o *ChannelTypeMessageMetadataDeleteRequest) SetKeys(v []string) {
	o.Keys = v
}

// GetSyncToSender returns the SyncToSender field value if set, zero value otherwise.
func (o *ChannelTypeMessageMetadataDeleteRequest) GetSyncToSender() int32 {
	if o == nil || IsNil(o.SyncToSender) {
		var ret int32
		return ret
	}
	return *o.SyncToSender
}

// GetSyncToSenderOk returns a tuple with the SyncToSender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelTypeMessageMetadataDeleteRequest) GetSyncToSenderOk() (*int32, bool) {
	if o == nil || IsNil(o.SyncToSender) {
		return nil, false
	}
	return o.SyncToSender, true
}

// HasSyncToSender returns a boolean if a field has been set.
func (o *ChannelTypeMessageMetadataDeleteRequest) HasSyncToSender() bool {
	if o != nil && !IsNil(o.SyncToSender) {
		return true
	}

	return false
}

// SetSyncToSender gets a reference to the given int32 and assigns it to the SyncToSender field.
func (o *ChannelTypeMessageMetadataDeleteRequest) SetSyncToSender(v int32) {
	o.SyncToSender = &v
}

func (o ChannelTypeMessageMetadataDeleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelTypeMessageMetadataDeleteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["messageId"] = o.MessageId
	toSerialize["userId"] = o.UserId
	toSerialize["channelType"] = o.ChannelType
	toSerialize["channelId"] = o.ChannelId
	toSerialize["keys"] = o.Keys
	if !IsNil(o.SyncToSender) {
		toSerialize["syncToSender"] = o.SyncToSender
	}
	return toSerialize, nil
}

func (o *ChannelTypeMessageMetadataDeleteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"messageId",
		"userId",
		"channelType",
		"channelId",
		"keys",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChannelTypeMessageMetadataDeleteRequest := _ChannelTypeMessageMetadataDeleteRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChannelTypeMessageMetadataDeleteRequest)

	if err != nil {
		return err
	}

	*o = ChannelTypeMessageMetadataDeleteRequest(varChannelTypeMessageMetadataDeleteRequest)

	return err
}

type NullableChannelTypeMessageMetadataDeleteRequest struct {
	value *ChannelTypeMessageMetadataDeleteRequest
	isSet bool
}

func (v NullableChannelTypeMessageMetadataDeleteRequest) Get() *ChannelTypeMessageMetadataDeleteRequest {
	return v.value
}

func (v *NullableChannelTypeMessageMetadataDeleteRequest) Set(val *ChannelTypeMessageMetadataDeleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelTypeMessageMetadataDeleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelTypeMessageMetadataDeleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelTypeMessageMetadataDeleteRequest(val *ChannelTypeMessageMetadataDeleteRequest) *NullableChannelTypeMessageMetadataDeleteRequest {
	return &NullableChannelTypeMessageMetadataDeleteRequest{value: val, isSet: true}
}

func (v NullableChannelTypeMessageMetadataDeleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelTypeMessageMetadataDeleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


