/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OpenChannelGlobalMuteListRemoveRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenChannelGlobalMuteListRemoveRequest{}

// OpenChannelGlobalMuteListRemoveRequest struct for OpenChannelGlobalMuteListRemoveRequest
type OpenChannelGlobalMuteListRemoveRequest struct {
	ParticipantIds []string `json:"participantIds"`
	// Notification extra payload in JSON string format.
	Extra *string `json:"extra,omitempty"`
	NeedNotify *bool `json:"needNotify,omitempty"`
}

type _OpenChannelGlobalMuteListRemoveRequest OpenChannelGlobalMuteListRemoveRequest

// NewOpenChannelGlobalMuteListRemoveRequest instantiates a new OpenChannelGlobalMuteListRemoveRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenChannelGlobalMuteListRemoveRequest(participantIds []string) *OpenChannelGlobalMuteListRemoveRequest {
	this := OpenChannelGlobalMuteListRemoveRequest{}
	this.ParticipantIds = participantIds
	return &this
}

// NewOpenChannelGlobalMuteListRemoveRequestWithDefaults instantiates a new OpenChannelGlobalMuteListRemoveRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenChannelGlobalMuteListRemoveRequestWithDefaults() *OpenChannelGlobalMuteListRemoveRequest {
	this := OpenChannelGlobalMuteListRemoveRequest{}
	return &this
}

// GetParticipantIds returns the ParticipantIds field value
func (o *OpenChannelGlobalMuteListRemoveRequest) GetParticipantIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ParticipantIds
}

// GetParticipantIdsOk returns a tuple with the ParticipantIds field value
// and a boolean to check if the value has been set.
func (o *OpenChannelGlobalMuteListRemoveRequest) GetParticipantIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParticipantIds, true
}

// SetParticipantIds sets field value
func (o *OpenChannelGlobalMuteListRemoveRequest) SetParticipantIds(v []string) {
	o.ParticipantIds = v
}

// GetExtra returns the Extra field value if set, zero value otherwise.
func (o *OpenChannelGlobalMuteListRemoveRequest) GetExtra() string {
	if o == nil || IsNil(o.Extra) {
		var ret string
		return ret
	}
	return *o.Extra
}

// GetExtraOk returns a tuple with the Extra field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelGlobalMuteListRemoveRequest) GetExtraOk() (*string, bool) {
	if o == nil || IsNil(o.Extra) {
		return nil, false
	}
	return o.Extra, true
}

// HasExtra returns a boolean if a field has been set.
func (o *OpenChannelGlobalMuteListRemoveRequest) HasExtra() bool {
	if o != nil && !IsNil(o.Extra) {
		return true
	}

	return false
}

// SetExtra gets a reference to the given string and assigns it to the Extra field.
func (o *OpenChannelGlobalMuteListRemoveRequest) SetExtra(v string) {
	o.Extra = &v
}

// GetNeedNotify returns the NeedNotify field value if set, zero value otherwise.
func (o *OpenChannelGlobalMuteListRemoveRequest) GetNeedNotify() bool {
	if o == nil || IsNil(o.NeedNotify) {
		var ret bool
		return ret
	}
	return *o.NeedNotify
}

// GetNeedNotifyOk returns a tuple with the NeedNotify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelGlobalMuteListRemoveRequest) GetNeedNotifyOk() (*bool, bool) {
	if o == nil || IsNil(o.NeedNotify) {
		return nil, false
	}
	return o.NeedNotify, true
}

// HasNeedNotify returns a boolean if a field has been set.
func (o *OpenChannelGlobalMuteListRemoveRequest) HasNeedNotify() bool {
	if o != nil && !IsNil(o.NeedNotify) {
		return true
	}

	return false
}

// SetNeedNotify gets a reference to the given bool and assigns it to the NeedNotify field.
func (o *OpenChannelGlobalMuteListRemoveRequest) SetNeedNotify(v bool) {
	o.NeedNotify = &v
}

func (o OpenChannelGlobalMuteListRemoveRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenChannelGlobalMuteListRemoveRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["participantIds"] = o.ParticipantIds
	if !IsNil(o.Extra) {
		toSerialize["extra"] = o.Extra
	}
	if !IsNil(o.NeedNotify) {
		toSerialize["needNotify"] = o.NeedNotify
	}
	return toSerialize, nil
}

func (o *OpenChannelGlobalMuteListRemoveRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"participantIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenChannelGlobalMuteListRemoveRequest := _OpenChannelGlobalMuteListRemoveRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenChannelGlobalMuteListRemoveRequest)

	if err != nil {
		return err
	}

	*o = OpenChannelGlobalMuteListRemoveRequest(varOpenChannelGlobalMuteListRemoveRequest)

	return err
}

type NullableOpenChannelGlobalMuteListRemoveRequest struct {
	value *OpenChannelGlobalMuteListRemoveRequest
	isSet bool
}

func (v NullableOpenChannelGlobalMuteListRemoveRequest) Get() *OpenChannelGlobalMuteListRemoveRequest {
	return v.value
}

func (v *NullableOpenChannelGlobalMuteListRemoveRequest) Set(val *OpenChannelGlobalMuteListRemoveRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenChannelGlobalMuteListRemoveRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenChannelGlobalMuteListRemoveRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenChannelGlobalMuteListRemoveRequest(val *OpenChannelGlobalMuteListRemoveRequest) *NullableOpenChannelGlobalMuteListRemoveRequest {
	return &NullableOpenChannelGlobalMuteListRemoveRequest{value: val, isSet: true}
}

func (v NullableOpenChannelGlobalMuteListRemoveRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenChannelGlobalMuteListRemoveRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


