/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.1
Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FriendAddRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FriendAddRequest{}

// FriendAddRequest struct for FriendAddRequest
type FriendAddRequest struct {
	UserId string `json:"userId"`
	TargetId string `json:"targetId"`
	// `1` means add with verification and `2` means add directly.
	Action *int32 `json:"action,omitempty"`
	Extra *string `json:"extra,omitempty"`
}

type _FriendAddRequest FriendAddRequest

// NewFriendAddRequest instantiates a new FriendAddRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFriendAddRequest(userId string, targetId string) *FriendAddRequest {
	this := FriendAddRequest{}
	this.UserId = userId
	this.TargetId = targetId
	return &this
}

// NewFriendAddRequestWithDefaults instantiates a new FriendAddRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFriendAddRequestWithDefaults() *FriendAddRequest {
	this := FriendAddRequest{}
	return &this
}

// GetUserId returns the UserId field value
func (o *FriendAddRequest) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *FriendAddRequest) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *FriendAddRequest) SetUserId(v string) {
	o.UserId = v
}

// GetTargetId returns the TargetId field value
func (o *FriendAddRequest) GetTargetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetId
}

// GetTargetIdOk returns a tuple with the TargetId field value
// and a boolean to check if the value has been set.
func (o *FriendAddRequest) GetTargetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetId, true
}

// SetTargetId sets field value
func (o *FriendAddRequest) SetTargetId(v string) {
	o.TargetId = v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *FriendAddRequest) GetAction() int32 {
	if o == nil || IsNil(o.Action) {
		var ret int32
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FriendAddRequest) GetActionOk() (*int32, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *FriendAddRequest) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given int32 and assigns it to the Action field.
func (o *FriendAddRequest) SetAction(v int32) {
	o.Action = &v
}

// GetExtra returns the Extra field value if set, zero value otherwise.
func (o *FriendAddRequest) GetExtra() string {
	if o == nil || IsNil(o.Extra) {
		var ret string
		return ret
	}
	return *o.Extra
}

// GetExtraOk returns a tuple with the Extra field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FriendAddRequest) GetExtraOk() (*string, bool) {
	if o == nil || IsNil(o.Extra) {
		return nil, false
	}
	return o.Extra, true
}

// HasExtra returns a boolean if a field has been set.
func (o *FriendAddRequest) HasExtra() bool {
	if o != nil && !IsNil(o.Extra) {
		return true
	}

	return false
}

// SetExtra gets a reference to the given string and assigns it to the Extra field.
func (o *FriendAddRequest) SetExtra(v string) {
	o.Extra = &v
}

func (o FriendAddRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FriendAddRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["userId"] = o.UserId
	toSerialize["targetId"] = o.TargetId
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.Extra) {
		toSerialize["extra"] = o.Extra
	}
	return toSerialize, nil
}

func (o *FriendAddRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"userId",
		"targetId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFriendAddRequest := _FriendAddRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFriendAddRequest)

	if err != nil {
		return err
	}

	*o = FriendAddRequest(varFriendAddRequest)

	return err
}

type NullableFriendAddRequest struct {
	value *FriendAddRequest
	isSet bool
}

func (v NullableFriendAddRequest) Get() *FriendAddRequest {
	return v.value
}

func (v *NullableFriendAddRequest) Set(val *FriendAddRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFriendAddRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFriendAddRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFriendAddRequest(val *FriendAddRequest) *NullableFriendAddRequest {
	return &NullableFriendAddRequest{value: val, isSet: true}
}

func (v NullableFriendAddRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFriendAddRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


