/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the GroupChannelProfileListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupChannelProfileListResponse{}

// GroupChannelProfileListResponse struct for GroupChannelProfileListResponse
type GroupChannelProfileListResponse struct {
	Code int32 `json:"code"`
	Result *GroupChannelProfileListResponseResult `json:"result,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GroupChannelProfileListResponse GroupChannelProfileListResponse

// NewGroupChannelProfileListResponse instantiates a new GroupChannelProfileListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupChannelProfileListResponse(code int32) *GroupChannelProfileListResponse {
	this := GroupChannelProfileListResponse{}
	this.Code = code
	return &this
}

// NewGroupChannelProfileListResponseWithDefaults instantiates a new GroupChannelProfileListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupChannelProfileListResponseWithDefaults() *GroupChannelProfileListResponse {
	this := GroupChannelProfileListResponse{}
	return &this
}

// GetCode returns the Code field value
func (o *GroupChannelProfileListResponse) GetCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *GroupChannelProfileListResponse) GetCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *GroupChannelProfileListResponse) SetCode(v int32) {
	o.Code = v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *GroupChannelProfileListResponse) GetResult() GroupChannelProfileListResponseResult {
	if o == nil || IsNil(o.Result) {
		var ret GroupChannelProfileListResponseResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupChannelProfileListResponse) GetResultOk() (*GroupChannelProfileListResponseResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *GroupChannelProfileListResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given GroupChannelProfileListResponseResult and assigns it to the Result field.
func (o *GroupChannelProfileListResponse) SetResult(v GroupChannelProfileListResponseResult) {
	o.Result = &v
}

func (o GroupChannelProfileListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupChannelProfileListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GroupChannelProfileListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupChannelProfileListResponse := _GroupChannelProfileListResponse{}

	err = json.Unmarshal(data, &varGroupChannelProfileListResponse)

	if err != nil {
		return err
	}

	*o = GroupChannelProfileListResponse(varGroupChannelProfileListResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "result")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGroupChannelProfileListResponse struct {
	value *GroupChannelProfileListResponse
	isSet bool
}

func (v NullableGroupChannelProfileListResponse) Get() *GroupChannelProfileListResponse {
	return v.value
}

func (v *NullableGroupChannelProfileListResponse) Set(val *GroupChannelProfileListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupChannelProfileListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupChannelProfileListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupChannelProfileListResponse(val *GroupChannelProfileListResponse) *NullableGroupChannelProfileListResponse {
	return &NullableGroupChannelProfileListResponse{value: val, isSet: true}
}

func (v NullableGroupChannelProfileListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupChannelProfileListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


