/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.1
Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
)

// checks if the CommunityChannelMutedMemberItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommunityChannelMutedMemberItem{}

// CommunityChannelMutedMemberItem struct for CommunityChannelMutedMemberItem
type CommunityChannelMutedMemberItem struct {
	UserId *string `json:"userId,omitempty"`
}

// NewCommunityChannelMutedMemberItem instantiates a new CommunityChannelMutedMemberItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommunityChannelMutedMemberItem() *CommunityChannelMutedMemberItem {
	this := CommunityChannelMutedMemberItem{}
	return &this
}

// NewCommunityChannelMutedMemberItemWithDefaults instantiates a new CommunityChannelMutedMemberItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommunityChannelMutedMemberItemWithDefaults() *CommunityChannelMutedMemberItem {
	this := CommunityChannelMutedMemberItem{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *CommunityChannelMutedMemberItem) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityChannelMutedMemberItem) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *CommunityChannelMutedMemberItem) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *CommunityChannelMutedMemberItem) SetUserId(v string) {
	o.UserId = &v
}

func (o CommunityChannelMutedMemberItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommunityChannelMutedMemberItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	return toSerialize, nil
}

type NullableCommunityChannelMutedMemberItem struct {
	value *CommunityChannelMutedMemberItem
	isSet bool
}

func (v NullableCommunityChannelMutedMemberItem) Get() *CommunityChannelMutedMemberItem {
	return v.value
}

func (v *NullableCommunityChannelMutedMemberItem) Set(val *CommunityChannelMutedMemberItem) {
	v.value = val
	v.isSet = true
}

func (v NullableCommunityChannelMutedMemberItem) IsSet() bool {
	return v.isSet
}

func (v *NullableCommunityChannelMutedMemberItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommunityChannelMutedMemberItem(val *CommunityChannelMutedMemberItem) *NullableCommunityChannelMutedMemberItem {
	return &NullableCommunityChannelMutedMemberItem{value: val, isSet: true}
}

func (v NullableCommunityChannelMutedMemberItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommunityChannelMutedMemberItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


