/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the CommunityChannelUserGroupListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommunityChannelUserGroupListRequest{}

// CommunityChannelUserGroupListRequest struct for CommunityChannelUserGroupListRequest
type CommunityChannelUserGroupListRequest struct {
	ChannelId string `json:"channelId"`
	Page *int32 `json:"page,omitempty"`
	PageSize *int32 `json:"pageSize,omitempty"`
	// Sort order from `CommunityChannelPageInput`.
	Order *int32 `json:"order,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CommunityChannelUserGroupListRequest CommunityChannelUserGroupListRequest

// NewCommunityChannelUserGroupListRequest instantiates a new CommunityChannelUserGroupListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommunityChannelUserGroupListRequest(channelId string) *CommunityChannelUserGroupListRequest {
	this := CommunityChannelUserGroupListRequest{}
	this.ChannelId = channelId
	var page int32 = 1
	this.Page = &page
	var pageSize int32 = 10
	this.PageSize = &pageSize
	return &this
}

// NewCommunityChannelUserGroupListRequestWithDefaults instantiates a new CommunityChannelUserGroupListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommunityChannelUserGroupListRequestWithDefaults() *CommunityChannelUserGroupListRequest {
	this := CommunityChannelUserGroupListRequest{}
	var page int32 = 1
	this.Page = &page
	var pageSize int32 = 10
	this.PageSize = &pageSize
	return &this
}

// GetChannelId returns the ChannelId field value
func (o *CommunityChannelUserGroupListRequest) GetChannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value
// and a boolean to check if the value has been set.
func (o *CommunityChannelUserGroupListRequest) GetChannelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelId, true
}

// SetChannelId sets field value
func (o *CommunityChannelUserGroupListRequest) SetChannelId(v string) {
	o.ChannelId = v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *CommunityChannelUserGroupListRequest) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityChannelUserGroupListRequest) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *CommunityChannelUserGroupListRequest) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *CommunityChannelUserGroupListRequest) SetPage(v int32) {
	o.Page = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *CommunityChannelUserGroupListRequest) GetPageSize() int32 {
	if o == nil || IsNil(o.PageSize) {
		var ret int32
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityChannelUserGroupListRequest) GetPageSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *CommunityChannelUserGroupListRequest) HasPageSize() bool {
	if o != nil && !IsNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given int32 and assigns it to the PageSize field.
func (o *CommunityChannelUserGroupListRequest) SetPageSize(v int32) {
	o.PageSize = &v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *CommunityChannelUserGroupListRequest) GetOrder() int32 {
	if o == nil || IsNil(o.Order) {
		var ret int32
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityChannelUserGroupListRequest) GetOrderOk() (*int32, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *CommunityChannelUserGroupListRequest) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given int32 and assigns it to the Order field.
func (o *CommunityChannelUserGroupListRequest) SetOrder(v int32) {
	o.Order = &v
}

func (o CommunityChannelUserGroupListRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommunityChannelUserGroupListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channelId"] = o.ChannelId
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.PageSize) {
		toSerialize["pageSize"] = o.PageSize
	}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommunityChannelUserGroupListRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channelId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommunityChannelUserGroupListRequest := _CommunityChannelUserGroupListRequest{}

	err = json.Unmarshal(data, &varCommunityChannelUserGroupListRequest)

	if err != nil {
		return err
	}

	*o = CommunityChannelUserGroupListRequest(varCommunityChannelUserGroupListRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "channelId")
		delete(additionalProperties, "page")
		delete(additionalProperties, "pageSize")
		delete(additionalProperties, "order")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommunityChannelUserGroupListRequest struct {
	value *CommunityChannelUserGroupListRequest
	isSet bool
}

func (v NullableCommunityChannelUserGroupListRequest) Get() *CommunityChannelUserGroupListRequest {
	return v.value
}

func (v *NullableCommunityChannelUserGroupListRequest) Set(val *CommunityChannelUserGroupListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCommunityChannelUserGroupListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCommunityChannelUserGroupListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommunityChannelUserGroupListRequest(val *CommunityChannelUserGroupListRequest) *NullableCommunityChannelUserGroupListRequest {
	return &NullableCommunityChannelUserGroupListRequest{value: val, isSet: true}
}

func (v NullableCommunityChannelUserGroupListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommunityChannelUserGroupListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


