/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.0
Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
)

// checks if the FriendPermissionItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FriendPermissionItem{}

// FriendPermissionItem struct for FriendPermissionItem
type FriendPermissionItem struct {
	UserId *string `json:"userId,omitempty"`
	PermissionType *int32 `json:"permissionType,omitempty"`
}

// NewFriendPermissionItem instantiates a new FriendPermissionItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFriendPermissionItem() *FriendPermissionItem {
	this := FriendPermissionItem{}
	return &this
}

// NewFriendPermissionItemWithDefaults instantiates a new FriendPermissionItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFriendPermissionItemWithDefaults() *FriendPermissionItem {
	this := FriendPermissionItem{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *FriendPermissionItem) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FriendPermissionItem) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *FriendPermissionItem) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *FriendPermissionItem) SetUserId(v string) {
	o.UserId = &v
}

// GetPermissionType returns the PermissionType field value if set, zero value otherwise.
func (o *FriendPermissionItem) GetPermissionType() int32 {
	if o == nil || IsNil(o.PermissionType) {
		var ret int32
		return ret
	}
	return *o.PermissionType
}

// GetPermissionTypeOk returns a tuple with the PermissionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FriendPermissionItem) GetPermissionTypeOk() (*int32, bool) {
	if o == nil || IsNil(o.PermissionType) {
		return nil, false
	}
	return o.PermissionType, true
}

// HasPermissionType returns a boolean if a field has been set.
func (o *FriendPermissionItem) HasPermissionType() bool {
	if o != nil && !IsNil(o.PermissionType) {
		return true
	}

	return false
}

// SetPermissionType gets a reference to the given int32 and assigns it to the PermissionType field.
func (o *FriendPermissionItem) SetPermissionType(v int32) {
	o.PermissionType = &v
}

func (o FriendPermissionItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FriendPermissionItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	if !IsNil(o.PermissionType) {
		toSerialize["permissionType"] = o.PermissionType
	}
	return toSerialize, nil
}

type NullableFriendPermissionItem struct {
	value *FriendPermissionItem
	isSet bool
}

func (v NullableFriendPermissionItem) Get() *FriendPermissionItem {
	return v.value
}

func (v *NullableFriendPermissionItem) Set(val *FriendPermissionItem) {
	v.value = val
	v.isSet = true
}

func (v NullableFriendPermissionItem) IsSet() bool {
	return v.isSet
}

func (v *NullableFriendPermissionItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFriendPermissionItem(val *FriendPermissionItem) *NullableFriendPermissionItem {
	return &NullableFriendPermissionItem{value: val, isSet: true}
}

func (v NullableFriendPermissionItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFriendPermissionItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


