/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.0
Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SystemChannelBroadcastOnlineRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemChannelBroadcastOnlineRequest{}

// SystemChannelBroadcastOnlineRequest struct for SystemChannelBroadcastOnlineRequest
type SystemChannelBroadcastOnlineRequest struct {
	FromUserId string `json:"fromUserId"`
	MessageType string `json:"messageType"`
	Content string `json:"content"`
	DisableUpdateLastMsg *bool `json:"disableUpdateLastMsg,omitempty"`
}

type _SystemChannelBroadcastOnlineRequest SystemChannelBroadcastOnlineRequest

// NewSystemChannelBroadcastOnlineRequest instantiates a new SystemChannelBroadcastOnlineRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemChannelBroadcastOnlineRequest(fromUserId string, messageType string, content string) *SystemChannelBroadcastOnlineRequest {
	this := SystemChannelBroadcastOnlineRequest{}
	this.FromUserId = fromUserId
	this.MessageType = messageType
	this.Content = content
	return &this
}

// NewSystemChannelBroadcastOnlineRequestWithDefaults instantiates a new SystemChannelBroadcastOnlineRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemChannelBroadcastOnlineRequestWithDefaults() *SystemChannelBroadcastOnlineRequest {
	this := SystemChannelBroadcastOnlineRequest{}
	return &this
}

// GetFromUserId returns the FromUserId field value
func (o *SystemChannelBroadcastOnlineRequest) GetFromUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FromUserId
}

// GetFromUserIdOk returns a tuple with the FromUserId field value
// and a boolean to check if the value has been set.
func (o *SystemChannelBroadcastOnlineRequest) GetFromUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromUserId, true
}

// SetFromUserId sets field value
func (o *SystemChannelBroadcastOnlineRequest) SetFromUserId(v string) {
	o.FromUserId = v
}

// GetMessageType returns the MessageType field value
func (o *SystemChannelBroadcastOnlineRequest) GetMessageType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MessageType
}

// GetMessageTypeOk returns a tuple with the MessageType field value
// and a boolean to check if the value has been set.
func (o *SystemChannelBroadcastOnlineRequest) GetMessageTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MessageType, true
}

// SetMessageType sets field value
func (o *SystemChannelBroadcastOnlineRequest) SetMessageType(v string) {
	o.MessageType = v
}

// GetContent returns the Content field value
func (o *SystemChannelBroadcastOnlineRequest) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *SystemChannelBroadcastOnlineRequest) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *SystemChannelBroadcastOnlineRequest) SetContent(v string) {
	o.Content = v
}

// GetDisableUpdateLastMsg returns the DisableUpdateLastMsg field value if set, zero value otherwise.
func (o *SystemChannelBroadcastOnlineRequest) GetDisableUpdateLastMsg() bool {
	if o == nil || IsNil(o.DisableUpdateLastMsg) {
		var ret bool
		return ret
	}
	return *o.DisableUpdateLastMsg
}

// GetDisableUpdateLastMsgOk returns a tuple with the DisableUpdateLastMsg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemChannelBroadcastOnlineRequest) GetDisableUpdateLastMsgOk() (*bool, bool) {
	if o == nil || IsNil(o.DisableUpdateLastMsg) {
		return nil, false
	}
	return o.DisableUpdateLastMsg, true
}

// HasDisableUpdateLastMsg returns a boolean if a field has been set.
func (o *SystemChannelBroadcastOnlineRequest) HasDisableUpdateLastMsg() bool {
	if o != nil && !IsNil(o.DisableUpdateLastMsg) {
		return true
	}

	return false
}

// SetDisableUpdateLastMsg gets a reference to the given bool and assigns it to the DisableUpdateLastMsg field.
func (o *SystemChannelBroadcastOnlineRequest) SetDisableUpdateLastMsg(v bool) {
	o.DisableUpdateLastMsg = &v
}

func (o SystemChannelBroadcastOnlineRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemChannelBroadcastOnlineRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fromUserId"] = o.FromUserId
	toSerialize["messageType"] = o.MessageType
	toSerialize["content"] = o.Content
	if !IsNil(o.DisableUpdateLastMsg) {
		toSerialize["disableUpdateLastMsg"] = o.DisableUpdateLastMsg
	}
	return toSerialize, nil
}

func (o *SystemChannelBroadcastOnlineRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fromUserId",
		"messageType",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSystemChannelBroadcastOnlineRequest := _SystemChannelBroadcastOnlineRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSystemChannelBroadcastOnlineRequest)

	if err != nil {
		return err
	}

	*o = SystemChannelBroadcastOnlineRequest(varSystemChannelBroadcastOnlineRequest)

	return err
}

type NullableSystemChannelBroadcastOnlineRequest struct {
	value *SystemChannelBroadcastOnlineRequest
	isSet bool
}

func (v NullableSystemChannelBroadcastOnlineRequest) Get() *SystemChannelBroadcastOnlineRequest {
	return v.value
}

func (v *NullableSystemChannelBroadcastOnlineRequest) Set(val *SystemChannelBroadcastOnlineRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemChannelBroadcastOnlineRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemChannelBroadcastOnlineRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemChannelBroadcastOnlineRequest(val *SystemChannelBroadcastOnlineRequest) *NullableSystemChannelBroadcastOnlineRequest {
	return &NullableSystemChannelBroadcastOnlineRequest{value: val, isSet: true}
}

func (v NullableSystemChannelBroadcastOnlineRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemChannelBroadcastOnlineRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


