/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.0
Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GroupChannelMemberBatchGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupChannelMemberBatchGetResponse{}

// GroupChannelMemberBatchGetResponse struct for GroupChannelMemberBatchGetResponse
type GroupChannelMemberBatchGetResponse struct {
	Code int32 `json:"code"`
	Result *GroupChannelMemberBatchGetResponseResult `json:"result,omitempty"`
}

type _GroupChannelMemberBatchGetResponse GroupChannelMemberBatchGetResponse

// NewGroupChannelMemberBatchGetResponse instantiates a new GroupChannelMemberBatchGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupChannelMemberBatchGetResponse(code int32) *GroupChannelMemberBatchGetResponse {
	this := GroupChannelMemberBatchGetResponse{}
	this.Code = code
	return &this
}

// NewGroupChannelMemberBatchGetResponseWithDefaults instantiates a new GroupChannelMemberBatchGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupChannelMemberBatchGetResponseWithDefaults() *GroupChannelMemberBatchGetResponse {
	this := GroupChannelMemberBatchGetResponse{}
	return &this
}

// GetCode returns the Code field value
func (o *GroupChannelMemberBatchGetResponse) GetCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *GroupChannelMemberBatchGetResponse) GetCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *GroupChannelMemberBatchGetResponse) SetCode(v int32) {
	o.Code = v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *GroupChannelMemberBatchGetResponse) GetResult() GroupChannelMemberBatchGetResponseResult {
	if o == nil || IsNil(o.Result) {
		var ret GroupChannelMemberBatchGetResponseResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupChannelMemberBatchGetResponse) GetResultOk() (*GroupChannelMemberBatchGetResponseResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *GroupChannelMemberBatchGetResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given GroupChannelMemberBatchGetResponseResult and assigns it to the Result field.
func (o *GroupChannelMemberBatchGetResponse) SetResult(v GroupChannelMemberBatchGetResponseResult) {
	o.Result = &v
}

func (o GroupChannelMemberBatchGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupChannelMemberBatchGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

func (o *GroupChannelMemberBatchGetResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupChannelMemberBatchGetResponse := _GroupChannelMemberBatchGetResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupChannelMemberBatchGetResponse)

	if err != nil {
		return err
	}

	*o = GroupChannelMemberBatchGetResponse(varGroupChannelMemberBatchGetResponse)

	return err
}

type NullableGroupChannelMemberBatchGetResponse struct {
	value *GroupChannelMemberBatchGetResponse
	isSet bool
}

func (v NullableGroupChannelMemberBatchGetResponse) Get() *GroupChannelMemberBatchGetResponse {
	return v.value
}

func (v *NullableGroupChannelMemberBatchGetResponse) Set(val *GroupChannelMemberBatchGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupChannelMemberBatchGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupChannelMemberBatchGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupChannelMemberBatchGetResponse(val *GroupChannelMemberBatchGetResponse) *NullableGroupChannelMemberBatchGetResponse {
	return &NullableGroupChannelMemberBatchGetResponse{value: val, isSet: true}
}

func (v NullableGroupChannelMemberBatchGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupChannelMemberBatchGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


