/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.1
Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OpenChannelDestroyTypeSetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenChannelDestroyTypeSetRequest{}

// OpenChannelDestroyTypeSetRequest struct for OpenChannelDestroyTypeSetRequest
type OpenChannelDestroyTypeSetRequest struct {
	ChannelId string `json:"channelId"`
	DestroyType *int32 `json:"destroyType,omitempty"`
	TtlMinutes *int32 `json:"ttlMinutes,omitempty"`
}

type _OpenChannelDestroyTypeSetRequest OpenChannelDestroyTypeSetRequest

// NewOpenChannelDestroyTypeSetRequest instantiates a new OpenChannelDestroyTypeSetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenChannelDestroyTypeSetRequest(channelId string) *OpenChannelDestroyTypeSetRequest {
	this := OpenChannelDestroyTypeSetRequest{}
	this.ChannelId = channelId
	return &this
}

// NewOpenChannelDestroyTypeSetRequestWithDefaults instantiates a new OpenChannelDestroyTypeSetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenChannelDestroyTypeSetRequestWithDefaults() *OpenChannelDestroyTypeSetRequest {
	this := OpenChannelDestroyTypeSetRequest{}
	return &this
}

// GetChannelId returns the ChannelId field value
func (o *OpenChannelDestroyTypeSetRequest) GetChannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value
// and a boolean to check if the value has been set.
func (o *OpenChannelDestroyTypeSetRequest) GetChannelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelId, true
}

// SetChannelId sets field value
func (o *OpenChannelDestroyTypeSetRequest) SetChannelId(v string) {
	o.ChannelId = v
}

// GetDestroyType returns the DestroyType field value if set, zero value otherwise.
func (o *OpenChannelDestroyTypeSetRequest) GetDestroyType() int32 {
	if o == nil || IsNil(o.DestroyType) {
		var ret int32
		return ret
	}
	return *o.DestroyType
}

// GetDestroyTypeOk returns a tuple with the DestroyType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelDestroyTypeSetRequest) GetDestroyTypeOk() (*int32, bool) {
	if o == nil || IsNil(o.DestroyType) {
		return nil, false
	}
	return o.DestroyType, true
}

// HasDestroyType returns a boolean if a field has been set.
func (o *OpenChannelDestroyTypeSetRequest) HasDestroyType() bool {
	if o != nil && !IsNil(o.DestroyType) {
		return true
	}

	return false
}

// SetDestroyType gets a reference to the given int32 and assigns it to the DestroyType field.
func (o *OpenChannelDestroyTypeSetRequest) SetDestroyType(v int32) {
	o.DestroyType = &v
}

// GetTtlMinutes returns the TtlMinutes field value if set, zero value otherwise.
func (o *OpenChannelDestroyTypeSetRequest) GetTtlMinutes() int32 {
	if o == nil || IsNil(o.TtlMinutes) {
		var ret int32
		return ret
	}
	return *o.TtlMinutes
}

// GetTtlMinutesOk returns a tuple with the TtlMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelDestroyTypeSetRequest) GetTtlMinutesOk() (*int32, bool) {
	if o == nil || IsNil(o.TtlMinutes) {
		return nil, false
	}
	return o.TtlMinutes, true
}

// HasTtlMinutes returns a boolean if a field has been set.
func (o *OpenChannelDestroyTypeSetRequest) HasTtlMinutes() bool {
	if o != nil && !IsNil(o.TtlMinutes) {
		return true
	}

	return false
}

// SetTtlMinutes gets a reference to the given int32 and assigns it to the TtlMinutes field.
func (o *OpenChannelDestroyTypeSetRequest) SetTtlMinutes(v int32) {
	o.TtlMinutes = &v
}

func (o OpenChannelDestroyTypeSetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenChannelDestroyTypeSetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channelId"] = o.ChannelId
	if !IsNil(o.DestroyType) {
		toSerialize["destroyType"] = o.DestroyType
	}
	if !IsNil(o.TtlMinutes) {
		toSerialize["ttlMinutes"] = o.TtlMinutes
	}
	return toSerialize, nil
}

func (o *OpenChannelDestroyTypeSetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channelId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenChannelDestroyTypeSetRequest := _OpenChannelDestroyTypeSetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenChannelDestroyTypeSetRequest)

	if err != nil {
		return err
	}

	*o = OpenChannelDestroyTypeSetRequest(varOpenChannelDestroyTypeSetRequest)

	return err
}

type NullableOpenChannelDestroyTypeSetRequest struct {
	value *OpenChannelDestroyTypeSetRequest
	isSet bool
}

func (v NullableOpenChannelDestroyTypeSetRequest) Get() *OpenChannelDestroyTypeSetRequest {
	return v.value
}

func (v *NullableOpenChannelDestroyTypeSetRequest) Set(val *OpenChannelDestroyTypeSetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenChannelDestroyTypeSetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenChannelDestroyTypeSetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenChannelDestroyTypeSetRequest(val *OpenChannelDestroyTypeSetRequest) *NullableOpenChannelDestroyTypeSetRequest {
	return &NullableOpenChannelDestroyTypeSetRequest{value: val, isSet: true}
}

func (v NullableOpenChannelDestroyTypeSetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenChannelDestroyTypeSetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


