/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
)

// checks if the GroupChannelMutedMemberItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupChannelMutedMemberItem{}

// GroupChannelMutedMemberItem struct for GroupChannelMutedMemberItem
type GroupChannelMutedMemberItem struct {
	UserId *string `json:"userId,omitempty"`
	// Mute start time in `YYYY-MM-DD HH:MM:SS` format.
	MutedAt *string `json:"mutedAt,omitempty"`
	// Mute expiry time in `YYYY-MM-DD HH:MM:SS` format.
	MuteExpiresAt *string `json:"muteExpiresAt,omitempty"`
}

// NewGroupChannelMutedMemberItem instantiates a new GroupChannelMutedMemberItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupChannelMutedMemberItem() *GroupChannelMutedMemberItem {
	this := GroupChannelMutedMemberItem{}
	return &this
}

// NewGroupChannelMutedMemberItemWithDefaults instantiates a new GroupChannelMutedMemberItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupChannelMutedMemberItemWithDefaults() *GroupChannelMutedMemberItem {
	this := GroupChannelMutedMemberItem{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *GroupChannelMutedMemberItem) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupChannelMutedMemberItem) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *GroupChannelMutedMemberItem) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *GroupChannelMutedMemberItem) SetUserId(v string) {
	o.UserId = &v
}

// GetMutedAt returns the MutedAt field value if set, zero value otherwise.
func (o *GroupChannelMutedMemberItem) GetMutedAt() string {
	if o == nil || IsNil(o.MutedAt) {
		var ret string
		return ret
	}
	return *o.MutedAt
}

// GetMutedAtOk returns a tuple with the MutedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupChannelMutedMemberItem) GetMutedAtOk() (*string, bool) {
	if o == nil || IsNil(o.MutedAt) {
		return nil, false
	}
	return o.MutedAt, true
}

// HasMutedAt returns a boolean if a field has been set.
func (o *GroupChannelMutedMemberItem) HasMutedAt() bool {
	if o != nil && !IsNil(o.MutedAt) {
		return true
	}

	return false
}

// SetMutedAt gets a reference to the given string and assigns it to the MutedAt field.
func (o *GroupChannelMutedMemberItem) SetMutedAt(v string) {
	o.MutedAt = &v
}

// GetMuteExpiresAt returns the MuteExpiresAt field value if set, zero value otherwise.
func (o *GroupChannelMutedMemberItem) GetMuteExpiresAt() string {
	if o == nil || IsNil(o.MuteExpiresAt) {
		var ret string
		return ret
	}
	return *o.MuteExpiresAt
}

// GetMuteExpiresAtOk returns a tuple with the MuteExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupChannelMutedMemberItem) GetMuteExpiresAtOk() (*string, bool) {
	if o == nil || IsNil(o.MuteExpiresAt) {
		return nil, false
	}
	return o.MuteExpiresAt, true
}

// HasMuteExpiresAt returns a boolean if a field has been set.
func (o *GroupChannelMutedMemberItem) HasMuteExpiresAt() bool {
	if o != nil && !IsNil(o.MuteExpiresAt) {
		return true
	}

	return false
}

// SetMuteExpiresAt gets a reference to the given string and assigns it to the MuteExpiresAt field.
func (o *GroupChannelMutedMemberItem) SetMuteExpiresAt(v string) {
	o.MuteExpiresAt = &v
}

func (o GroupChannelMutedMemberItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupChannelMutedMemberItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	if !IsNil(o.MutedAt) {
		toSerialize["mutedAt"] = o.MutedAt
	}
	if !IsNil(o.MuteExpiresAt) {
		toSerialize["muteExpiresAt"] = o.MuteExpiresAt
	}
	return toSerialize, nil
}

type NullableGroupChannelMutedMemberItem struct {
	value *GroupChannelMutedMemberItem
	isSet bool
}

func (v NullableGroupChannelMutedMemberItem) Get() *GroupChannelMutedMemberItem {
	return v.value
}

func (v *NullableGroupChannelMutedMemberItem) Set(val *GroupChannelMutedMemberItem) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupChannelMutedMemberItem) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupChannelMutedMemberItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupChannelMutedMemberItem(val *GroupChannelMutedMemberItem) *NullableGroupChannelMutedMemberItem {
	return &NullableGroupChannelMutedMemberItem{value: val, isSet: true}
}

func (v NullableGroupChannelMutedMemberItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupChannelMutedMemberItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


