/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserConnectionStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserConnectionStatusResponse{}

// UserConnectionStatusResponse struct for UserConnectionStatusResponse
type UserConnectionStatusResponse struct {
	Code int32 `json:"code"`
	Result *UserConnectionStatusResponseResult `json:"result,omitempty"`
}

type _UserConnectionStatusResponse UserConnectionStatusResponse

// NewUserConnectionStatusResponse instantiates a new UserConnectionStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserConnectionStatusResponse(code int32) *UserConnectionStatusResponse {
	this := UserConnectionStatusResponse{}
	this.Code = code
	return &this
}

// NewUserConnectionStatusResponseWithDefaults instantiates a new UserConnectionStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserConnectionStatusResponseWithDefaults() *UserConnectionStatusResponse {
	this := UserConnectionStatusResponse{}
	return &this
}

// GetCode returns the Code field value
func (o *UserConnectionStatusResponse) GetCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *UserConnectionStatusResponse) GetCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *UserConnectionStatusResponse) SetCode(v int32) {
	o.Code = v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *UserConnectionStatusResponse) GetResult() UserConnectionStatusResponseResult {
	if o == nil || IsNil(o.Result) {
		var ret UserConnectionStatusResponseResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserConnectionStatusResponse) GetResultOk() (*UserConnectionStatusResponseResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *UserConnectionStatusResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given UserConnectionStatusResponseResult and assigns it to the Result field.
func (o *UserConnectionStatusResponse) SetResult(v UserConnectionStatusResponseResult) {
	o.Result = &v
}

func (o UserConnectionStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserConnectionStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

func (o *UserConnectionStatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserConnectionStatusResponse := _UserConnectionStatusResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserConnectionStatusResponse)

	if err != nil {
		return err
	}

	*o = UserConnectionStatusResponse(varUserConnectionStatusResponse)

	return err
}

type NullableUserConnectionStatusResponse struct {
	value *UserConnectionStatusResponse
	isSet bool
}

func (v NullableUserConnectionStatusResponse) Get() *UserConnectionStatusResponse {
	return v.value
}

func (v *NullableUserConnectionStatusResponse) Set(val *UserConnectionStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUserConnectionStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUserConnectionStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserConnectionStatusResponse(val *UserConnectionStatusResponse) *NullableUserConnectionStatusResponse {
	return &NullableUserConnectionStatusResponse{value: val, isSet: true}
}

func (v NullableUserConnectionStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserConnectionStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


