/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.1
Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GroupChannelMemberListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupChannelMemberListRequest{}

// GroupChannelMemberListRequest struct for GroupChannelMemberListRequest
type GroupChannelMemberListRequest struct {
	// Group channel ID.
	ChannelId string `json:"channelId"`
	// Member role filter. `0` all members, `1` regular members, `2` admins, `3` owner.
	MemberRole *int32 `json:"memberRole,omitempty"`
	// Pagination token returned by the previous request. Omit it for the first page.
	PageToken *string `json:"pageToken,omitempty"`
	// Number of members to return per page. The official default is 50 and the maximum is 100.
	PageSize *int32 `json:"pageSize,omitempty"`
	// Sort order by join time. `0` ascending and `1` descending.
	Order *int32 `json:"order,omitempty"`
}

type _GroupChannelMemberListRequest GroupChannelMemberListRequest

// NewGroupChannelMemberListRequest instantiates a new GroupChannelMemberListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupChannelMemberListRequest(channelId string) *GroupChannelMemberListRequest {
	this := GroupChannelMemberListRequest{}
	this.ChannelId = channelId
	return &this
}

// NewGroupChannelMemberListRequestWithDefaults instantiates a new GroupChannelMemberListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupChannelMemberListRequestWithDefaults() *GroupChannelMemberListRequest {
	this := GroupChannelMemberListRequest{}
	return &this
}

// GetChannelId returns the ChannelId field value
func (o *GroupChannelMemberListRequest) GetChannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value
// and a boolean to check if the value has been set.
func (o *GroupChannelMemberListRequest) GetChannelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelId, true
}

// SetChannelId sets field value
func (o *GroupChannelMemberListRequest) SetChannelId(v string) {
	o.ChannelId = v
}

// GetMemberRole returns the MemberRole field value if set, zero value otherwise.
func (o *GroupChannelMemberListRequest) GetMemberRole() int32 {
	if o == nil || IsNil(o.MemberRole) {
		var ret int32
		return ret
	}
	return *o.MemberRole
}

// GetMemberRoleOk returns a tuple with the MemberRole field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupChannelMemberListRequest) GetMemberRoleOk() (*int32, bool) {
	if o == nil || IsNil(o.MemberRole) {
		return nil, false
	}
	return o.MemberRole, true
}

// HasMemberRole returns a boolean if a field has been set.
func (o *GroupChannelMemberListRequest) HasMemberRole() bool {
	if o != nil && !IsNil(o.MemberRole) {
		return true
	}

	return false
}

// SetMemberRole gets a reference to the given int32 and assigns it to the MemberRole field.
func (o *GroupChannelMemberListRequest) SetMemberRole(v int32) {
	o.MemberRole = &v
}

// GetPageToken returns the PageToken field value if set, zero value otherwise.
func (o *GroupChannelMemberListRequest) GetPageToken() string {
	if o == nil || IsNil(o.PageToken) {
		var ret string
		return ret
	}
	return *o.PageToken
}

// GetPageTokenOk returns a tuple with the PageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupChannelMemberListRequest) GetPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.PageToken) {
		return nil, false
	}
	return o.PageToken, true
}

// HasPageToken returns a boolean if a field has been set.
func (o *GroupChannelMemberListRequest) HasPageToken() bool {
	if o != nil && !IsNil(o.PageToken) {
		return true
	}

	return false
}

// SetPageToken gets a reference to the given string and assigns it to the PageToken field.
func (o *GroupChannelMemberListRequest) SetPageToken(v string) {
	o.PageToken = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *GroupChannelMemberListRequest) GetPageSize() int32 {
	if o == nil || IsNil(o.PageSize) {
		var ret int32
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupChannelMemberListRequest) GetPageSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *GroupChannelMemberListRequest) HasPageSize() bool {
	if o != nil && !IsNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given int32 and assigns it to the PageSize field.
func (o *GroupChannelMemberListRequest) SetPageSize(v int32) {
	o.PageSize = &v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *GroupChannelMemberListRequest) GetOrder() int32 {
	if o == nil || IsNil(o.Order) {
		var ret int32
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupChannelMemberListRequest) GetOrderOk() (*int32, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *GroupChannelMemberListRequest) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given int32 and assigns it to the Order field.
func (o *GroupChannelMemberListRequest) SetOrder(v int32) {
	o.Order = &v
}

func (o GroupChannelMemberListRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupChannelMemberListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channelId"] = o.ChannelId
	if !IsNil(o.MemberRole) {
		toSerialize["memberRole"] = o.MemberRole
	}
	if !IsNil(o.PageToken) {
		toSerialize["pageToken"] = o.PageToken
	}
	if !IsNil(o.PageSize) {
		toSerialize["pageSize"] = o.PageSize
	}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	return toSerialize, nil
}

func (o *GroupChannelMemberListRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channelId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupChannelMemberListRequest := _GroupChannelMemberListRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupChannelMemberListRequest)

	if err != nil {
		return err
	}

	*o = GroupChannelMemberListRequest(varGroupChannelMemberListRequest)

	return err
}

type NullableGroupChannelMemberListRequest struct {
	value *GroupChannelMemberListRequest
	isSet bool
}

func (v NullableGroupChannelMemberListRequest) Get() *GroupChannelMemberListRequest {
	return v.value
}

func (v *NullableGroupChannelMemberListRequest) Set(val *GroupChannelMemberListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupChannelMemberListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupChannelMemberListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupChannelMemberListRequest(val *GroupChannelMemberListRequest) *NullableGroupChannelMemberListRequest {
	return &NullableGroupChannelMemberListRequest{value: val, isSet: true}
}

func (v NullableGroupChannelMemberListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupChannelMemberListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


