/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.1
Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CommunitySubchannelCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommunitySubchannelCreateRequest{}

// CommunitySubchannelCreateRequest struct for CommunitySubchannelCreateRequest
type CommunitySubchannelCreateRequest struct {
	ChannelId string `json:"channelId"`
	// Legacy `busChannel`.
	SubchannelId string `json:"subchannelId"`
	// Legacy `type`. `0` for public and `1` for private.
	ChannelVisibility *int32 `json:"channelVisibility,omitempty"`
}

type _CommunitySubchannelCreateRequest CommunitySubchannelCreateRequest

// NewCommunitySubchannelCreateRequest instantiates a new CommunitySubchannelCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommunitySubchannelCreateRequest(channelId string, subchannelId string) *CommunitySubchannelCreateRequest {
	this := CommunitySubchannelCreateRequest{}
	this.ChannelId = channelId
	this.SubchannelId = subchannelId
	return &this
}

// NewCommunitySubchannelCreateRequestWithDefaults instantiates a new CommunitySubchannelCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommunitySubchannelCreateRequestWithDefaults() *CommunitySubchannelCreateRequest {
	this := CommunitySubchannelCreateRequest{}
	return &this
}

// GetChannelId returns the ChannelId field value
func (o *CommunitySubchannelCreateRequest) GetChannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value
// and a boolean to check if the value has been set.
func (o *CommunitySubchannelCreateRequest) GetChannelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelId, true
}

// SetChannelId sets field value
func (o *CommunitySubchannelCreateRequest) SetChannelId(v string) {
	o.ChannelId = v
}

// GetSubchannelId returns the SubchannelId field value
func (o *CommunitySubchannelCreateRequest) GetSubchannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubchannelId
}

// GetSubchannelIdOk returns a tuple with the SubchannelId field value
// and a boolean to check if the value has been set.
func (o *CommunitySubchannelCreateRequest) GetSubchannelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubchannelId, true
}

// SetSubchannelId sets field value
func (o *CommunitySubchannelCreateRequest) SetSubchannelId(v string) {
	o.SubchannelId = v
}

// GetChannelVisibility returns the ChannelVisibility field value if set, zero value otherwise.
func (o *CommunitySubchannelCreateRequest) GetChannelVisibility() int32 {
	if o == nil || IsNil(o.ChannelVisibility) {
		var ret int32
		return ret
	}
	return *o.ChannelVisibility
}

// GetChannelVisibilityOk returns a tuple with the ChannelVisibility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunitySubchannelCreateRequest) GetChannelVisibilityOk() (*int32, bool) {
	if o == nil || IsNil(o.ChannelVisibility) {
		return nil, false
	}
	return o.ChannelVisibility, true
}

// HasChannelVisibility returns a boolean if a field has been set.
func (o *CommunitySubchannelCreateRequest) HasChannelVisibility() bool {
	if o != nil && !IsNil(o.ChannelVisibility) {
		return true
	}

	return false
}

// SetChannelVisibility gets a reference to the given int32 and assigns it to the ChannelVisibility field.
func (o *CommunitySubchannelCreateRequest) SetChannelVisibility(v int32) {
	o.ChannelVisibility = &v
}

func (o CommunitySubchannelCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommunitySubchannelCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channelId"] = o.ChannelId
	toSerialize["subchannelId"] = o.SubchannelId
	if !IsNil(o.ChannelVisibility) {
		toSerialize["channelVisibility"] = o.ChannelVisibility
	}
	return toSerialize, nil
}

func (o *CommunitySubchannelCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channelId",
		"subchannelId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommunitySubchannelCreateRequest := _CommunitySubchannelCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCommunitySubchannelCreateRequest)

	if err != nil {
		return err
	}

	*o = CommunitySubchannelCreateRequest(varCommunitySubchannelCreateRequest)

	return err
}

type NullableCommunitySubchannelCreateRequest struct {
	value *CommunitySubchannelCreateRequest
	isSet bool
}

func (v NullableCommunitySubchannelCreateRequest) Get() *CommunitySubchannelCreateRequest {
	return v.value
}

func (v *NullableCommunitySubchannelCreateRequest) Set(val *CommunitySubchannelCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCommunitySubchannelCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCommunitySubchannelCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommunitySubchannelCreateRequest(val *CommunitySubchannelCreateRequest) *NullableCommunitySubchannelCreateRequest {
	return &NullableCommunitySubchannelCreateRequest{value: val, isSet: true}
}

func (v NullableCommunitySubchannelCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommunitySubchannelCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


