/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChannelPinSetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelPinSetRequest{}

// ChannelPinSetRequest struct for ChannelPinSetRequest
type ChannelPinSetRequest struct {
	UserId string `json:"userId"`
	// Legacy `conversationType`. Current docs use numeric channel types such as `1`, `3`, and `6`.
	ChannelType int32 `json:"channelType"`
	// Legacy `targetId`.
	ChannelId string `json:"channelId"`
	// JSON field name used by the server. `true` pins the conversation and `false` cancels the pin.
	IsPin bool `json:"isPin"`
}

type _ChannelPinSetRequest ChannelPinSetRequest

// NewChannelPinSetRequest instantiates a new ChannelPinSetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelPinSetRequest(userId string, channelType int32, channelId string, isPin bool) *ChannelPinSetRequest {
	this := ChannelPinSetRequest{}
	this.UserId = userId
	this.ChannelType = channelType
	this.ChannelId = channelId
	this.IsPin = isPin
	return &this
}

// NewChannelPinSetRequestWithDefaults instantiates a new ChannelPinSetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelPinSetRequestWithDefaults() *ChannelPinSetRequest {
	this := ChannelPinSetRequest{}
	return &this
}

// GetUserId returns the UserId field value
func (o *ChannelPinSetRequest) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *ChannelPinSetRequest) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *ChannelPinSetRequest) SetUserId(v string) {
	o.UserId = v
}

// GetChannelType returns the ChannelType field value
func (o *ChannelPinSetRequest) GetChannelType() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChannelType
}

// GetChannelTypeOk returns a tuple with the ChannelType field value
// and a boolean to check if the value has been set.
func (o *ChannelPinSetRequest) GetChannelTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelType, true
}

// SetChannelType sets field value
func (o *ChannelPinSetRequest) SetChannelType(v int32) {
	o.ChannelType = v
}

// GetChannelId returns the ChannelId field value
func (o *ChannelPinSetRequest) GetChannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value
// and a boolean to check if the value has been set.
func (o *ChannelPinSetRequest) GetChannelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelId, true
}

// SetChannelId sets field value
func (o *ChannelPinSetRequest) SetChannelId(v string) {
	o.ChannelId = v
}

// GetIsPin returns the IsPin field value
func (o *ChannelPinSetRequest) GetIsPin() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsPin
}

// GetIsPinOk returns a tuple with the IsPin field value
// and a boolean to check if the value has been set.
func (o *ChannelPinSetRequest) GetIsPinOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsPin, true
}

// SetIsPin sets field value
func (o *ChannelPinSetRequest) SetIsPin(v bool) {
	o.IsPin = v
}

func (o ChannelPinSetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelPinSetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["userId"] = o.UserId
	toSerialize["channelType"] = o.ChannelType
	toSerialize["channelId"] = o.ChannelId
	toSerialize["isPin"] = o.IsPin
	return toSerialize, nil
}

func (o *ChannelPinSetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"userId",
		"channelType",
		"channelId",
		"isPin",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChannelPinSetRequest := _ChannelPinSetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChannelPinSetRequest)

	if err != nil {
		return err
	}

	*o = ChannelPinSetRequest(varChannelPinSetRequest)

	return err
}

type NullableChannelPinSetRequest struct {
	value *ChannelPinSetRequest
	isSet bool
}

func (v NullableChannelPinSetRequest) Get() *ChannelPinSetRequest {
	return v.value
}

func (v *NullableChannelPinSetRequest) Set(val *ChannelPinSetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelPinSetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelPinSetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelPinSetRequest(val *ChannelPinSetRequest) *NullableChannelPinSetRequest {
	return &NullableChannelPinSetRequest{value: val, isSet: true}
}

func (v NullableChannelPinSetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelPinSetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


