/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SystemChannelPushMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemChannelPushMessage{}

// SystemChannelPushMessage struct for SystemChannelPushMessage
type SystemChannelPushMessage struct {
	Content string `json:"content"`
	MessageType string `json:"messageType"`
	DisableUpdateLastMsg *bool `json:"disableUpdateLastMsg,omitempty"`
}

type _SystemChannelPushMessage SystemChannelPushMessage

// NewSystemChannelPushMessage instantiates a new SystemChannelPushMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemChannelPushMessage(content string, messageType string) *SystemChannelPushMessage {
	this := SystemChannelPushMessage{}
	this.Content = content
	this.MessageType = messageType
	return &this
}

// NewSystemChannelPushMessageWithDefaults instantiates a new SystemChannelPushMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemChannelPushMessageWithDefaults() *SystemChannelPushMessage {
	this := SystemChannelPushMessage{}
	return &this
}

// GetContent returns the Content field value
func (o *SystemChannelPushMessage) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *SystemChannelPushMessage) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *SystemChannelPushMessage) SetContent(v string) {
	o.Content = v
}

// GetMessageType returns the MessageType field value
func (o *SystemChannelPushMessage) GetMessageType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MessageType
}

// GetMessageTypeOk returns a tuple with the MessageType field value
// and a boolean to check if the value has been set.
func (o *SystemChannelPushMessage) GetMessageTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MessageType, true
}

// SetMessageType sets field value
func (o *SystemChannelPushMessage) SetMessageType(v string) {
	o.MessageType = v
}

// GetDisableUpdateLastMsg returns the DisableUpdateLastMsg field value if set, zero value otherwise.
func (o *SystemChannelPushMessage) GetDisableUpdateLastMsg() bool {
	if o == nil || IsNil(o.DisableUpdateLastMsg) {
		var ret bool
		return ret
	}
	return *o.DisableUpdateLastMsg
}

// GetDisableUpdateLastMsgOk returns a tuple with the DisableUpdateLastMsg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemChannelPushMessage) GetDisableUpdateLastMsgOk() (*bool, bool) {
	if o == nil || IsNil(o.DisableUpdateLastMsg) {
		return nil, false
	}
	return o.DisableUpdateLastMsg, true
}

// HasDisableUpdateLastMsg returns a boolean if a field has been set.
func (o *SystemChannelPushMessage) HasDisableUpdateLastMsg() bool {
	if o != nil && !IsNil(o.DisableUpdateLastMsg) {
		return true
	}

	return false
}

// SetDisableUpdateLastMsg gets a reference to the given bool and assigns it to the DisableUpdateLastMsg field.
func (o *SystemChannelPushMessage) SetDisableUpdateLastMsg(v bool) {
	o.DisableUpdateLastMsg = &v
}

func (o SystemChannelPushMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemChannelPushMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["content"] = o.Content
	toSerialize["messageType"] = o.MessageType
	if !IsNil(o.DisableUpdateLastMsg) {
		toSerialize["disableUpdateLastMsg"] = o.DisableUpdateLastMsg
	}
	return toSerialize, nil
}

func (o *SystemChannelPushMessage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"content",
		"messageType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSystemChannelPushMessage := _SystemChannelPushMessage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSystemChannelPushMessage)

	if err != nil {
		return err
	}

	*o = SystemChannelPushMessage(varSystemChannelPushMessage)

	return err
}

type NullableSystemChannelPushMessage struct {
	value *SystemChannelPushMessage
	isSet bool
}

func (v NullableSystemChannelPushMessage) Get() *SystemChannelPushMessage {
	return v.value
}

func (v *NullableSystemChannelPushMessage) Set(val *SystemChannelPushMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemChannelPushMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemChannelPushMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemChannelPushMessage(val *SystemChannelPushMessage) *NullableSystemChannelPushMessage {
	return &NullableSystemChannelPushMessage{value: val, isSet: true}
}

func (v NullableSystemChannelPushMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemChannelPushMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


