/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FriendListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FriendListResponse{}

// FriendListResponse struct for FriendListResponse
type FriendListResponse struct {
	Code int32 `json:"code"`
	Result *FriendListResponseResult `json:"result,omitempty"`
}

type _FriendListResponse FriendListResponse

// NewFriendListResponse instantiates a new FriendListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFriendListResponse(code int32) *FriendListResponse {
	this := FriendListResponse{}
	this.Code = code
	return &this
}

// NewFriendListResponseWithDefaults instantiates a new FriendListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFriendListResponseWithDefaults() *FriendListResponse {
	this := FriendListResponse{}
	return &this
}

// GetCode returns the Code field value
func (o *FriendListResponse) GetCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *FriendListResponse) GetCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *FriendListResponse) SetCode(v int32) {
	o.Code = v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *FriendListResponse) GetResult() FriendListResponseResult {
	if o == nil || IsNil(o.Result) {
		var ret FriendListResponseResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FriendListResponse) GetResultOk() (*FriendListResponseResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *FriendListResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given FriendListResponseResult and assigns it to the Result field.
func (o *FriendListResponse) SetResult(v FriendListResponseResult) {
	o.Result = &v
}

func (o FriendListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FriendListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

func (o *FriendListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFriendListResponse := _FriendListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFriendListResponse)

	if err != nil {
		return err
	}

	*o = FriendListResponse(varFriendListResponse)

	return err
}

type NullableFriendListResponse struct {
	value *FriendListResponse
	isSet bool
}

func (v NullableFriendListResponse) Get() *FriendListResponse {
	return v.value
}

func (v *NullableFriendListResponse) Set(val *FriendListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFriendListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFriendListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFriendListResponse(val *FriendListResponse) *NullableFriendListResponse {
	return &NullableFriendListResponse{value: val, isSet: true}
}

func (v NullableFriendListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFriendListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


