/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
)

// checks if the GroupChannelProfileItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupChannelProfileItem{}

// GroupChannelProfileItem struct for GroupChannelProfileItem
type GroupChannelProfileItem struct {
	// Group channel ID.
	ChannelId *string `json:"channelId,omitempty"`
	// Group name.
	Name *string `json:"name,omitempty"`
	// Group basic profile JSON object, such as introduction, announcement, and portrait URL.
	GroupProfile map[string]interface{} `json:"groupProfile,omitempty"`
	// Extended group profile JSON object. Keys are typically custom fields prefixed with `ext_`.
	GroupExtProfile map[string]interface{} `json:"groupExtProfile,omitempty"`
	// Group permission settings JSON object, including join, invite, and profile-management permissions.
	Permissions map[string]interface{} `json:"permissions,omitempty"`
	// User ID of the current group owner.
	Owner *string `json:"owner,omitempty"`
	// Timestamp when the group was created.
	CreatedAt *int64 `json:"createdAt,omitempty"`
	// Current number of group members.
	MemberCount *int32 `json:"memberCount,omitempty"`
}

// NewGroupChannelProfileItem instantiates a new GroupChannelProfileItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupChannelProfileItem() *GroupChannelProfileItem {
	this := GroupChannelProfileItem{}
	return &this
}

// NewGroupChannelProfileItemWithDefaults instantiates a new GroupChannelProfileItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupChannelProfileItemWithDefaults() *GroupChannelProfileItem {
	this := GroupChannelProfileItem{}
	return &this
}

// GetChannelId returns the ChannelId field value if set, zero value otherwise.
func (o *GroupChannelProfileItem) GetChannelId() string {
	if o == nil || IsNil(o.ChannelId) {
		var ret string
		return ret
	}
	return *o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupChannelProfileItem) GetChannelIdOk() (*string, bool) {
	if o == nil || IsNil(o.ChannelId) {
		return nil, false
	}
	return o.ChannelId, true
}

// HasChannelId returns a boolean if a field has been set.
func (o *GroupChannelProfileItem) HasChannelId() bool {
	if o != nil && !IsNil(o.ChannelId) {
		return true
	}

	return false
}

// SetChannelId gets a reference to the given string and assigns it to the ChannelId field.
func (o *GroupChannelProfileItem) SetChannelId(v string) {
	o.ChannelId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GroupChannelProfileItem) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupChannelProfileItem) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GroupChannelProfileItem) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GroupChannelProfileItem) SetName(v string) {
	o.Name = &v
}

// GetGroupProfile returns the GroupProfile field value if set, zero value otherwise.
func (o *GroupChannelProfileItem) GetGroupProfile() map[string]interface{} {
	if o == nil || IsNil(o.GroupProfile) {
		var ret map[string]interface{}
		return ret
	}
	return o.GroupProfile
}

// GetGroupProfileOk returns a tuple with the GroupProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupChannelProfileItem) GetGroupProfileOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.GroupProfile) {
		return map[string]interface{}{}, false
	}
	return o.GroupProfile, true
}

// HasGroupProfile returns a boolean if a field has been set.
func (o *GroupChannelProfileItem) HasGroupProfile() bool {
	if o != nil && !IsNil(o.GroupProfile) {
		return true
	}

	return false
}

// SetGroupProfile gets a reference to the given map[string]interface{} and assigns it to the GroupProfile field.
func (o *GroupChannelProfileItem) SetGroupProfile(v map[string]interface{}) {
	o.GroupProfile = v
}

// GetGroupExtProfile returns the GroupExtProfile field value if set, zero value otherwise.
func (o *GroupChannelProfileItem) GetGroupExtProfile() map[string]interface{} {
	if o == nil || IsNil(o.GroupExtProfile) {
		var ret map[string]interface{}
		return ret
	}
	return o.GroupExtProfile
}

// GetGroupExtProfileOk returns a tuple with the GroupExtProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupChannelProfileItem) GetGroupExtProfileOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.GroupExtProfile) {
		return map[string]interface{}{}, false
	}
	return o.GroupExtProfile, true
}

// HasGroupExtProfile returns a boolean if a field has been set.
func (o *GroupChannelProfileItem) HasGroupExtProfile() bool {
	if o != nil && !IsNil(o.GroupExtProfile) {
		return true
	}

	return false
}

// SetGroupExtProfile gets a reference to the given map[string]interface{} and assigns it to the GroupExtProfile field.
func (o *GroupChannelProfileItem) SetGroupExtProfile(v map[string]interface{}) {
	o.GroupExtProfile = v
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *GroupChannelProfileItem) GetPermissions() map[string]interface{} {
	if o == nil || IsNil(o.Permissions) {
		var ret map[string]interface{}
		return ret
	}
	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupChannelProfileItem) GetPermissionsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Permissions) {
		return map[string]interface{}{}, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *GroupChannelProfileItem) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given map[string]interface{} and assigns it to the Permissions field.
func (o *GroupChannelProfileItem) SetPermissions(v map[string]interface{}) {
	o.Permissions = v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *GroupChannelProfileItem) GetOwner() string {
	if o == nil || IsNil(o.Owner) {
		var ret string
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupChannelProfileItem) GetOwnerOk() (*string, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *GroupChannelProfileItem) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given string and assigns it to the Owner field.
func (o *GroupChannelProfileItem) SetOwner(v string) {
	o.Owner = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GroupChannelProfileItem) GetCreatedAt() int64 {
	if o == nil || IsNil(o.CreatedAt) {
		var ret int64
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupChannelProfileItem) GetCreatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GroupChannelProfileItem) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int64 and assigns it to the CreatedAt field.
func (o *GroupChannelProfileItem) SetCreatedAt(v int64) {
	o.CreatedAt = &v
}

// GetMemberCount returns the MemberCount field value if set, zero value otherwise.
func (o *GroupChannelProfileItem) GetMemberCount() int32 {
	if o == nil || IsNil(o.MemberCount) {
		var ret int32
		return ret
	}
	return *o.MemberCount
}

// GetMemberCountOk returns a tuple with the MemberCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupChannelProfileItem) GetMemberCountOk() (*int32, bool) {
	if o == nil || IsNil(o.MemberCount) {
		return nil, false
	}
	return o.MemberCount, true
}

// HasMemberCount returns a boolean if a field has been set.
func (o *GroupChannelProfileItem) HasMemberCount() bool {
	if o != nil && !IsNil(o.MemberCount) {
		return true
	}

	return false
}

// SetMemberCount gets a reference to the given int32 and assigns it to the MemberCount field.
func (o *GroupChannelProfileItem) SetMemberCount(v int32) {
	o.MemberCount = &v
}

func (o GroupChannelProfileItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupChannelProfileItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ChannelId) {
		toSerialize["channelId"] = o.ChannelId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.GroupProfile) {
		toSerialize["groupProfile"] = o.GroupProfile
	}
	if !IsNil(o.GroupExtProfile) {
		toSerialize["groupExtProfile"] = o.GroupExtProfile
	}
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.MemberCount) {
		toSerialize["memberCount"] = o.MemberCount
	}
	return toSerialize, nil
}

type NullableGroupChannelProfileItem struct {
	value *GroupChannelProfileItem
	isSet bool
}

func (v NullableGroupChannelProfileItem) Get() *GroupChannelProfileItem {
	return v.value
}

func (v *NullableGroupChannelProfileItem) Set(val *GroupChannelProfileItem) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupChannelProfileItem) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupChannelProfileItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupChannelProfileItem(val *GroupChannelProfileItem) *NullableGroupChannelProfileItem {
	return &NullableGroupChannelProfileItem{value: val, isSet: true}
}

func (v NullableGroupChannelProfileItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupChannelProfileItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


