/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserChannelTagListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserChannelTagListRequest{}

// UserChannelTagListRequest struct for UserChannelTagListRequest
type UserChannelTagListRequest struct {
	UserId string `json:"userId"`
}

type _UserChannelTagListRequest UserChannelTagListRequest

// NewUserChannelTagListRequest instantiates a new UserChannelTagListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserChannelTagListRequest(userId string) *UserChannelTagListRequest {
	this := UserChannelTagListRequest{}
	this.UserId = userId
	return &this
}

// NewUserChannelTagListRequestWithDefaults instantiates a new UserChannelTagListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserChannelTagListRequestWithDefaults() *UserChannelTagListRequest {
	this := UserChannelTagListRequest{}
	return &this
}

// GetUserId returns the UserId field value
func (o *UserChannelTagListRequest) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *UserChannelTagListRequest) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *UserChannelTagListRequest) SetUserId(v string) {
	o.UserId = v
}

func (o UserChannelTagListRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserChannelTagListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["userId"] = o.UserId
	return toSerialize, nil
}

func (o *UserChannelTagListRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"userId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserChannelTagListRequest := _UserChannelTagListRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserChannelTagListRequest)

	if err != nil {
		return err
	}

	*o = UserChannelTagListRequest(varUserChannelTagListRequest)

	return err
}

type NullableUserChannelTagListRequest struct {
	value *UserChannelTagListRequest
	isSet bool
}

func (v NullableUserChannelTagListRequest) Get() *UserChannelTagListRequest {
	return v.value
}

func (v *NullableUserChannelTagListRequest) Set(val *UserChannelTagListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserChannelTagListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserChannelTagListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserChannelTagListRequest(val *UserChannelTagListRequest) *NullableUserChannelTagListRequest {
	return &NullableUserChannelTagListRequest{value: val, isSet: true}
}

func (v NullableUserChannelTagListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserChannelTagListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


