/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
)

// checks if the CommunityChannelAllowedSenderItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommunityChannelAllowedSenderItem{}

// CommunityChannelAllowedSenderItem struct for CommunityChannelAllowedSenderItem
type CommunityChannelAllowedSenderItem struct {
	UserId *string `json:"userId,omitempty"`
}

// NewCommunityChannelAllowedSenderItem instantiates a new CommunityChannelAllowedSenderItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommunityChannelAllowedSenderItem() *CommunityChannelAllowedSenderItem {
	this := CommunityChannelAllowedSenderItem{}
	return &this
}

// NewCommunityChannelAllowedSenderItemWithDefaults instantiates a new CommunityChannelAllowedSenderItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommunityChannelAllowedSenderItemWithDefaults() *CommunityChannelAllowedSenderItem {
	this := CommunityChannelAllowedSenderItem{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *CommunityChannelAllowedSenderItem) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityChannelAllowedSenderItem) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *CommunityChannelAllowedSenderItem) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *CommunityChannelAllowedSenderItem) SetUserId(v string) {
	o.UserId = &v
}

func (o CommunityChannelAllowedSenderItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommunityChannelAllowedSenderItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	return toSerialize, nil
}

type NullableCommunityChannelAllowedSenderItem struct {
	value *CommunityChannelAllowedSenderItem
	isSet bool
}

func (v NullableCommunityChannelAllowedSenderItem) Get() *CommunityChannelAllowedSenderItem {
	return v.value
}

func (v *NullableCommunityChannelAllowedSenderItem) Set(val *CommunityChannelAllowedSenderItem) {
	v.value = val
	v.isSet = true
}

func (v NullableCommunityChannelAllowedSenderItem) IsSet() bool {
	return v.isSet
}

func (v *NullableCommunityChannelAllowedSenderItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommunityChannelAllowedSenderItem(val *CommunityChannelAllowedSenderItem) *NullableCommunityChannelAllowedSenderItem {
	return &NullableCommunityChannelAllowedSenderItem{value: val, isSet: true}
}

func (v NullableCommunityChannelAllowedSenderItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommunityChannelAllowedSenderItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


