/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OpenChannelMetadataBatchGetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenChannelMetadataBatchGetRequest{}

// OpenChannelMetadataBatchGetRequest struct for OpenChannelMetadataBatchGetRequest
type OpenChannelMetadataBatchGetRequest struct {
	ChannelId string `json:"channelId"`
	// Metadata keys to fetch. When omitted, the service returns metadata according to its default rule.
	MetadataKeys []string `json:"metadataKeys,omitempty"`
}

type _OpenChannelMetadataBatchGetRequest OpenChannelMetadataBatchGetRequest

// NewOpenChannelMetadataBatchGetRequest instantiates a new OpenChannelMetadataBatchGetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenChannelMetadataBatchGetRequest(channelId string) *OpenChannelMetadataBatchGetRequest {
	this := OpenChannelMetadataBatchGetRequest{}
	this.ChannelId = channelId
	return &this
}

// NewOpenChannelMetadataBatchGetRequestWithDefaults instantiates a new OpenChannelMetadataBatchGetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenChannelMetadataBatchGetRequestWithDefaults() *OpenChannelMetadataBatchGetRequest {
	this := OpenChannelMetadataBatchGetRequest{}
	return &this
}

// GetChannelId returns the ChannelId field value
func (o *OpenChannelMetadataBatchGetRequest) GetChannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value
// and a boolean to check if the value has been set.
func (o *OpenChannelMetadataBatchGetRequest) GetChannelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelId, true
}

// SetChannelId sets field value
func (o *OpenChannelMetadataBatchGetRequest) SetChannelId(v string) {
	o.ChannelId = v
}

// GetMetadataKeys returns the MetadataKeys field value if set, zero value otherwise.
func (o *OpenChannelMetadataBatchGetRequest) GetMetadataKeys() []string {
	if o == nil || IsNil(o.MetadataKeys) {
		var ret []string
		return ret
	}
	return o.MetadataKeys
}

// GetMetadataKeysOk returns a tuple with the MetadataKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelMetadataBatchGetRequest) GetMetadataKeysOk() ([]string, bool) {
	if o == nil || IsNil(o.MetadataKeys) {
		return nil, false
	}
	return o.MetadataKeys, true
}

// HasMetadataKeys returns a boolean if a field has been set.
func (o *OpenChannelMetadataBatchGetRequest) HasMetadataKeys() bool {
	if o != nil && !IsNil(o.MetadataKeys) {
		return true
	}

	return false
}

// SetMetadataKeys gets a reference to the given []string and assigns it to the MetadataKeys field.
func (o *OpenChannelMetadataBatchGetRequest) SetMetadataKeys(v []string) {
	o.MetadataKeys = v
}

func (o OpenChannelMetadataBatchGetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenChannelMetadataBatchGetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channelId"] = o.ChannelId
	if !IsNil(o.MetadataKeys) {
		toSerialize["metadataKeys"] = o.MetadataKeys
	}
	return toSerialize, nil
}

func (o *OpenChannelMetadataBatchGetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channelId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenChannelMetadataBatchGetRequest := _OpenChannelMetadataBatchGetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenChannelMetadataBatchGetRequest)

	if err != nil {
		return err
	}

	*o = OpenChannelMetadataBatchGetRequest(varOpenChannelMetadataBatchGetRequest)

	return err
}

type NullableOpenChannelMetadataBatchGetRequest struct {
	value *OpenChannelMetadataBatchGetRequest
	isSet bool
}

func (v NullableOpenChannelMetadataBatchGetRequest) Get() *OpenChannelMetadataBatchGetRequest {
	return v.value
}

func (v *NullableOpenChannelMetadataBatchGetRequest) Set(val *OpenChannelMetadataBatchGetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenChannelMetadataBatchGetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenChannelMetadataBatchGetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenChannelMetadataBatchGetRequest(val *OpenChannelMetadataBatchGetRequest) *NullableOpenChannelMetadataBatchGetRequest {
	return &NullableOpenChannelMetadataBatchGetRequest{value: val, isSet: true}
}

func (v NullableOpenChannelMetadataBatchGetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenChannelMetadataBatchGetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


