/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.0
Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserBanRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserBanRequest{}

// UserBanRequest struct for UserBanRequest
type UserBanRequest struct {
	UserIds []string `json:"userIds"`
	DurationMinutes int32 `json:"durationMinutes"`
}

type _UserBanRequest UserBanRequest

// NewUserBanRequest instantiates a new UserBanRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserBanRequest(userIds []string, durationMinutes int32) *UserBanRequest {
	this := UserBanRequest{}
	this.UserIds = userIds
	this.DurationMinutes = durationMinutes
	return &this
}

// NewUserBanRequestWithDefaults instantiates a new UserBanRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserBanRequestWithDefaults() *UserBanRequest {
	this := UserBanRequest{}
	return &this
}

// GetUserIds returns the UserIds field value
func (o *UserBanRequest) GetUserIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.UserIds
}

// GetUserIdsOk returns a tuple with the UserIds field value
// and a boolean to check if the value has been set.
func (o *UserBanRequest) GetUserIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserIds, true
}

// SetUserIds sets field value
func (o *UserBanRequest) SetUserIds(v []string) {
	o.UserIds = v
}

// GetDurationMinutes returns the DurationMinutes field value
func (o *UserBanRequest) GetDurationMinutes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DurationMinutes
}

// GetDurationMinutesOk returns a tuple with the DurationMinutes field value
// and a boolean to check if the value has been set.
func (o *UserBanRequest) GetDurationMinutesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DurationMinutes, true
}

// SetDurationMinutes sets field value
func (o *UserBanRequest) SetDurationMinutes(v int32) {
	o.DurationMinutes = v
}

func (o UserBanRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserBanRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["userIds"] = o.UserIds
	toSerialize["durationMinutes"] = o.DurationMinutes
	return toSerialize, nil
}

func (o *UserBanRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"userIds",
		"durationMinutes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserBanRequest := _UserBanRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserBanRequest)

	if err != nil {
		return err
	}

	*o = UserBanRequest(varUserBanRequest)

	return err
}

type NullableUserBanRequest struct {
	value *UserBanRequest
	isSet bool
}

func (v NullableUserBanRequest) Get() *UserBanRequest {
	return v.value
}

func (v *NullableUserBanRequest) Set(val *UserBanRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserBanRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserBanRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserBanRequest(val *UserBanRequest) *NullableUserBanRequest {
	return &NullableUserBanRequest{value: val, isSet: true}
}

func (v NullableUserBanRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserBanRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


