/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.0
Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
)

// checks if the OpenChannelParticipantItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenChannelParticipantItem{}

// OpenChannelParticipantItem struct for OpenChannelParticipantItem
type OpenChannelParticipantItem struct {
	ParticipantId *string `json:"participantId,omitempty"`
	// Participant join time in `YYYY-MM-DD HH:MM:SS` format.
	CreatedAt *string `json:"createdAt,omitempty"`
}

// NewOpenChannelParticipantItem instantiates a new OpenChannelParticipantItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenChannelParticipantItem() *OpenChannelParticipantItem {
	this := OpenChannelParticipantItem{}
	return &this
}

// NewOpenChannelParticipantItemWithDefaults instantiates a new OpenChannelParticipantItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenChannelParticipantItemWithDefaults() *OpenChannelParticipantItem {
	this := OpenChannelParticipantItem{}
	return &this
}

// GetParticipantId returns the ParticipantId field value if set, zero value otherwise.
func (o *OpenChannelParticipantItem) GetParticipantId() string {
	if o == nil || IsNil(o.ParticipantId) {
		var ret string
		return ret
	}
	return *o.ParticipantId
}

// GetParticipantIdOk returns a tuple with the ParticipantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelParticipantItem) GetParticipantIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParticipantId) {
		return nil, false
	}
	return o.ParticipantId, true
}

// HasParticipantId returns a boolean if a field has been set.
func (o *OpenChannelParticipantItem) HasParticipantId() bool {
	if o != nil && !IsNil(o.ParticipantId) {
		return true
	}

	return false
}

// SetParticipantId gets a reference to the given string and assigns it to the ParticipantId field.
func (o *OpenChannelParticipantItem) SetParticipantId(v string) {
	o.ParticipantId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *OpenChannelParticipantItem) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelParticipantItem) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *OpenChannelParticipantItem) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *OpenChannelParticipantItem) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

func (o OpenChannelParticipantItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenChannelParticipantItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ParticipantId) {
		toSerialize["participantId"] = o.ParticipantId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableOpenChannelParticipantItem struct {
	value *OpenChannelParticipantItem
	isSet bool
}

func (v NullableOpenChannelParticipantItem) Get() *OpenChannelParticipantItem {
	return v.value
}

func (v *NullableOpenChannelParticipantItem) Set(val *OpenChannelParticipantItem) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenChannelParticipantItem) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenChannelParticipantItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenChannelParticipantItem(val *OpenChannelParticipantItem) *NullableOpenChannelParticipantItem {
	return &NullableOpenChannelParticipantItem{value: val, isSet: true}
}

func (v NullableOpenChannelParticipantItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenChannelParticipantItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


