/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.1
Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OpenChannelPriorityMessageTypeListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenChannelPriorityMessageTypeListRequest{}

// OpenChannelPriorityMessageTypeListRequest struct for OpenChannelPriorityMessageTypeListRequest
type OpenChannelPriorityMessageTypeListRequest struct {
	MessageTypes []string `json:"messageTypes"`
}

type _OpenChannelPriorityMessageTypeListRequest OpenChannelPriorityMessageTypeListRequest

// NewOpenChannelPriorityMessageTypeListRequest instantiates a new OpenChannelPriorityMessageTypeListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenChannelPriorityMessageTypeListRequest(messageTypes []string) *OpenChannelPriorityMessageTypeListRequest {
	this := OpenChannelPriorityMessageTypeListRequest{}
	this.MessageTypes = messageTypes
	return &this
}

// NewOpenChannelPriorityMessageTypeListRequestWithDefaults instantiates a new OpenChannelPriorityMessageTypeListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenChannelPriorityMessageTypeListRequestWithDefaults() *OpenChannelPriorityMessageTypeListRequest {
	this := OpenChannelPriorityMessageTypeListRequest{}
	return &this
}

// GetMessageTypes returns the MessageTypes field value
func (o *OpenChannelPriorityMessageTypeListRequest) GetMessageTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.MessageTypes
}

// GetMessageTypesOk returns a tuple with the MessageTypes field value
// and a boolean to check if the value has been set.
func (o *OpenChannelPriorityMessageTypeListRequest) GetMessageTypesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MessageTypes, true
}

// SetMessageTypes sets field value
func (o *OpenChannelPriorityMessageTypeListRequest) SetMessageTypes(v []string) {
	o.MessageTypes = v
}

func (o OpenChannelPriorityMessageTypeListRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenChannelPriorityMessageTypeListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["messageTypes"] = o.MessageTypes
	return toSerialize, nil
}

func (o *OpenChannelPriorityMessageTypeListRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"messageTypes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenChannelPriorityMessageTypeListRequest := _OpenChannelPriorityMessageTypeListRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenChannelPriorityMessageTypeListRequest)

	if err != nil {
		return err
	}

	*o = OpenChannelPriorityMessageTypeListRequest(varOpenChannelPriorityMessageTypeListRequest)

	return err
}

type NullableOpenChannelPriorityMessageTypeListRequest struct {
	value *OpenChannelPriorityMessageTypeListRequest
	isSet bool
}

func (v NullableOpenChannelPriorityMessageTypeListRequest) Get() *OpenChannelPriorityMessageTypeListRequest {
	return v.value
}

func (v *NullableOpenChannelPriorityMessageTypeListRequest) Set(val *OpenChannelPriorityMessageTypeListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenChannelPriorityMessageTypeListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenChannelPriorityMessageTypeListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenChannelPriorityMessageTypeListRequest(val *OpenChannelPriorityMessageTypeListRequest) *NullableOpenChannelPriorityMessageTypeListRequest {
	return &NullableOpenChannelPriorityMessageTypeListRequest{value: val, isSet: true}
}

func (v NullableOpenChannelPriorityMessageTypeListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenChannelPriorityMessageTypeListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


