/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.0
Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OpenChannelCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenChannelCreateRequest{}

// OpenChannelCreateRequest struct for OpenChannelCreateRequest
type OpenChannelCreateRequest struct {
	// Legacy `chatroomId`.
	ChannelId string `json:"channelId"`
	// '0' for inactive-time destroy and '1' for fixed-time destroy.
	DestroyType *int32 `json:"destroyType,omitempty"`
	// Legacy `destroyTime`. Valid range is 60 to 10080 minutes according to the PDF.
	TtlMinutes *int32 `json:"ttlMinutes,omitempty"`
	// Whether whole-channel freeze is enabled when the chatroom is created.
	ShouldFreeze *bool `json:"shouldFreeze,omitempty"`
	// Allowed senders list applied when the chatroom is frozen.
	AllowedSendersList []string `json:"allowedSendersList,omitempty"`
	// Legacy `entryOwnerId`.
	MetadataOwnerId *string `json:"metadataOwnerId,omitempty"`
	// Legacy `entryInfo`. Open-channel metadata key/value pairs.
	Metadata *map[string]string `json:"metadata,omitempty"`
}

type _OpenChannelCreateRequest OpenChannelCreateRequest

// NewOpenChannelCreateRequest instantiates a new OpenChannelCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenChannelCreateRequest(channelId string) *OpenChannelCreateRequest {
	this := OpenChannelCreateRequest{}
	this.ChannelId = channelId
	return &this
}

// NewOpenChannelCreateRequestWithDefaults instantiates a new OpenChannelCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenChannelCreateRequestWithDefaults() *OpenChannelCreateRequest {
	this := OpenChannelCreateRequest{}
	return &this
}

// GetChannelId returns the ChannelId field value
func (o *OpenChannelCreateRequest) GetChannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value
// and a boolean to check if the value has been set.
func (o *OpenChannelCreateRequest) GetChannelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelId, true
}

// SetChannelId sets field value
func (o *OpenChannelCreateRequest) SetChannelId(v string) {
	o.ChannelId = v
}

// GetDestroyType returns the DestroyType field value if set, zero value otherwise.
func (o *OpenChannelCreateRequest) GetDestroyType() int32 {
	if o == nil || IsNil(o.DestroyType) {
		var ret int32
		return ret
	}
	return *o.DestroyType
}

// GetDestroyTypeOk returns a tuple with the DestroyType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelCreateRequest) GetDestroyTypeOk() (*int32, bool) {
	if o == nil || IsNil(o.DestroyType) {
		return nil, false
	}
	return o.DestroyType, true
}

// HasDestroyType returns a boolean if a field has been set.
func (o *OpenChannelCreateRequest) HasDestroyType() bool {
	if o != nil && !IsNil(o.DestroyType) {
		return true
	}

	return false
}

// SetDestroyType gets a reference to the given int32 and assigns it to the DestroyType field.
func (o *OpenChannelCreateRequest) SetDestroyType(v int32) {
	o.DestroyType = &v
}

// GetTtlMinutes returns the TtlMinutes field value if set, zero value otherwise.
func (o *OpenChannelCreateRequest) GetTtlMinutes() int32 {
	if o == nil || IsNil(o.TtlMinutes) {
		var ret int32
		return ret
	}
	return *o.TtlMinutes
}

// GetTtlMinutesOk returns a tuple with the TtlMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelCreateRequest) GetTtlMinutesOk() (*int32, bool) {
	if o == nil || IsNil(o.TtlMinutes) {
		return nil, false
	}
	return o.TtlMinutes, true
}

// HasTtlMinutes returns a boolean if a field has been set.
func (o *OpenChannelCreateRequest) HasTtlMinutes() bool {
	if o != nil && !IsNil(o.TtlMinutes) {
		return true
	}

	return false
}

// SetTtlMinutes gets a reference to the given int32 and assigns it to the TtlMinutes field.
func (o *OpenChannelCreateRequest) SetTtlMinutes(v int32) {
	o.TtlMinutes = &v
}

// GetShouldFreeze returns the ShouldFreeze field value if set, zero value otherwise.
func (o *OpenChannelCreateRequest) GetShouldFreeze() bool {
	if o == nil || IsNil(o.ShouldFreeze) {
		var ret bool
		return ret
	}
	return *o.ShouldFreeze
}

// GetShouldFreezeOk returns a tuple with the ShouldFreeze field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelCreateRequest) GetShouldFreezeOk() (*bool, bool) {
	if o == nil || IsNil(o.ShouldFreeze) {
		return nil, false
	}
	return o.ShouldFreeze, true
}

// HasShouldFreeze returns a boolean if a field has been set.
func (o *OpenChannelCreateRequest) HasShouldFreeze() bool {
	if o != nil && !IsNil(o.ShouldFreeze) {
		return true
	}

	return false
}

// SetShouldFreeze gets a reference to the given bool and assigns it to the ShouldFreeze field.
func (o *OpenChannelCreateRequest) SetShouldFreeze(v bool) {
	o.ShouldFreeze = &v
}

// GetAllowedSendersList returns the AllowedSendersList field value if set, zero value otherwise.
func (o *OpenChannelCreateRequest) GetAllowedSendersList() []string {
	if o == nil || IsNil(o.AllowedSendersList) {
		var ret []string
		return ret
	}
	return o.AllowedSendersList
}

// GetAllowedSendersListOk returns a tuple with the AllowedSendersList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelCreateRequest) GetAllowedSendersListOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedSendersList) {
		return nil, false
	}
	return o.AllowedSendersList, true
}

// HasAllowedSendersList returns a boolean if a field has been set.
func (o *OpenChannelCreateRequest) HasAllowedSendersList() bool {
	if o != nil && !IsNil(o.AllowedSendersList) {
		return true
	}

	return false
}

// SetAllowedSendersList gets a reference to the given []string and assigns it to the AllowedSendersList field.
func (o *OpenChannelCreateRequest) SetAllowedSendersList(v []string) {
	o.AllowedSendersList = v
}

// GetMetadataOwnerId returns the MetadataOwnerId field value if set, zero value otherwise.
func (o *OpenChannelCreateRequest) GetMetadataOwnerId() string {
	if o == nil || IsNil(o.MetadataOwnerId) {
		var ret string
		return ret
	}
	return *o.MetadataOwnerId
}

// GetMetadataOwnerIdOk returns a tuple with the MetadataOwnerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelCreateRequest) GetMetadataOwnerIdOk() (*string, bool) {
	if o == nil || IsNil(o.MetadataOwnerId) {
		return nil, false
	}
	return o.MetadataOwnerId, true
}

// HasMetadataOwnerId returns a boolean if a field has been set.
func (o *OpenChannelCreateRequest) HasMetadataOwnerId() bool {
	if o != nil && !IsNil(o.MetadataOwnerId) {
		return true
	}

	return false
}

// SetMetadataOwnerId gets a reference to the given string and assigns it to the MetadataOwnerId field.
func (o *OpenChannelCreateRequest) SetMetadataOwnerId(v string) {
	o.MetadataOwnerId = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *OpenChannelCreateRequest) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelCreateRequest) GetMetadataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *OpenChannelCreateRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *OpenChannelCreateRequest) SetMetadata(v map[string]string) {
	o.Metadata = &v
}

func (o OpenChannelCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenChannelCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channelId"] = o.ChannelId
	if !IsNil(o.DestroyType) {
		toSerialize["destroyType"] = o.DestroyType
	}
	if !IsNil(o.TtlMinutes) {
		toSerialize["ttlMinutes"] = o.TtlMinutes
	}
	if !IsNil(o.ShouldFreeze) {
		toSerialize["shouldFreeze"] = o.ShouldFreeze
	}
	if !IsNil(o.AllowedSendersList) {
		toSerialize["allowedSendersList"] = o.AllowedSendersList
	}
	if !IsNil(o.MetadataOwnerId) {
		toSerialize["metadataOwnerId"] = o.MetadataOwnerId
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *OpenChannelCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channelId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenChannelCreateRequest := _OpenChannelCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenChannelCreateRequest)

	if err != nil {
		return err
	}

	*o = OpenChannelCreateRequest(varOpenChannelCreateRequest)

	return err
}

type NullableOpenChannelCreateRequest struct {
	value *OpenChannelCreateRequest
	isSet bool
}

func (v NullableOpenChannelCreateRequest) Get() *OpenChannelCreateRequest {
	return v.value
}

func (v *NullableOpenChannelCreateRequest) Set(val *OpenChannelCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenChannelCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenChannelCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenChannelCreateRequest(val *OpenChannelCreateRequest) *NullableOpenChannelCreateRequest {
	return &NullableOpenChannelCreateRequest{value: val, isSet: true}
}

func (v NullableOpenChannelCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenChannelCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


