/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
)

// checks if the GroupChannelFreezeListGetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupChannelFreezeListGetRequest{}

// GroupChannelFreezeListGetRequest struct for GroupChannelFreezeListGetRequest
type GroupChannelFreezeListGetRequest struct {
	// Optional specific group channel IDs to query.
	ChannelIds []string `json:"channelIds,omitempty"`
	Page *int32 `json:"page,omitempty"`
	PageSize *int32 `json:"pageSize,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GroupChannelFreezeListGetRequest GroupChannelFreezeListGetRequest

// NewGroupChannelFreezeListGetRequest instantiates a new GroupChannelFreezeListGetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupChannelFreezeListGetRequest() *GroupChannelFreezeListGetRequest {
	this := GroupChannelFreezeListGetRequest{}
	return &this
}

// NewGroupChannelFreezeListGetRequestWithDefaults instantiates a new GroupChannelFreezeListGetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupChannelFreezeListGetRequestWithDefaults() *GroupChannelFreezeListGetRequest {
	this := GroupChannelFreezeListGetRequest{}
	return &this
}

// GetChannelIds returns the ChannelIds field value if set, zero value otherwise.
func (o *GroupChannelFreezeListGetRequest) GetChannelIds() []string {
	if o == nil || IsNil(o.ChannelIds) {
		var ret []string
		return ret
	}
	return o.ChannelIds
}

// GetChannelIdsOk returns a tuple with the ChannelIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupChannelFreezeListGetRequest) GetChannelIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ChannelIds) {
		return nil, false
	}
	return o.ChannelIds, true
}

// HasChannelIds returns a boolean if a field has been set.
func (o *GroupChannelFreezeListGetRequest) HasChannelIds() bool {
	if o != nil && !IsNil(o.ChannelIds) {
		return true
	}

	return false
}

// SetChannelIds gets a reference to the given []string and assigns it to the ChannelIds field.
func (o *GroupChannelFreezeListGetRequest) SetChannelIds(v []string) {
	o.ChannelIds = v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *GroupChannelFreezeListGetRequest) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupChannelFreezeListGetRequest) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *GroupChannelFreezeListGetRequest) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *GroupChannelFreezeListGetRequest) SetPage(v int32) {
	o.Page = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *GroupChannelFreezeListGetRequest) GetPageSize() int32 {
	if o == nil || IsNil(o.PageSize) {
		var ret int32
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupChannelFreezeListGetRequest) GetPageSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *GroupChannelFreezeListGetRequest) HasPageSize() bool {
	if o != nil && !IsNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given int32 and assigns it to the PageSize field.
func (o *GroupChannelFreezeListGetRequest) SetPageSize(v int32) {
	o.PageSize = &v
}

func (o GroupChannelFreezeListGetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupChannelFreezeListGetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ChannelIds) {
		toSerialize["channelIds"] = o.ChannelIds
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.PageSize) {
		toSerialize["pageSize"] = o.PageSize
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GroupChannelFreezeListGetRequest) UnmarshalJSON(data []byte) (err error) {
	varGroupChannelFreezeListGetRequest := _GroupChannelFreezeListGetRequest{}

	err = json.Unmarshal(data, &varGroupChannelFreezeListGetRequest)

	if err != nil {
		return err
	}

	*o = GroupChannelFreezeListGetRequest(varGroupChannelFreezeListGetRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "channelIds")
		delete(additionalProperties, "page")
		delete(additionalProperties, "pageSize")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGroupChannelFreezeListGetRequest struct {
	value *GroupChannelFreezeListGetRequest
	isSet bool
}

func (v NullableGroupChannelFreezeListGetRequest) Get() *GroupChannelFreezeListGetRequest {
	return v.value
}

func (v *NullableGroupChannelFreezeListGetRequest) Set(val *GroupChannelFreezeListGetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupChannelFreezeListGetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupChannelFreezeListGetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupChannelFreezeListGetRequest(val *GroupChannelFreezeListGetRequest) *NullableGroupChannelFreezeListGetRequest {
	return &NullableGroupChannelFreezeListGetRequest{value: val, isSet: true}
}

func (v NullableGroupChannelFreezeListGetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupChannelFreezeListGetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


