/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.1
Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OpenChannelParticipantMuteListGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenChannelParticipantMuteListGetResponse{}

// OpenChannelParticipantMuteListGetResponse struct for OpenChannelParticipantMuteListGetResponse
type OpenChannelParticipantMuteListGetResponse struct {
	Code int32 `json:"code"`
	Result *OpenChannelParticipantMuteListGetResponseResult `json:"result,omitempty"`
}

type _OpenChannelParticipantMuteListGetResponse OpenChannelParticipantMuteListGetResponse

// NewOpenChannelParticipantMuteListGetResponse instantiates a new OpenChannelParticipantMuteListGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenChannelParticipantMuteListGetResponse(code int32) *OpenChannelParticipantMuteListGetResponse {
	this := OpenChannelParticipantMuteListGetResponse{}
	this.Code = code
	return &this
}

// NewOpenChannelParticipantMuteListGetResponseWithDefaults instantiates a new OpenChannelParticipantMuteListGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenChannelParticipantMuteListGetResponseWithDefaults() *OpenChannelParticipantMuteListGetResponse {
	this := OpenChannelParticipantMuteListGetResponse{}
	return &this
}

// GetCode returns the Code field value
func (o *OpenChannelParticipantMuteListGetResponse) GetCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *OpenChannelParticipantMuteListGetResponse) GetCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *OpenChannelParticipantMuteListGetResponse) SetCode(v int32) {
	o.Code = v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *OpenChannelParticipantMuteListGetResponse) GetResult() OpenChannelParticipantMuteListGetResponseResult {
	if o == nil || IsNil(o.Result) {
		var ret OpenChannelParticipantMuteListGetResponseResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelParticipantMuteListGetResponse) GetResultOk() (*OpenChannelParticipantMuteListGetResponseResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *OpenChannelParticipantMuteListGetResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given OpenChannelParticipantMuteListGetResponseResult and assigns it to the Result field.
func (o *OpenChannelParticipantMuteListGetResponse) SetResult(v OpenChannelParticipantMuteListGetResponseResult) {
	o.Result = &v
}

func (o OpenChannelParticipantMuteListGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenChannelParticipantMuteListGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

func (o *OpenChannelParticipantMuteListGetResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenChannelParticipantMuteListGetResponse := _OpenChannelParticipantMuteListGetResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenChannelParticipantMuteListGetResponse)

	if err != nil {
		return err
	}

	*o = OpenChannelParticipantMuteListGetResponse(varOpenChannelParticipantMuteListGetResponse)

	return err
}

type NullableOpenChannelParticipantMuteListGetResponse struct {
	value *OpenChannelParticipantMuteListGetResponse
	isSet bool
}

func (v NullableOpenChannelParticipantMuteListGetResponse) Get() *OpenChannelParticipantMuteListGetResponse {
	return v.value
}

func (v *NullableOpenChannelParticipantMuteListGetResponse) Set(val *OpenChannelParticipantMuteListGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenChannelParticipantMuteListGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenChannelParticipantMuteListGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenChannelParticipantMuteListGetResponse(val *OpenChannelParticipantMuteListGetResponse) *NullableOpenChannelParticipantMuteListGetResponse {
	return &NullableOpenChannelParticipantMuteListGetResponse{value: val, isSet: true}
}

func (v NullableOpenChannelParticipantMuteListGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenChannelParticipantMuteListGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


