/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserTagBatchSetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserTagBatchSetRequest{}

// UserTagBatchSetRequest struct for UserTagBatchSetRequest
type UserTagBatchSetRequest struct {
	UserIds []string `json:"userIds"`
	// Full replacement set of user tags. Sending an empty array clears all tags.
	Tags []string `json:"tags"`
}

type _UserTagBatchSetRequest UserTagBatchSetRequest

// NewUserTagBatchSetRequest instantiates a new UserTagBatchSetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserTagBatchSetRequest(userIds []string, tags []string) *UserTagBatchSetRequest {
	this := UserTagBatchSetRequest{}
	this.UserIds = userIds
	this.Tags = tags
	return &this
}

// NewUserTagBatchSetRequestWithDefaults instantiates a new UserTagBatchSetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserTagBatchSetRequestWithDefaults() *UserTagBatchSetRequest {
	this := UserTagBatchSetRequest{}
	return &this
}

// GetUserIds returns the UserIds field value
func (o *UserTagBatchSetRequest) GetUserIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.UserIds
}

// GetUserIdsOk returns a tuple with the UserIds field value
// and a boolean to check if the value has been set.
func (o *UserTagBatchSetRequest) GetUserIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserIds, true
}

// SetUserIds sets field value
func (o *UserTagBatchSetRequest) SetUserIds(v []string) {
	o.UserIds = v
}

// GetTags returns the Tags field value
func (o *UserTagBatchSetRequest) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value
// and a boolean to check if the value has been set.
func (o *UserTagBatchSetRequest) GetTagsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags, true
}

// SetTags sets field value
func (o *UserTagBatchSetRequest) SetTags(v []string) {
	o.Tags = v
}

func (o UserTagBatchSetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserTagBatchSetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["userIds"] = o.UserIds
	toSerialize["tags"] = o.Tags
	return toSerialize, nil
}

func (o *UserTagBatchSetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"userIds",
		"tags",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserTagBatchSetRequest := _UserTagBatchSetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserTagBatchSetRequest)

	if err != nil {
		return err
	}

	*o = UserTagBatchSetRequest(varUserTagBatchSetRequest)

	return err
}

type NullableUserTagBatchSetRequest struct {
	value *UserTagBatchSetRequest
	isSet bool
}

func (v NullableUserTagBatchSetRequest) Get() *UserTagBatchSetRequest {
	return v.value
}

func (v *NullableUserTagBatchSetRequest) Set(val *UserTagBatchSetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserTagBatchSetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserTagBatchSetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserTagBatchSetRequest(val *UserTagBatchSetRequest) *NullableUserTagBatchSetRequest {
	return &NullableUserTagBatchSetRequest{value: val, isSet: true}
}

func (v NullableUserTagBatchSetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserTagBatchSetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


