/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SystemChannelBroadcastDeleteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SystemChannelBroadcastDeleteRequest{}

// SystemChannelBroadcastDeleteRequest struct for SystemChannelBroadcastDeleteRequest
type SystemChannelBroadcastDeleteRequest struct {
	FromUserId string `json:"fromUserId"`
	MessageId string `json:"messageId"`
	SentAt *int64 `json:"sentAt,omitempty"`
	IsAdmin *int32 `json:"isAdmin,omitempty"`
	Extra *string `json:"extra,omitempty"`
	DisableUpdateLastMsg *bool `json:"disableUpdateLastMsg,omitempty"`
}

type _SystemChannelBroadcastDeleteRequest SystemChannelBroadcastDeleteRequest

// NewSystemChannelBroadcastDeleteRequest instantiates a new SystemChannelBroadcastDeleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSystemChannelBroadcastDeleteRequest(fromUserId string, messageId string) *SystemChannelBroadcastDeleteRequest {
	this := SystemChannelBroadcastDeleteRequest{}
	this.FromUserId = fromUserId
	this.MessageId = messageId
	return &this
}

// NewSystemChannelBroadcastDeleteRequestWithDefaults instantiates a new SystemChannelBroadcastDeleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSystemChannelBroadcastDeleteRequestWithDefaults() *SystemChannelBroadcastDeleteRequest {
	this := SystemChannelBroadcastDeleteRequest{}
	return &this
}

// GetFromUserId returns the FromUserId field value
func (o *SystemChannelBroadcastDeleteRequest) GetFromUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FromUserId
}

// GetFromUserIdOk returns a tuple with the FromUserId field value
// and a boolean to check if the value has been set.
func (o *SystemChannelBroadcastDeleteRequest) GetFromUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromUserId, true
}

// SetFromUserId sets field value
func (o *SystemChannelBroadcastDeleteRequest) SetFromUserId(v string) {
	o.FromUserId = v
}

// GetMessageId returns the MessageId field value
func (o *SystemChannelBroadcastDeleteRequest) GetMessageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MessageId
}

// GetMessageIdOk returns a tuple with the MessageId field value
// and a boolean to check if the value has been set.
func (o *SystemChannelBroadcastDeleteRequest) GetMessageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MessageId, true
}

// SetMessageId sets field value
func (o *SystemChannelBroadcastDeleteRequest) SetMessageId(v string) {
	o.MessageId = v
}

// GetSentAt returns the SentAt field value if set, zero value otherwise.
func (o *SystemChannelBroadcastDeleteRequest) GetSentAt() int64 {
	if o == nil || IsNil(o.SentAt) {
		var ret int64
		return ret
	}
	return *o.SentAt
}

// GetSentAtOk returns a tuple with the SentAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemChannelBroadcastDeleteRequest) GetSentAtOk() (*int64, bool) {
	if o == nil || IsNil(o.SentAt) {
		return nil, false
	}
	return o.SentAt, true
}

// HasSentAt returns a boolean if a field has been set.
func (o *SystemChannelBroadcastDeleteRequest) HasSentAt() bool {
	if o != nil && !IsNil(o.SentAt) {
		return true
	}

	return false
}

// SetSentAt gets a reference to the given int64 and assigns it to the SentAt field.
func (o *SystemChannelBroadcastDeleteRequest) SetSentAt(v int64) {
	o.SentAt = &v
}

// GetIsAdmin returns the IsAdmin field value if set, zero value otherwise.
func (o *SystemChannelBroadcastDeleteRequest) GetIsAdmin() int32 {
	if o == nil || IsNil(o.IsAdmin) {
		var ret int32
		return ret
	}
	return *o.IsAdmin
}

// GetIsAdminOk returns a tuple with the IsAdmin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemChannelBroadcastDeleteRequest) GetIsAdminOk() (*int32, bool) {
	if o == nil || IsNil(o.IsAdmin) {
		return nil, false
	}
	return o.IsAdmin, true
}

// HasIsAdmin returns a boolean if a field has been set.
func (o *SystemChannelBroadcastDeleteRequest) HasIsAdmin() bool {
	if o != nil && !IsNil(o.IsAdmin) {
		return true
	}

	return false
}

// SetIsAdmin gets a reference to the given int32 and assigns it to the IsAdmin field.
func (o *SystemChannelBroadcastDeleteRequest) SetIsAdmin(v int32) {
	o.IsAdmin = &v
}

// GetExtra returns the Extra field value if set, zero value otherwise.
func (o *SystemChannelBroadcastDeleteRequest) GetExtra() string {
	if o == nil || IsNil(o.Extra) {
		var ret string
		return ret
	}
	return *o.Extra
}

// GetExtraOk returns a tuple with the Extra field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemChannelBroadcastDeleteRequest) GetExtraOk() (*string, bool) {
	if o == nil || IsNil(o.Extra) {
		return nil, false
	}
	return o.Extra, true
}

// HasExtra returns a boolean if a field has been set.
func (o *SystemChannelBroadcastDeleteRequest) HasExtra() bool {
	if o != nil && !IsNil(o.Extra) {
		return true
	}

	return false
}

// SetExtra gets a reference to the given string and assigns it to the Extra field.
func (o *SystemChannelBroadcastDeleteRequest) SetExtra(v string) {
	o.Extra = &v
}

// GetDisableUpdateLastMsg returns the DisableUpdateLastMsg field value if set, zero value otherwise.
func (o *SystemChannelBroadcastDeleteRequest) GetDisableUpdateLastMsg() bool {
	if o == nil || IsNil(o.DisableUpdateLastMsg) {
		var ret bool
		return ret
	}
	return *o.DisableUpdateLastMsg
}

// GetDisableUpdateLastMsgOk returns a tuple with the DisableUpdateLastMsg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SystemChannelBroadcastDeleteRequest) GetDisableUpdateLastMsgOk() (*bool, bool) {
	if o == nil || IsNil(o.DisableUpdateLastMsg) {
		return nil, false
	}
	return o.DisableUpdateLastMsg, true
}

// HasDisableUpdateLastMsg returns a boolean if a field has been set.
func (o *SystemChannelBroadcastDeleteRequest) HasDisableUpdateLastMsg() bool {
	if o != nil && !IsNil(o.DisableUpdateLastMsg) {
		return true
	}

	return false
}

// SetDisableUpdateLastMsg gets a reference to the given bool and assigns it to the DisableUpdateLastMsg field.
func (o *SystemChannelBroadcastDeleteRequest) SetDisableUpdateLastMsg(v bool) {
	o.DisableUpdateLastMsg = &v
}

func (o SystemChannelBroadcastDeleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SystemChannelBroadcastDeleteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fromUserId"] = o.FromUserId
	toSerialize["messageId"] = o.MessageId
	if !IsNil(o.SentAt) {
		toSerialize["sentAt"] = o.SentAt
	}
	if !IsNil(o.IsAdmin) {
		toSerialize["isAdmin"] = o.IsAdmin
	}
	if !IsNil(o.Extra) {
		toSerialize["extra"] = o.Extra
	}
	if !IsNil(o.DisableUpdateLastMsg) {
		toSerialize["disableUpdateLastMsg"] = o.DisableUpdateLastMsg
	}
	return toSerialize, nil
}

func (o *SystemChannelBroadcastDeleteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fromUserId",
		"messageId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSystemChannelBroadcastDeleteRequest := _SystemChannelBroadcastDeleteRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSystemChannelBroadcastDeleteRequest)

	if err != nil {
		return err
	}

	*o = SystemChannelBroadcastDeleteRequest(varSystemChannelBroadcastDeleteRequest)

	return err
}

type NullableSystemChannelBroadcastDeleteRequest struct {
	value *SystemChannelBroadcastDeleteRequest
	isSet bool
}

func (v NullableSystemChannelBroadcastDeleteRequest) Get() *SystemChannelBroadcastDeleteRequest {
	return v.value
}

func (v *NullableSystemChannelBroadcastDeleteRequest) Set(val *SystemChannelBroadcastDeleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSystemChannelBroadcastDeleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSystemChannelBroadcastDeleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSystemChannelBroadcastDeleteRequest(val *SystemChannelBroadcastDeleteRequest) *NullableSystemChannelBroadcastDeleteRequest {
	return &NullableSystemChannelBroadcastDeleteRequest{value: val, isSet: true}
}

func (v NullableSystemChannelBroadcastDeleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSystemChannelBroadcastDeleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


