/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.0
Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GroupChannelListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupChannelListResponse{}

// GroupChannelListResponse struct for GroupChannelListResponse
type GroupChannelListResponse struct {
	Code int32 `json:"code"`
	Result *GroupChannelListResponseResult `json:"result,omitempty"`
}

type _GroupChannelListResponse GroupChannelListResponse

// NewGroupChannelListResponse instantiates a new GroupChannelListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupChannelListResponse(code int32) *GroupChannelListResponse {
	this := GroupChannelListResponse{}
	this.Code = code
	return &this
}

// NewGroupChannelListResponseWithDefaults instantiates a new GroupChannelListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupChannelListResponseWithDefaults() *GroupChannelListResponse {
	this := GroupChannelListResponse{}
	return &this
}

// GetCode returns the Code field value
func (o *GroupChannelListResponse) GetCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *GroupChannelListResponse) GetCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *GroupChannelListResponse) SetCode(v int32) {
	o.Code = v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *GroupChannelListResponse) GetResult() GroupChannelListResponseResult {
	if o == nil || IsNil(o.Result) {
		var ret GroupChannelListResponseResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupChannelListResponse) GetResultOk() (*GroupChannelListResponseResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *GroupChannelListResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given GroupChannelListResponseResult and assigns it to the Result field.
func (o *GroupChannelListResponse) SetResult(v GroupChannelListResponseResult) {
	o.Result = &v
}

func (o GroupChannelListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupChannelListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

func (o *GroupChannelListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupChannelListResponse := _GroupChannelListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGroupChannelListResponse)

	if err != nil {
		return err
	}

	*o = GroupChannelListResponse(varGroupChannelListResponse)

	return err
}

type NullableGroupChannelListResponse struct {
	value *GroupChannelListResponse
	isSet bool
}

func (v NullableGroupChannelListResponse) Get() *GroupChannelListResponse {
	return v.value
}

func (v *NullableGroupChannelListResponse) Set(val *GroupChannelListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupChannelListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupChannelListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupChannelListResponse(val *GroupChannelListResponse) *NullableGroupChannelListResponse {
	return &NullableGroupChannelListResponse{value: val, isSet: true}
}

func (v NullableGroupChannelListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupChannelListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


