/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DirectChannelStreamMessageSendRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DirectChannelStreamMessageSendRequest{}

// DirectChannelStreamMessageSendRequest struct for DirectChannelStreamMessageSendRequest
type DirectChannelStreamMessageSendRequest struct {
	// Sender user ID. The sender should have an access token so push notifications can display sender information correctly.
	FromUserId string `json:"fromUserId"`
	// Recipient user ID. Only a single recipient is supported per stream message.
	ToUserId string `json:"toUserId"`
	// Message type. Fixed value `RC:StreamMsg` for stream messages.
	MessageType string `json:"messageType"`
	Content StreamMessageContent `json:"content"`
	// Whether to sync the message to the sender's client while the sender is online. `1` enables sync and `0` disables it.
	IsEchoToSender *int32 `json:"isEchoToSender,omitempty"`
	// Whether to store the message in recipient cloud history. `0` means do not store and `1` means store.
	ShouldPersist *int32 `json:"shouldPersist,omitempty"`
	// Custom message metadata entries. Keys are limited to 32 characters and values to 4096 characters. Up to 100 key-value pairs.
	Metadata *map[string]string `json:"metadata,omitempty"`
	// Whether to keep this message from updating the channel's last-message preview.
	DisableUpdateLastMsg *bool `json:"disableUpdateLastMsg,omitempty"`
}

type _DirectChannelStreamMessageSendRequest DirectChannelStreamMessageSendRequest

// NewDirectChannelStreamMessageSendRequest instantiates a new DirectChannelStreamMessageSendRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDirectChannelStreamMessageSendRequest(fromUserId string, toUserId string, messageType string, content StreamMessageContent) *DirectChannelStreamMessageSendRequest {
	this := DirectChannelStreamMessageSendRequest{}
	this.FromUserId = fromUserId
	this.ToUserId = toUserId
	this.MessageType = messageType
	this.Content = content
	return &this
}

// NewDirectChannelStreamMessageSendRequestWithDefaults instantiates a new DirectChannelStreamMessageSendRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDirectChannelStreamMessageSendRequestWithDefaults() *DirectChannelStreamMessageSendRequest {
	this := DirectChannelStreamMessageSendRequest{}
	return &this
}

// GetFromUserId returns the FromUserId field value
func (o *DirectChannelStreamMessageSendRequest) GetFromUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FromUserId
}

// GetFromUserIdOk returns a tuple with the FromUserId field value
// and a boolean to check if the value has been set.
func (o *DirectChannelStreamMessageSendRequest) GetFromUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromUserId, true
}

// SetFromUserId sets field value
func (o *DirectChannelStreamMessageSendRequest) SetFromUserId(v string) {
	o.FromUserId = v
}

// GetToUserId returns the ToUserId field value
func (o *DirectChannelStreamMessageSendRequest) GetToUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ToUserId
}

// GetToUserIdOk returns a tuple with the ToUserId field value
// and a boolean to check if the value has been set.
func (o *DirectChannelStreamMessageSendRequest) GetToUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToUserId, true
}

// SetToUserId sets field value
func (o *DirectChannelStreamMessageSendRequest) SetToUserId(v string) {
	o.ToUserId = v
}

// GetMessageType returns the MessageType field value
func (o *DirectChannelStreamMessageSendRequest) GetMessageType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MessageType
}

// GetMessageTypeOk returns a tuple with the MessageType field value
// and a boolean to check if the value has been set.
func (o *DirectChannelStreamMessageSendRequest) GetMessageTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MessageType, true
}

// SetMessageType sets field value
func (o *DirectChannelStreamMessageSendRequest) SetMessageType(v string) {
	o.MessageType = v
}

// GetContent returns the Content field value
func (o *DirectChannelStreamMessageSendRequest) GetContent() StreamMessageContent {
	if o == nil {
		var ret StreamMessageContent
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *DirectChannelStreamMessageSendRequest) GetContentOk() (*StreamMessageContent, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *DirectChannelStreamMessageSendRequest) SetContent(v StreamMessageContent) {
	o.Content = v
}

// GetIsEchoToSender returns the IsEchoToSender field value if set, zero value otherwise.
func (o *DirectChannelStreamMessageSendRequest) GetIsEchoToSender() int32 {
	if o == nil || IsNil(o.IsEchoToSender) {
		var ret int32
		return ret
	}
	return *o.IsEchoToSender
}

// GetIsEchoToSenderOk returns a tuple with the IsEchoToSender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectChannelStreamMessageSendRequest) GetIsEchoToSenderOk() (*int32, bool) {
	if o == nil || IsNil(o.IsEchoToSender) {
		return nil, false
	}
	return o.IsEchoToSender, true
}

// HasIsEchoToSender returns a boolean if a field has been set.
func (o *DirectChannelStreamMessageSendRequest) HasIsEchoToSender() bool {
	if o != nil && !IsNil(o.IsEchoToSender) {
		return true
	}

	return false
}

// SetIsEchoToSender gets a reference to the given int32 and assigns it to the IsEchoToSender field.
func (o *DirectChannelStreamMessageSendRequest) SetIsEchoToSender(v int32) {
	o.IsEchoToSender = &v
}

// GetShouldPersist returns the ShouldPersist field value if set, zero value otherwise.
func (o *DirectChannelStreamMessageSendRequest) GetShouldPersist() int32 {
	if o == nil || IsNil(o.ShouldPersist) {
		var ret int32
		return ret
	}
	return *o.ShouldPersist
}

// GetShouldPersistOk returns a tuple with the ShouldPersist field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectChannelStreamMessageSendRequest) GetShouldPersistOk() (*int32, bool) {
	if o == nil || IsNil(o.ShouldPersist) {
		return nil, false
	}
	return o.ShouldPersist, true
}

// HasShouldPersist returns a boolean if a field has been set.
func (o *DirectChannelStreamMessageSendRequest) HasShouldPersist() bool {
	if o != nil && !IsNil(o.ShouldPersist) {
		return true
	}

	return false
}

// SetShouldPersist gets a reference to the given int32 and assigns it to the ShouldPersist field.
func (o *DirectChannelStreamMessageSendRequest) SetShouldPersist(v int32) {
	o.ShouldPersist = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *DirectChannelStreamMessageSendRequest) GetMetadata() map[string]string {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectChannelStreamMessageSendRequest) GetMetadataOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *DirectChannelStreamMessageSendRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]string and assigns it to the Metadata field.
func (o *DirectChannelStreamMessageSendRequest) SetMetadata(v map[string]string) {
	o.Metadata = &v
}

// GetDisableUpdateLastMsg returns the DisableUpdateLastMsg field value if set, zero value otherwise.
func (o *DirectChannelStreamMessageSendRequest) GetDisableUpdateLastMsg() bool {
	if o == nil || IsNil(o.DisableUpdateLastMsg) {
		var ret bool
		return ret
	}
	return *o.DisableUpdateLastMsg
}

// GetDisableUpdateLastMsgOk returns a tuple with the DisableUpdateLastMsg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DirectChannelStreamMessageSendRequest) GetDisableUpdateLastMsgOk() (*bool, bool) {
	if o == nil || IsNil(o.DisableUpdateLastMsg) {
		return nil, false
	}
	return o.DisableUpdateLastMsg, true
}

// HasDisableUpdateLastMsg returns a boolean if a field has been set.
func (o *DirectChannelStreamMessageSendRequest) HasDisableUpdateLastMsg() bool {
	if o != nil && !IsNil(o.DisableUpdateLastMsg) {
		return true
	}

	return false
}

// SetDisableUpdateLastMsg gets a reference to the given bool and assigns it to the DisableUpdateLastMsg field.
func (o *DirectChannelStreamMessageSendRequest) SetDisableUpdateLastMsg(v bool) {
	o.DisableUpdateLastMsg = &v
}

func (o DirectChannelStreamMessageSendRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DirectChannelStreamMessageSendRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fromUserId"] = o.FromUserId
	toSerialize["toUserId"] = o.ToUserId
	toSerialize["messageType"] = o.MessageType
	toSerialize["content"] = o.Content
	if !IsNil(o.IsEchoToSender) {
		toSerialize["isEchoToSender"] = o.IsEchoToSender
	}
	if !IsNil(o.ShouldPersist) {
		toSerialize["shouldPersist"] = o.ShouldPersist
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.DisableUpdateLastMsg) {
		toSerialize["disableUpdateLastMsg"] = o.DisableUpdateLastMsg
	}
	return toSerialize, nil
}

func (o *DirectChannelStreamMessageSendRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fromUserId",
		"toUserId",
		"messageType",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDirectChannelStreamMessageSendRequest := _DirectChannelStreamMessageSendRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDirectChannelStreamMessageSendRequest)

	if err != nil {
		return err
	}

	*o = DirectChannelStreamMessageSendRequest(varDirectChannelStreamMessageSendRequest)

	return err
}

type NullableDirectChannelStreamMessageSendRequest struct {
	value *DirectChannelStreamMessageSendRequest
	isSet bool
}

func (v NullableDirectChannelStreamMessageSendRequest) Get() *DirectChannelStreamMessageSendRequest {
	return v.value
}

func (v *NullableDirectChannelStreamMessageSendRequest) Set(val *DirectChannelStreamMessageSendRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDirectChannelStreamMessageSendRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDirectChannelStreamMessageSendRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDirectChannelStreamMessageSendRequest(val *DirectChannelStreamMessageSendRequest) *NullableDirectChannelStreamMessageSendRequest {
	return &NullableDirectChannelStreamMessageSendRequest{value: val, isSet: true}
}

func (v NullableDirectChannelStreamMessageSendRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDirectChannelStreamMessageSendRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


