/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the CommunityChannelUserGroupSubchannelListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommunityChannelUserGroupSubchannelListRequest{}

// CommunityChannelUserGroupSubchannelListRequest struct for CommunityChannelUserGroupSubchannelListRequest
type CommunityChannelUserGroupSubchannelListRequest struct {
	ChannelId string `json:"channelId"`
	UserGroupId string `json:"userGroupId"`
	Page *int32 `json:"page,omitempty"`
	PageSize *int32 `json:"pageSize,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CommunityChannelUserGroupSubchannelListRequest CommunityChannelUserGroupSubchannelListRequest

// NewCommunityChannelUserGroupSubchannelListRequest instantiates a new CommunityChannelUserGroupSubchannelListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommunityChannelUserGroupSubchannelListRequest(channelId string, userGroupId string) *CommunityChannelUserGroupSubchannelListRequest {
	this := CommunityChannelUserGroupSubchannelListRequest{}
	this.ChannelId = channelId
	this.UserGroupId = userGroupId
	var page int32 = 1
	this.Page = &page
	var pageSize int32 = 10
	this.PageSize = &pageSize
	return &this
}

// NewCommunityChannelUserGroupSubchannelListRequestWithDefaults instantiates a new CommunityChannelUserGroupSubchannelListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommunityChannelUserGroupSubchannelListRequestWithDefaults() *CommunityChannelUserGroupSubchannelListRequest {
	this := CommunityChannelUserGroupSubchannelListRequest{}
	var page int32 = 1
	this.Page = &page
	var pageSize int32 = 10
	this.PageSize = &pageSize
	return &this
}

// GetChannelId returns the ChannelId field value
func (o *CommunityChannelUserGroupSubchannelListRequest) GetChannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value
// and a boolean to check if the value has been set.
func (o *CommunityChannelUserGroupSubchannelListRequest) GetChannelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelId, true
}

// SetChannelId sets field value
func (o *CommunityChannelUserGroupSubchannelListRequest) SetChannelId(v string) {
	o.ChannelId = v
}

// GetUserGroupId returns the UserGroupId field value
func (o *CommunityChannelUserGroupSubchannelListRequest) GetUserGroupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserGroupId
}

// GetUserGroupIdOk returns a tuple with the UserGroupId field value
// and a boolean to check if the value has been set.
func (o *CommunityChannelUserGroupSubchannelListRequest) GetUserGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserGroupId, true
}

// SetUserGroupId sets field value
func (o *CommunityChannelUserGroupSubchannelListRequest) SetUserGroupId(v string) {
	o.UserGroupId = v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *CommunityChannelUserGroupSubchannelListRequest) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityChannelUserGroupSubchannelListRequest) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *CommunityChannelUserGroupSubchannelListRequest) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *CommunityChannelUserGroupSubchannelListRequest) SetPage(v int32) {
	o.Page = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *CommunityChannelUserGroupSubchannelListRequest) GetPageSize() int32 {
	if o == nil || IsNil(o.PageSize) {
		var ret int32
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityChannelUserGroupSubchannelListRequest) GetPageSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *CommunityChannelUserGroupSubchannelListRequest) HasPageSize() bool {
	if o != nil && !IsNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given int32 and assigns it to the PageSize field.
func (o *CommunityChannelUserGroupSubchannelListRequest) SetPageSize(v int32) {
	o.PageSize = &v
}

func (o CommunityChannelUserGroupSubchannelListRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommunityChannelUserGroupSubchannelListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channelId"] = o.ChannelId
	toSerialize["userGroupId"] = o.UserGroupId
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.PageSize) {
		toSerialize["pageSize"] = o.PageSize
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommunityChannelUserGroupSubchannelListRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channelId",
		"userGroupId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommunityChannelUserGroupSubchannelListRequest := _CommunityChannelUserGroupSubchannelListRequest{}

	err = json.Unmarshal(data, &varCommunityChannelUserGroupSubchannelListRequest)

	if err != nil {
		return err
	}

	*o = CommunityChannelUserGroupSubchannelListRequest(varCommunityChannelUserGroupSubchannelListRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "channelId")
		delete(additionalProperties, "userGroupId")
		delete(additionalProperties, "page")
		delete(additionalProperties, "pageSize")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommunityChannelUserGroupSubchannelListRequest struct {
	value *CommunityChannelUserGroupSubchannelListRequest
	isSet bool
}

func (v NullableCommunityChannelUserGroupSubchannelListRequest) Get() *CommunityChannelUserGroupSubchannelListRequest {
	return v.value
}

func (v *NullableCommunityChannelUserGroupSubchannelListRequest) Set(val *CommunityChannelUserGroupSubchannelListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCommunityChannelUserGroupSubchannelListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCommunityChannelUserGroupSubchannelListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommunityChannelUserGroupSubchannelListRequest(val *CommunityChannelUserGroupSubchannelListRequest) *NullableCommunityChannelUserGroupSubchannelListRequest {
	return &NullableCommunityChannelUserGroupSubchannelListRequest{value: val, isSet: true}
}

func (v NullableCommunityChannelUserGroupSubchannelListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommunityChannelUserGroupSubchannelListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


