/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
)

// checks if the MessageChannelDelivery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageChannelDelivery{}

// MessageChannelDelivery struct for MessageChannelDelivery
type MessageChannelDelivery struct {
	ChannelId *string `json:"channelId,omitempty"`
	MessageId *string `json:"messageId,omitempty"`
}

// NewMessageChannelDelivery instantiates a new MessageChannelDelivery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageChannelDelivery() *MessageChannelDelivery {
	this := MessageChannelDelivery{}
	return &this
}

// NewMessageChannelDeliveryWithDefaults instantiates a new MessageChannelDelivery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageChannelDeliveryWithDefaults() *MessageChannelDelivery {
	this := MessageChannelDelivery{}
	return &this
}

// GetChannelId returns the ChannelId field value if set, zero value otherwise.
func (o *MessageChannelDelivery) GetChannelId() string {
	if o == nil || IsNil(o.ChannelId) {
		var ret string
		return ret
	}
	return *o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageChannelDelivery) GetChannelIdOk() (*string, bool) {
	if o == nil || IsNil(o.ChannelId) {
		return nil, false
	}
	return o.ChannelId, true
}

// HasChannelId returns a boolean if a field has been set.
func (o *MessageChannelDelivery) HasChannelId() bool {
	if o != nil && !IsNil(o.ChannelId) {
		return true
	}

	return false
}

// SetChannelId gets a reference to the given string and assigns it to the ChannelId field.
func (o *MessageChannelDelivery) SetChannelId(v string) {
	o.ChannelId = &v
}

// GetMessageId returns the MessageId field value if set, zero value otherwise.
func (o *MessageChannelDelivery) GetMessageId() string {
	if o == nil || IsNil(o.MessageId) {
		var ret string
		return ret
	}
	return *o.MessageId
}

// GetMessageIdOk returns a tuple with the MessageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageChannelDelivery) GetMessageIdOk() (*string, bool) {
	if o == nil || IsNil(o.MessageId) {
		return nil, false
	}
	return o.MessageId, true
}

// HasMessageId returns a boolean if a field has been set.
func (o *MessageChannelDelivery) HasMessageId() bool {
	if o != nil && !IsNil(o.MessageId) {
		return true
	}

	return false
}

// SetMessageId gets a reference to the given string and assigns it to the MessageId field.
func (o *MessageChannelDelivery) SetMessageId(v string) {
	o.MessageId = &v
}

func (o MessageChannelDelivery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageChannelDelivery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ChannelId) {
		toSerialize["channelId"] = o.ChannelId
	}
	if !IsNil(o.MessageId) {
		toSerialize["messageId"] = o.MessageId
	}
	return toSerialize, nil
}

type NullableMessageChannelDelivery struct {
	value *MessageChannelDelivery
	isSet bool
}

func (v NullableMessageChannelDelivery) Get() *MessageChannelDelivery {
	return v.value
}

func (v *NullableMessageChannelDelivery) Set(val *MessageChannelDelivery) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageChannelDelivery) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageChannelDelivery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageChannelDelivery(val *MessageChannelDelivery) *NullableMessageChannelDelivery {
	return &NullableMessageChannelDelivery{value: val, isSet: true}
}

func (v NullableMessageChannelDelivery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageChannelDelivery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


