/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.1
Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProfanityWordItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProfanityWordItem{}

// ProfanityWordItem struct for ProfanityWordItem
type ProfanityWordItem struct {
	// Profanity word content.
	Word string `json:"word"`
	// Replacement content. When omitted, messages containing the word are blocked instead of replaced.
	Replacement *string `json:"replacement,omitempty"`
}

type _ProfanityWordItem ProfanityWordItem

// NewProfanityWordItem instantiates a new ProfanityWordItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProfanityWordItem(word string) *ProfanityWordItem {
	this := ProfanityWordItem{}
	this.Word = word
	return &this
}

// NewProfanityWordItemWithDefaults instantiates a new ProfanityWordItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProfanityWordItemWithDefaults() *ProfanityWordItem {
	this := ProfanityWordItem{}
	return &this
}

// GetWord returns the Word field value
func (o *ProfanityWordItem) GetWord() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Word
}

// GetWordOk returns a tuple with the Word field value
// and a boolean to check if the value has been set.
func (o *ProfanityWordItem) GetWordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Word, true
}

// SetWord sets field value
func (o *ProfanityWordItem) SetWord(v string) {
	o.Word = v
}

// GetReplacement returns the Replacement field value if set, zero value otherwise.
func (o *ProfanityWordItem) GetReplacement() string {
	if o == nil || IsNil(o.Replacement) {
		var ret string
		return ret
	}
	return *o.Replacement
}

// GetReplacementOk returns a tuple with the Replacement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProfanityWordItem) GetReplacementOk() (*string, bool) {
	if o == nil || IsNil(o.Replacement) {
		return nil, false
	}
	return o.Replacement, true
}

// HasReplacement returns a boolean if a field has been set.
func (o *ProfanityWordItem) HasReplacement() bool {
	if o != nil && !IsNil(o.Replacement) {
		return true
	}

	return false
}

// SetReplacement gets a reference to the given string and assigns it to the Replacement field.
func (o *ProfanityWordItem) SetReplacement(v string) {
	o.Replacement = &v
}

func (o ProfanityWordItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProfanityWordItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["word"] = o.Word
	if !IsNil(o.Replacement) {
		toSerialize["replacement"] = o.Replacement
	}
	return toSerialize, nil
}

func (o *ProfanityWordItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"word",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProfanityWordItem := _ProfanityWordItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProfanityWordItem)

	if err != nil {
		return err
	}

	*o = ProfanityWordItem(varProfanityWordItem)

	return err
}

type NullableProfanityWordItem struct {
	value *ProfanityWordItem
	isSet bool
}

func (v NullableProfanityWordItem) Get() *ProfanityWordItem {
	return v.value
}

func (v *NullableProfanityWordItem) Set(val *ProfanityWordItem) {
	v.value = val
	v.isSet = true
}

func (v NullableProfanityWordItem) IsSet() bool {
	return v.isSet
}

func (v *NullableProfanityWordItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProfanityWordItem(val *ProfanityWordItem) *NullableProfanityWordItem {
	return &NullableProfanityWordItem{value: val, isSet: true}
}

func (v NullableProfanityWordItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProfanityWordItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


