/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the OpenChannelParticipantExistResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenChannelParticipantExistResponse{}

// OpenChannelParticipantExistResponse struct for OpenChannelParticipantExistResponse
type OpenChannelParticipantExistResponse struct {
	// Return code. `0` indicates success.
	Code int32 `json:"code"`
	Result *OpenChannelParticipantExistResponseResult `json:"result,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OpenChannelParticipantExistResponse OpenChannelParticipantExistResponse

// NewOpenChannelParticipantExistResponse instantiates a new OpenChannelParticipantExistResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenChannelParticipantExistResponse(code int32) *OpenChannelParticipantExistResponse {
	this := OpenChannelParticipantExistResponse{}
	this.Code = code
	return &this
}

// NewOpenChannelParticipantExistResponseWithDefaults instantiates a new OpenChannelParticipantExistResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenChannelParticipantExistResponseWithDefaults() *OpenChannelParticipantExistResponse {
	this := OpenChannelParticipantExistResponse{}
	return &this
}

// GetCode returns the Code field value
func (o *OpenChannelParticipantExistResponse) GetCode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *OpenChannelParticipantExistResponse) GetCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *OpenChannelParticipantExistResponse) SetCode(v int32) {
	o.Code = v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *OpenChannelParticipantExistResponse) GetResult() OpenChannelParticipantExistResponseResult {
	if o == nil || IsNil(o.Result) {
		var ret OpenChannelParticipantExistResponseResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelParticipantExistResponse) GetResultOk() (*OpenChannelParticipantExistResponseResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *OpenChannelParticipantExistResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given OpenChannelParticipantExistResponseResult and assigns it to the Result field.
func (o *OpenChannelParticipantExistResponse) SetResult(v OpenChannelParticipantExistResponseResult) {
	o.Result = &v
}

func (o OpenChannelParticipantExistResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenChannelParticipantExistResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OpenChannelParticipantExistResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenChannelParticipantExistResponse := _OpenChannelParticipantExistResponse{}

	err = json.Unmarshal(data, &varOpenChannelParticipantExistResponse)

	if err != nil {
		return err
	}

	*o = OpenChannelParticipantExistResponse(varOpenChannelParticipantExistResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "result")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOpenChannelParticipantExistResponse struct {
	value *OpenChannelParticipantExistResponse
	isSet bool
}

func (v NullableOpenChannelParticipantExistResponse) Get() *OpenChannelParticipantExistResponse {
	return v.value
}

func (v *NullableOpenChannelParticipantExistResponse) Set(val *OpenChannelParticipantExistResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenChannelParticipantExistResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenChannelParticipantExistResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenChannelParticipantExistResponse(val *OpenChannelParticipantExistResponse) *NullableOpenChannelParticipantExistResponse {
	return &NullableOpenChannelParticipantExistResponse{value: val, isSet: true}
}

func (v NullableOpenChannelParticipantExistResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenChannelParticipantExistResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


