/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the OpenChannelParticipantListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenChannelParticipantListRequest{}

// OpenChannelParticipantListRequest struct for OpenChannelParticipantListRequest
type OpenChannelParticipantListRequest struct {
	ChannelId string `json:"channelId"`
	PageSize *int32 `json:"pageSize,omitempty"`
	// `1` for ascending join time and `2` for descending join time.
	Order *int32 `json:"order,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OpenChannelParticipantListRequest OpenChannelParticipantListRequest

// NewOpenChannelParticipantListRequest instantiates a new OpenChannelParticipantListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenChannelParticipantListRequest(channelId string) *OpenChannelParticipantListRequest {
	this := OpenChannelParticipantListRequest{}
	this.ChannelId = channelId
	return &this
}

// NewOpenChannelParticipantListRequestWithDefaults instantiates a new OpenChannelParticipantListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenChannelParticipantListRequestWithDefaults() *OpenChannelParticipantListRequest {
	this := OpenChannelParticipantListRequest{}
	return &this
}

// GetChannelId returns the ChannelId field value
func (o *OpenChannelParticipantListRequest) GetChannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value
// and a boolean to check if the value has been set.
func (o *OpenChannelParticipantListRequest) GetChannelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelId, true
}

// SetChannelId sets field value
func (o *OpenChannelParticipantListRequest) SetChannelId(v string) {
	o.ChannelId = v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *OpenChannelParticipantListRequest) GetPageSize() int32 {
	if o == nil || IsNil(o.PageSize) {
		var ret int32
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelParticipantListRequest) GetPageSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *OpenChannelParticipantListRequest) HasPageSize() bool {
	if o != nil && !IsNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given int32 and assigns it to the PageSize field.
func (o *OpenChannelParticipantListRequest) SetPageSize(v int32) {
	o.PageSize = &v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *OpenChannelParticipantListRequest) GetOrder() int32 {
	if o == nil || IsNil(o.Order) {
		var ret int32
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelParticipantListRequest) GetOrderOk() (*int32, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *OpenChannelParticipantListRequest) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given int32 and assigns it to the Order field.
func (o *OpenChannelParticipantListRequest) SetOrder(v int32) {
	o.Order = &v
}

func (o OpenChannelParticipantListRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenChannelParticipantListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channelId"] = o.ChannelId
	if !IsNil(o.PageSize) {
		toSerialize["pageSize"] = o.PageSize
	}
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OpenChannelParticipantListRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channelId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenChannelParticipantListRequest := _OpenChannelParticipantListRequest{}

	err = json.Unmarshal(data, &varOpenChannelParticipantListRequest)

	if err != nil {
		return err
	}

	*o = OpenChannelParticipantListRequest(varOpenChannelParticipantListRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "channelId")
		delete(additionalProperties, "pageSize")
		delete(additionalProperties, "order")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOpenChannelParticipantListRequest struct {
	value *OpenChannelParticipantListRequest
	isSet bool
}

func (v NullableOpenChannelParticipantListRequest) Get() *OpenChannelParticipantListRequest {
	return v.value
}

func (v *NullableOpenChannelParticipantListRequest) Set(val *OpenChannelParticipantListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenChannelParticipantListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenChannelParticipantListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenChannelParticipantListRequest(val *OpenChannelParticipantListRequest) *NullableOpenChannelParticipantListRequest {
	return &NullableOpenChannelParticipantListRequest{value: val, isSet: true}
}

func (v NullableOpenChannelParticipantListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenChannelParticipantListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


