/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OpenChannelDestroyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenChannelDestroyRequest{}

// OpenChannelDestroyRequest struct for OpenChannelDestroyRequest
type OpenChannelDestroyRequest struct {
	// Legacy `chatroomIds`.
	ChannelIds []string `json:"channelIds"`
}

type _OpenChannelDestroyRequest OpenChannelDestroyRequest

// NewOpenChannelDestroyRequest instantiates a new OpenChannelDestroyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenChannelDestroyRequest(channelIds []string) *OpenChannelDestroyRequest {
	this := OpenChannelDestroyRequest{}
	this.ChannelIds = channelIds
	return &this
}

// NewOpenChannelDestroyRequestWithDefaults instantiates a new OpenChannelDestroyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenChannelDestroyRequestWithDefaults() *OpenChannelDestroyRequest {
	this := OpenChannelDestroyRequest{}
	return &this
}

// GetChannelIds returns the ChannelIds field value
func (o *OpenChannelDestroyRequest) GetChannelIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ChannelIds
}

// GetChannelIdsOk returns a tuple with the ChannelIds field value
// and a boolean to check if the value has been set.
func (o *OpenChannelDestroyRequest) GetChannelIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ChannelIds, true
}

// SetChannelIds sets field value
func (o *OpenChannelDestroyRequest) SetChannelIds(v []string) {
	o.ChannelIds = v
}

func (o OpenChannelDestroyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenChannelDestroyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channelIds"] = o.ChannelIds
	return toSerialize, nil
}

func (o *OpenChannelDestroyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channelIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenChannelDestroyRequest := _OpenChannelDestroyRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenChannelDestroyRequest)

	if err != nil {
		return err
	}

	*o = OpenChannelDestroyRequest(varOpenChannelDestroyRequest)

	return err
}

type NullableOpenChannelDestroyRequest struct {
	value *OpenChannelDestroyRequest
	isSet bool
}

func (v NullableOpenChannelDestroyRequest) Get() *OpenChannelDestroyRequest {
	return v.value
}

func (v *NullableOpenChannelDestroyRequest) Set(val *OpenChannelDestroyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenChannelDestroyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenChannelDestroyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenChannelDestroyRequest(val *OpenChannelDestroyRequest) *NullableOpenChannelDestroyRequest {
	return &NullableOpenChannelDestroyRequest{value: val, isSet: true}
}

func (v NullableOpenChannelDestroyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenChannelDestroyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


