/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CommunityChannelUserGroupItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommunityChannelUserGroupItem{}

// CommunityChannelUserGroupItem struct for CommunityChannelUserGroupItem
type CommunityChannelUserGroupItem struct {
	UserGroupId string `json:"userGroupId"`
}

type _CommunityChannelUserGroupItem CommunityChannelUserGroupItem

// NewCommunityChannelUserGroupItem instantiates a new CommunityChannelUserGroupItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommunityChannelUserGroupItem(userGroupId string) *CommunityChannelUserGroupItem {
	this := CommunityChannelUserGroupItem{}
	this.UserGroupId = userGroupId
	return &this
}

// NewCommunityChannelUserGroupItemWithDefaults instantiates a new CommunityChannelUserGroupItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommunityChannelUserGroupItemWithDefaults() *CommunityChannelUserGroupItem {
	this := CommunityChannelUserGroupItem{}
	return &this
}

// GetUserGroupId returns the UserGroupId field value
func (o *CommunityChannelUserGroupItem) GetUserGroupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserGroupId
}

// GetUserGroupIdOk returns a tuple with the UserGroupId field value
// and a boolean to check if the value has been set.
func (o *CommunityChannelUserGroupItem) GetUserGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserGroupId, true
}

// SetUserGroupId sets field value
func (o *CommunityChannelUserGroupItem) SetUserGroupId(v string) {
	o.UserGroupId = v
}

func (o CommunityChannelUserGroupItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommunityChannelUserGroupItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["userGroupId"] = o.UserGroupId
	return toSerialize, nil
}

func (o *CommunityChannelUserGroupItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"userGroupId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommunityChannelUserGroupItem := _CommunityChannelUserGroupItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCommunityChannelUserGroupItem)

	if err != nil {
		return err
	}

	*o = CommunityChannelUserGroupItem(varCommunityChannelUserGroupItem)

	return err
}

type NullableCommunityChannelUserGroupItem struct {
	value *CommunityChannelUserGroupItem
	isSet bool
}

func (v NullableCommunityChannelUserGroupItem) Get() *CommunityChannelUserGroupItem {
	return v.value
}

func (v *NullableCommunityChannelUserGroupItem) Set(val *CommunityChannelUserGroupItem) {
	v.value = val
	v.isSet = true
}

func (v NullableCommunityChannelUserGroupItem) IsSet() bool {
	return v.isSet
}

func (v *NullableCommunityChannelUserGroupItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommunityChannelUserGroupItem(val *CommunityChannelUserGroupItem) *NullableCommunityChannelUserGroupItem {
	return &NullableCommunityChannelUserGroupItem{value: val, isSet: true}
}

func (v NullableCommunityChannelUserGroupItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommunityChannelUserGroupItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


