/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
)

// checks if the MessageMetadataListItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageMetadataListItem{}

// MessageMetadataListItem Matches `com.rcloud.server.api.model.v4.output.MetadataItem`.
type MessageMetadataListItem struct {
	Key *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
	UpdatedAt *int64 `json:"updatedAt,omitempty"`
}

// NewMessageMetadataListItem instantiates a new MessageMetadataListItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageMetadataListItem() *MessageMetadataListItem {
	this := MessageMetadataListItem{}
	return &this
}

// NewMessageMetadataListItemWithDefaults instantiates a new MessageMetadataListItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageMetadataListItemWithDefaults() *MessageMetadataListItem {
	this := MessageMetadataListItem{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *MessageMetadataListItem) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageMetadataListItem) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *MessageMetadataListItem) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *MessageMetadataListItem) SetKey(v string) {
	o.Key = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *MessageMetadataListItem) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageMetadataListItem) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *MessageMetadataListItem) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *MessageMetadataListItem) SetValue(v string) {
	o.Value = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *MessageMetadataListItem) GetUpdatedAt() int64 {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret int64
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageMetadataListItem) GetUpdatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *MessageMetadataListItem) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given int64 and assigns it to the UpdatedAt field.
func (o *MessageMetadataListItem) SetUpdatedAt(v int64) {
	o.UpdatedAt = &v
}

func (o MessageMetadataListItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageMetadataListItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableMessageMetadataListItem struct {
	value *MessageMetadataListItem
	isSet bool
}

func (v NullableMessageMetadataListItem) Get() *MessageMetadataListItem {
	return v.value
}

func (v *NullableMessageMetadataListItem) Set(val *MessageMetadataListItem) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageMetadataListItem) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageMetadataListItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageMetadataListItem(val *MessageMetadataListItem) *NullableMessageMetadataListItem {
	return &NullableMessageMetadataListItem{value: val, isSet: true}
}

func (v NullableMessageMetadataListItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageMetadataListItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


