/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
)

// checks if the MessageRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageRecord{}

// MessageRecord struct for MessageRecord
type MessageRecord struct {
	// Channel identifier of the stored message.
	ChannelId *string `json:"channelId,omitempty"`
	// Community subchannel ID associated with the stored message, when applicable.
	SubchannelId *string `json:"subchannelId,omitempty"`
	// Sender user ID of the stored message.
	FromUserId *string `json:"fromUserId,omitempty"`
	// Unique message ID.
	MessageId *string `json:"messageId,omitempty"`
	// Message send timestamp in milliseconds.
	SentAt *int64 `json:"sentAt,omitempty"`
	// Message type of the stored message.
	MessageType *string `json:"messageType,omitempty"`
	// Channel type of the stored message.
	ChannelType *int32 `json:"channelType,omitempty"`
	// Raw message content payload as stored by the service.
	Content *string `json:"content,omitempty"`
	// Whether the message has metadata entries attached.
	MetadataEnabled *bool `json:"hasMetadata,omitempty"`
	// List of metadata entries (`CommunityHistoryMessage` uses `List<MetadataItem>`, not a map).
	Metadata []MessageMetadataListItem `json:"metadata,omitempty"`
}

// NewMessageRecord instantiates a new MessageRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageRecord() *MessageRecord {
	this := MessageRecord{}
	return &this
}

// NewMessageRecordWithDefaults instantiates a new MessageRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageRecordWithDefaults() *MessageRecord {
	this := MessageRecord{}
	return &this
}

// GetChannelId returns the ChannelId field value if set, zero value otherwise.
func (o *MessageRecord) GetChannelId() string {
	if o == nil || IsNil(o.ChannelId) {
		var ret string
		return ret
	}
	return *o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageRecord) GetChannelIdOk() (*string, bool) {
	if o == nil || IsNil(o.ChannelId) {
		return nil, false
	}
	return o.ChannelId, true
}

// HasChannelId returns a boolean if a field has been set.
func (o *MessageRecord) HasChannelId() bool {
	if o != nil && !IsNil(o.ChannelId) {
		return true
	}

	return false
}

// SetChannelId gets a reference to the given string and assigns it to the ChannelId field.
func (o *MessageRecord) SetChannelId(v string) {
	o.ChannelId = &v
}

// GetSubchannelId returns the SubchannelId field value if set, zero value otherwise.
func (o *MessageRecord) GetSubchannelId() string {
	if o == nil || IsNil(o.SubchannelId) {
		var ret string
		return ret
	}
	return *o.SubchannelId
}

// GetSubchannelIdOk returns a tuple with the SubchannelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageRecord) GetSubchannelIdOk() (*string, bool) {
	if o == nil || IsNil(o.SubchannelId) {
		return nil, false
	}
	return o.SubchannelId, true
}

// HasSubchannelId returns a boolean if a field has been set.
func (o *MessageRecord) HasSubchannelId() bool {
	if o != nil && !IsNil(o.SubchannelId) {
		return true
	}

	return false
}

// SetSubchannelId gets a reference to the given string and assigns it to the SubchannelId field.
func (o *MessageRecord) SetSubchannelId(v string) {
	o.SubchannelId = &v
}

// GetFromUserId returns the FromUserId field value if set, zero value otherwise.
func (o *MessageRecord) GetFromUserId() string {
	if o == nil || IsNil(o.FromUserId) {
		var ret string
		return ret
	}
	return *o.FromUserId
}

// GetFromUserIdOk returns a tuple with the FromUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageRecord) GetFromUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.FromUserId) {
		return nil, false
	}
	return o.FromUserId, true
}

// HasFromUserId returns a boolean if a field has been set.
func (o *MessageRecord) HasFromUserId() bool {
	if o != nil && !IsNil(o.FromUserId) {
		return true
	}

	return false
}

// SetFromUserId gets a reference to the given string and assigns it to the FromUserId field.
func (o *MessageRecord) SetFromUserId(v string) {
	o.FromUserId = &v
}

// GetMessageId returns the MessageId field value if set, zero value otherwise.
func (o *MessageRecord) GetMessageId() string {
	if o == nil || IsNil(o.MessageId) {
		var ret string
		return ret
	}
	return *o.MessageId
}

// GetMessageIdOk returns a tuple with the MessageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageRecord) GetMessageIdOk() (*string, bool) {
	if o == nil || IsNil(o.MessageId) {
		return nil, false
	}
	return o.MessageId, true
}

// HasMessageId returns a boolean if a field has been set.
func (o *MessageRecord) HasMessageId() bool {
	if o != nil && !IsNil(o.MessageId) {
		return true
	}

	return false
}

// SetMessageId gets a reference to the given string and assigns it to the MessageId field.
func (o *MessageRecord) SetMessageId(v string) {
	o.MessageId = &v
}

// GetSentAt returns the SentAt field value if set, zero value otherwise.
func (o *MessageRecord) GetSentAt() int64 {
	if o == nil || IsNil(o.SentAt) {
		var ret int64
		return ret
	}
	return *o.SentAt
}

// GetSentAtOk returns a tuple with the SentAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageRecord) GetSentAtOk() (*int64, bool) {
	if o == nil || IsNil(o.SentAt) {
		return nil, false
	}
	return o.SentAt, true
}

// HasSentAt returns a boolean if a field has been set.
func (o *MessageRecord) HasSentAt() bool {
	if o != nil && !IsNil(o.SentAt) {
		return true
	}

	return false
}

// SetSentAt gets a reference to the given int64 and assigns it to the SentAt field.
func (o *MessageRecord) SetSentAt(v int64) {
	o.SentAt = &v
}

// GetMessageType returns the MessageType field value if set, zero value otherwise.
func (o *MessageRecord) GetMessageType() string {
	if o == nil || IsNil(o.MessageType) {
		var ret string
		return ret
	}
	return *o.MessageType
}

// GetMessageTypeOk returns a tuple with the MessageType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageRecord) GetMessageTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MessageType) {
		return nil, false
	}
	return o.MessageType, true
}

// HasMessageType returns a boolean if a field has been set.
func (o *MessageRecord) HasMessageType() bool {
	if o != nil && !IsNil(o.MessageType) {
		return true
	}

	return false
}

// SetMessageType gets a reference to the given string and assigns it to the MessageType field.
func (o *MessageRecord) SetMessageType(v string) {
	o.MessageType = &v
}

// GetChannelType returns the ChannelType field value if set, zero value otherwise.
func (o *MessageRecord) GetChannelType() int32 {
	if o == nil || IsNil(o.ChannelType) {
		var ret int32
		return ret
	}
	return *o.ChannelType
}

// GetChannelTypeOk returns a tuple with the ChannelType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageRecord) GetChannelTypeOk() (*int32, bool) {
	if o == nil || IsNil(o.ChannelType) {
		return nil, false
	}
	return o.ChannelType, true
}

// HasChannelType returns a boolean if a field has been set.
func (o *MessageRecord) HasChannelType() bool {
	if o != nil && !IsNil(o.ChannelType) {
		return true
	}

	return false
}

// SetChannelType gets a reference to the given int32 and assigns it to the ChannelType field.
func (o *MessageRecord) SetChannelType(v int32) {
	o.ChannelType = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *MessageRecord) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageRecord) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *MessageRecord) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *MessageRecord) SetContent(v string) {
	o.Content = &v
}

// GetHasMetadata returns the HasMetadata field value if set, zero value otherwise.
func (o *MessageRecord) GetHasMetadata() bool {
	if o == nil || IsNil(o.MetadataEnabled) {
		var ret bool
		return ret
	}
	return *o.MetadataEnabled
}

// GetHasMetadataOk returns a tuple with the HasMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageRecord) GetHasMetadataOk() (*bool, bool) {
	if o == nil || IsNil(o.MetadataEnabled) {
		return nil, false
	}
	return o.MetadataEnabled, true
}

// HasHasMetadata returns a boolean if a field has been set.
func (o *MessageRecord) HasHasMetadata() bool {
	if o != nil && !IsNil(o.MetadataEnabled) {
		return true
	}

	return false
}

// SetHasMetadata gets a reference to the given bool and assigns it to the HasMetadata field.
func (o *MessageRecord) SetHasMetadata(v bool) {
	o.MetadataEnabled = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *MessageRecord) GetMetadata() []MessageMetadataListItem {
	if o == nil || IsNil(o.Metadata) {
		var ret []MessageMetadataListItem
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageRecord) GetMetadataOk() ([]MessageMetadataListItem, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *MessageRecord) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given []MessageMetadataListItem and assigns it to the Metadata field.
func (o *MessageRecord) SetMetadata(v []MessageMetadataListItem) {
	o.Metadata = v
}

func (o MessageRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ChannelId) {
		toSerialize["channelId"] = o.ChannelId
	}
	if !IsNil(o.SubchannelId) {
		toSerialize["subchannelId"] = o.SubchannelId
	}
	if !IsNil(o.FromUserId) {
		toSerialize["fromUserId"] = o.FromUserId
	}
	if !IsNil(o.MessageId) {
		toSerialize["messageId"] = o.MessageId
	}
	if !IsNil(o.SentAt) {
		toSerialize["sentAt"] = o.SentAt
	}
	if !IsNil(o.MessageType) {
		toSerialize["messageType"] = o.MessageType
	}
	if !IsNil(o.ChannelType) {
		toSerialize["channelType"] = o.ChannelType
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.MetadataEnabled) {
		toSerialize["hasMetadata"] = o.MetadataEnabled
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

type NullableMessageRecord struct {
	value *MessageRecord
	isSet bool
}

func (v NullableMessageRecord) Get() *MessageRecord {
	return v.value
}

func (v *NullableMessageRecord) Set(val *MessageRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageRecord(val *MessageRecord) *NullableMessageRecord {
	return &NullableMessageRecord{value: val, isSet: true}
}

func (v NullableMessageRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


