/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.1
Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
)

// checks if the UserProfileItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserProfileItem{}

// UserProfileItem struct for UserProfileItem
type UserProfileItem struct {
	UserId *string `json:"userId,omitempty"`
	Version *int64 `json:"version,omitempty"`
	UserProfile map[string]interface{} `json:"userProfile,omitempty"`
	UserExtProfile map[string]interface{} `json:"userExtProfile,omitempty"`
}

// NewUserProfileItem instantiates a new UserProfileItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserProfileItem() *UserProfileItem {
	this := UserProfileItem{}
	return &this
}

// NewUserProfileItemWithDefaults instantiates a new UserProfileItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserProfileItemWithDefaults() *UserProfileItem {
	this := UserProfileItem{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *UserProfileItem) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProfileItem) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *UserProfileItem) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *UserProfileItem) SetUserId(v string) {
	o.UserId = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *UserProfileItem) GetVersion() int64 {
	if o == nil || IsNil(o.Version) {
		var ret int64
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProfileItem) GetVersionOk() (*int64, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *UserProfileItem) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int64 and assigns it to the Version field.
func (o *UserProfileItem) SetVersion(v int64) {
	o.Version = &v
}

// GetUserProfile returns the UserProfile field value if set, zero value otherwise.
func (o *UserProfileItem) GetUserProfile() map[string]interface{} {
	if o == nil || IsNil(o.UserProfile) {
		var ret map[string]interface{}
		return ret
	}
	return o.UserProfile
}

// GetUserProfileOk returns a tuple with the UserProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProfileItem) GetUserProfileOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.UserProfile) {
		return map[string]interface{}{}, false
	}
	return o.UserProfile, true
}

// HasUserProfile returns a boolean if a field has been set.
func (o *UserProfileItem) HasUserProfile() bool {
	if o != nil && !IsNil(o.UserProfile) {
		return true
	}

	return false
}

// SetUserProfile gets a reference to the given map[string]interface{} and assigns it to the UserProfile field.
func (o *UserProfileItem) SetUserProfile(v map[string]interface{}) {
	o.UserProfile = v
}

// GetUserExtProfile returns the UserExtProfile field value if set, zero value otherwise.
func (o *UserProfileItem) GetUserExtProfile() map[string]interface{} {
	if o == nil || IsNil(o.UserExtProfile) {
		var ret map[string]interface{}
		return ret
	}
	return o.UserExtProfile
}

// GetUserExtProfileOk returns a tuple with the UserExtProfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserProfileItem) GetUserExtProfileOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.UserExtProfile) {
		return map[string]interface{}{}, false
	}
	return o.UserExtProfile, true
}

// HasUserExtProfile returns a boolean if a field has been set.
func (o *UserProfileItem) HasUserExtProfile() bool {
	if o != nil && !IsNil(o.UserExtProfile) {
		return true
	}

	return false
}

// SetUserExtProfile gets a reference to the given map[string]interface{} and assigns it to the UserExtProfile field.
func (o *UserProfileItem) SetUserExtProfile(v map[string]interface{}) {
	o.UserExtProfile = v
}

func (o UserProfileItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserProfileItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.UserProfile) {
		toSerialize["userProfile"] = o.UserProfile
	}
	if !IsNil(o.UserExtProfile) {
		toSerialize["userExtProfile"] = o.UserExtProfile
	}
	return toSerialize, nil
}

type NullableUserProfileItem struct {
	value *UserProfileItem
	isSet bool
}

func (v NullableUserProfileItem) Get() *UserProfileItem {
	return v.value
}

func (v *NullableUserProfileItem) Set(val *UserProfileItem) {
	v.value = val
	v.isSet = true
}

func (v NullableUserProfileItem) IsSet() bool {
	return v.isSet
}

func (v *NullableUserProfileItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserProfileItem(val *UserProfileItem) *NullableUserProfileItem {
	return &NullableUserProfileItem{value: val, isSet: true}
}

func (v NullableUserProfileItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserProfileItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


