/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.0
Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChannelPushSetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelPushSetRequest{}

// ChannelPushSetRequest struct for ChannelPushSetRequest
type ChannelPushSetRequest struct {
	// Session / channel type as a string (`1` to `10` as accepted by the server). Matches `ChannelTypeRequestInput` in the service.
	ChannelType string `json:"channelType"`
	// User ID whose channel notification setting is updated.
	RequestId string `json:"requestId"`
	// Legacy `targetId`.
	ChannelId string `json:"channelId"`
	// Legacy `busChannel`. Used for community-channel subchannel level settings.
	SubchannelId *string `json:"subchannelId,omitempty"`
	// Do-not-disturb level (required by service validation; range `-1` to `5`).
	NoDisturbLevel int32 `json:"noDisturbLevel"`
}

type _ChannelPushSetRequest ChannelPushSetRequest

// NewChannelPushSetRequest instantiates a new ChannelPushSetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelPushSetRequest(channelType string, requestId string, channelId string, noDisturbLevel int32) *ChannelPushSetRequest {
	this := ChannelPushSetRequest{}
	this.ChannelType = channelType
	this.RequestId = requestId
	this.ChannelId = channelId
	this.NoDisturbLevel = noDisturbLevel
	return &this
}

// NewChannelPushSetRequestWithDefaults instantiates a new ChannelPushSetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelPushSetRequestWithDefaults() *ChannelPushSetRequest {
	this := ChannelPushSetRequest{}
	return &this
}

// GetChannelType returns the ChannelType field value
func (o *ChannelPushSetRequest) GetChannelType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelType
}

// GetChannelTypeOk returns a tuple with the ChannelType field value
// and a boolean to check if the value has been set.
func (o *ChannelPushSetRequest) GetChannelTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelType, true
}

// SetChannelType sets field value
func (o *ChannelPushSetRequest) SetChannelType(v string) {
	o.ChannelType = v
}

// GetRequestId returns the RequestId field value
func (o *ChannelPushSetRequest) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *ChannelPushSetRequest) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *ChannelPushSetRequest) SetRequestId(v string) {
	o.RequestId = v
}

// GetChannelId returns the ChannelId field value
func (o *ChannelPushSetRequest) GetChannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value
// and a boolean to check if the value has been set.
func (o *ChannelPushSetRequest) GetChannelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelId, true
}

// SetChannelId sets field value
func (o *ChannelPushSetRequest) SetChannelId(v string) {
	o.ChannelId = v
}

// GetSubchannelId returns the SubchannelId field value if set, zero value otherwise.
func (o *ChannelPushSetRequest) GetSubchannelId() string {
	if o == nil || IsNil(o.SubchannelId) {
		var ret string
		return ret
	}
	return *o.SubchannelId
}

// GetSubchannelIdOk returns a tuple with the SubchannelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelPushSetRequest) GetSubchannelIdOk() (*string, bool) {
	if o == nil || IsNil(o.SubchannelId) {
		return nil, false
	}
	return o.SubchannelId, true
}

// HasSubchannelId returns a boolean if a field has been set.
func (o *ChannelPushSetRequest) HasSubchannelId() bool {
	if o != nil && !IsNil(o.SubchannelId) {
		return true
	}

	return false
}

// SetSubchannelId gets a reference to the given string and assigns it to the SubchannelId field.
func (o *ChannelPushSetRequest) SetSubchannelId(v string) {
	o.SubchannelId = &v
}

// GetNoDisturbLevel returns the NoDisturbLevel field value
func (o *ChannelPushSetRequest) GetNoDisturbLevel() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NoDisturbLevel
}

// GetNoDisturbLevelOk returns a tuple with the NoDisturbLevel field value
// and a boolean to check if the value has been set.
func (o *ChannelPushSetRequest) GetNoDisturbLevelOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NoDisturbLevel, true
}

// SetNoDisturbLevel sets field value
func (o *ChannelPushSetRequest) SetNoDisturbLevel(v int32) {
	o.NoDisturbLevel = v
}

func (o ChannelPushSetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelPushSetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channelType"] = o.ChannelType
	toSerialize["requestId"] = o.RequestId
	toSerialize["channelId"] = o.ChannelId
	if !IsNil(o.SubchannelId) {
		toSerialize["subchannelId"] = o.SubchannelId
	}
	toSerialize["noDisturbLevel"] = o.NoDisturbLevel
	return toSerialize, nil
}

func (o *ChannelPushSetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channelType",
		"requestId",
		"channelId",
		"noDisturbLevel",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChannelPushSetRequest := _ChannelPushSetRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChannelPushSetRequest)

	if err != nil {
		return err
	}

	*o = ChannelPushSetRequest(varChannelPushSetRequest)

	return err
}

type NullableChannelPushSetRequest struct {
	value *ChannelPushSetRequest
	isSet bool
}

func (v NullableChannelPushSetRequest) Get() *ChannelPushSetRequest {
	return v.value
}

func (v *NullableChannelPushSetRequest) Set(val *ChannelPushSetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelPushSetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelPushSetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelPushSetRequest(val *ChannelPushSetRequest) *NullableChannelPushSetRequest {
	return &NullableChannelPushSetRequest{value: val, isSet: true}
}

func (v NullableChannelPushSetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelPushSetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


