/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the GroupChannelMemberBatchGetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupChannelMemberBatchGetRequest{}

// GroupChannelMemberBatchGetRequest struct for GroupChannelMemberBatchGetRequest
type GroupChannelMemberBatchGetRequest struct {
	ChannelId string `json:"channelId"`
	UserIds []string `json:"userIds"`
	AdditionalProperties map[string]interface{}
}

type _GroupChannelMemberBatchGetRequest GroupChannelMemberBatchGetRequest

// NewGroupChannelMemberBatchGetRequest instantiates a new GroupChannelMemberBatchGetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupChannelMemberBatchGetRequest(channelId string, userIds []string) *GroupChannelMemberBatchGetRequest {
	this := GroupChannelMemberBatchGetRequest{}
	this.ChannelId = channelId
	this.UserIds = userIds
	return &this
}

// NewGroupChannelMemberBatchGetRequestWithDefaults instantiates a new GroupChannelMemberBatchGetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupChannelMemberBatchGetRequestWithDefaults() *GroupChannelMemberBatchGetRequest {
	this := GroupChannelMemberBatchGetRequest{}
	return &this
}

// GetChannelId returns the ChannelId field value
func (o *GroupChannelMemberBatchGetRequest) GetChannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value
// and a boolean to check if the value has been set.
func (o *GroupChannelMemberBatchGetRequest) GetChannelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelId, true
}

// SetChannelId sets field value
func (o *GroupChannelMemberBatchGetRequest) SetChannelId(v string) {
	o.ChannelId = v
}

// GetUserIds returns the UserIds field value
func (o *GroupChannelMemberBatchGetRequest) GetUserIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.UserIds
}

// GetUserIdsOk returns a tuple with the UserIds field value
// and a boolean to check if the value has been set.
func (o *GroupChannelMemberBatchGetRequest) GetUserIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserIds, true
}

// SetUserIds sets field value
func (o *GroupChannelMemberBatchGetRequest) SetUserIds(v []string) {
	o.UserIds = v
}

func (o GroupChannelMemberBatchGetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupChannelMemberBatchGetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channelId"] = o.ChannelId
	toSerialize["userIds"] = o.UserIds

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GroupChannelMemberBatchGetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channelId",
		"userIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupChannelMemberBatchGetRequest := _GroupChannelMemberBatchGetRequest{}

	err = json.Unmarshal(data, &varGroupChannelMemberBatchGetRequest)

	if err != nil {
		return err
	}

	*o = GroupChannelMemberBatchGetRequest(varGroupChannelMemberBatchGetRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "channelId")
		delete(additionalProperties, "userIds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGroupChannelMemberBatchGetRequest struct {
	value *GroupChannelMemberBatchGetRequest
	isSet bool
}

func (v NullableGroupChannelMemberBatchGetRequest) Get() *GroupChannelMemberBatchGetRequest {
	return v.value
}

func (v *NullableGroupChannelMemberBatchGetRequest) Set(val *GroupChannelMemberBatchGetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupChannelMemberBatchGetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupChannelMemberBatchGetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupChannelMemberBatchGetRequest(val *GroupChannelMemberBatchGetRequest) *NullableGroupChannelMemberBatchGetRequest {
	return &NullableGroupChannelMemberBatchGetRequest{value: val, isSet: true}
}

func (v NullableGroupChannelMemberBatchGetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupChannelMemberBatchGetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


