/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the ChannelTagTargetItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelTagTargetItem{}

// ChannelTagTargetItem struct for ChannelTagTargetItem
type ChannelTagTargetItem struct {
	ChannelId string `json:"channelId"`
	ChannelType int32 `json:"channelType"`
	AdditionalProperties map[string]interface{}
}

type _ChannelTagTargetItem ChannelTagTargetItem

// NewChannelTagTargetItem instantiates a new ChannelTagTargetItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelTagTargetItem(channelId string, channelType int32) *ChannelTagTargetItem {
	this := ChannelTagTargetItem{}
	this.ChannelId = channelId
	this.ChannelType = channelType
	return &this
}

// NewChannelTagTargetItemWithDefaults instantiates a new ChannelTagTargetItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelTagTargetItemWithDefaults() *ChannelTagTargetItem {
	this := ChannelTagTargetItem{}
	return &this
}

// GetChannelId returns the ChannelId field value
func (o *ChannelTagTargetItem) GetChannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value
// and a boolean to check if the value has been set.
func (o *ChannelTagTargetItem) GetChannelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelId, true
}

// SetChannelId sets field value
func (o *ChannelTagTargetItem) SetChannelId(v string) {
	o.ChannelId = v
}

// GetChannelType returns the ChannelType field value
func (o *ChannelTagTargetItem) GetChannelType() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChannelType
}

// GetChannelTypeOk returns a tuple with the ChannelType field value
// and a boolean to check if the value has been set.
func (o *ChannelTagTargetItem) GetChannelTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelType, true
}

// SetChannelType sets field value
func (o *ChannelTagTargetItem) SetChannelType(v int32) {
	o.ChannelType = v
}

func (o ChannelTagTargetItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelTagTargetItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channelId"] = o.ChannelId
	toSerialize["channelType"] = o.ChannelType

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ChannelTagTargetItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channelId",
		"channelType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChannelTagTargetItem := _ChannelTagTargetItem{}

	err = json.Unmarshal(data, &varChannelTagTargetItem)

	if err != nil {
		return err
	}

	*o = ChannelTagTargetItem(varChannelTagTargetItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "channelId")
		delete(additionalProperties, "channelType")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableChannelTagTargetItem struct {
	value *ChannelTagTargetItem
	isSet bool
}

func (v NullableChannelTagTargetItem) Get() *ChannelTagTargetItem {
	return v.value
}

func (v *NullableChannelTagTargetItem) Set(val *ChannelTagTargetItem) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelTagTargetItem) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelTagTargetItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelTagTargetItem(val *ChannelTagTargetItem) *NullableChannelTagTargetItem {
	return &NullableChannelTagTargetItem{value: val, isSet: true}
}

func (v NullableChannelTagTargetItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelTagTargetItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


