/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.0
Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CommunityChannelHistoryMessageListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommunityChannelHistoryMessageListRequest{}

// CommunityChannelHistoryMessageListRequest struct for CommunityChannelHistoryMessageListRequest
type CommunityChannelHistoryMessageListRequest struct {
	ChannelId string `json:"channelId"`
	SubchannelId string `json:"subchannelId"`
	StartAt int64 `json:"startAt"`
	EndAt int64 `json:"endAt"`
	FromUserId *string `json:"fromUserId,omitempty"`
	PageSize *int32 `json:"pageSize,omitempty"`
}

type _CommunityChannelHistoryMessageListRequest CommunityChannelHistoryMessageListRequest

// NewCommunityChannelHistoryMessageListRequest instantiates a new CommunityChannelHistoryMessageListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommunityChannelHistoryMessageListRequest(channelId string, subchannelId string, startAt int64, endAt int64) *CommunityChannelHistoryMessageListRequest {
	this := CommunityChannelHistoryMessageListRequest{}
	this.ChannelId = channelId
	this.SubchannelId = subchannelId
	this.StartAt = startAt
	this.EndAt = endAt
	var pageSize int32 = 20
	this.PageSize = &pageSize
	return &this
}

// NewCommunityChannelHistoryMessageListRequestWithDefaults instantiates a new CommunityChannelHistoryMessageListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommunityChannelHistoryMessageListRequestWithDefaults() *CommunityChannelHistoryMessageListRequest {
	this := CommunityChannelHistoryMessageListRequest{}
	var pageSize int32 = 20
	this.PageSize = &pageSize
	return &this
}

// GetChannelId returns the ChannelId field value
func (o *CommunityChannelHistoryMessageListRequest) GetChannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value
// and a boolean to check if the value has been set.
func (o *CommunityChannelHistoryMessageListRequest) GetChannelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelId, true
}

// SetChannelId sets field value
func (o *CommunityChannelHistoryMessageListRequest) SetChannelId(v string) {
	o.ChannelId = v
}

// GetSubchannelId returns the SubchannelId field value
func (o *CommunityChannelHistoryMessageListRequest) GetSubchannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubchannelId
}

// GetSubchannelIdOk returns a tuple with the SubchannelId field value
// and a boolean to check if the value has been set.
func (o *CommunityChannelHistoryMessageListRequest) GetSubchannelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubchannelId, true
}

// SetSubchannelId sets field value
func (o *CommunityChannelHistoryMessageListRequest) SetSubchannelId(v string) {
	o.SubchannelId = v
}

// GetStartAt returns the StartAt field value
func (o *CommunityChannelHistoryMessageListRequest) GetStartAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.StartAt
}

// GetStartAtOk returns a tuple with the StartAt field value
// and a boolean to check if the value has been set.
func (o *CommunityChannelHistoryMessageListRequest) GetStartAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartAt, true
}

// SetStartAt sets field value
func (o *CommunityChannelHistoryMessageListRequest) SetStartAt(v int64) {
	o.StartAt = v
}

// GetEndAt returns the EndAt field value
func (o *CommunityChannelHistoryMessageListRequest) GetEndAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.EndAt
}

// GetEndAtOk returns a tuple with the EndAt field value
// and a boolean to check if the value has been set.
func (o *CommunityChannelHistoryMessageListRequest) GetEndAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndAt, true
}

// SetEndAt sets field value
func (o *CommunityChannelHistoryMessageListRequest) SetEndAt(v int64) {
	o.EndAt = v
}

// GetFromUserId returns the FromUserId field value if set, zero value otherwise.
func (o *CommunityChannelHistoryMessageListRequest) GetFromUserId() string {
	if o == nil || IsNil(o.FromUserId) {
		var ret string
		return ret
	}
	return *o.FromUserId
}

// GetFromUserIdOk returns a tuple with the FromUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityChannelHistoryMessageListRequest) GetFromUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.FromUserId) {
		return nil, false
	}
	return o.FromUserId, true
}

// HasFromUserId returns a boolean if a field has been set.
func (o *CommunityChannelHistoryMessageListRequest) HasFromUserId() bool {
	if o != nil && !IsNil(o.FromUserId) {
		return true
	}

	return false
}

// SetFromUserId gets a reference to the given string and assigns it to the FromUserId field.
func (o *CommunityChannelHistoryMessageListRequest) SetFromUserId(v string) {
	o.FromUserId = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *CommunityChannelHistoryMessageListRequest) GetPageSize() int32 {
	if o == nil || IsNil(o.PageSize) {
		var ret int32
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityChannelHistoryMessageListRequest) GetPageSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *CommunityChannelHistoryMessageListRequest) HasPageSize() bool {
	if o != nil && !IsNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given int32 and assigns it to the PageSize field.
func (o *CommunityChannelHistoryMessageListRequest) SetPageSize(v int32) {
	o.PageSize = &v
}

func (o CommunityChannelHistoryMessageListRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommunityChannelHistoryMessageListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channelId"] = o.ChannelId
	toSerialize["subchannelId"] = o.SubchannelId
	toSerialize["startAt"] = o.StartAt
	toSerialize["endAt"] = o.EndAt
	if !IsNil(o.FromUserId) {
		toSerialize["fromUserId"] = o.FromUserId
	}
	if !IsNil(o.PageSize) {
		toSerialize["pageSize"] = o.PageSize
	}
	return toSerialize, nil
}

func (o *CommunityChannelHistoryMessageListRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channelId",
		"subchannelId",
		"startAt",
		"endAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommunityChannelHistoryMessageListRequest := _CommunityChannelHistoryMessageListRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCommunityChannelHistoryMessageListRequest)

	if err != nil {
		return err
	}

	*o = CommunityChannelHistoryMessageListRequest(varCommunityChannelHistoryMessageListRequest)

	return err
}

type NullableCommunityChannelHistoryMessageListRequest struct {
	value *CommunityChannelHistoryMessageListRequest
	isSet bool
}

func (v NullableCommunityChannelHistoryMessageListRequest) Get() *CommunityChannelHistoryMessageListRequest {
	return v.value
}

func (v *NullableCommunityChannelHistoryMessageListRequest) Set(val *CommunityChannelHistoryMessageListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCommunityChannelHistoryMessageListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCommunityChannelHistoryMessageListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommunityChannelHistoryMessageListRequest(val *CommunityChannelHistoryMessageListRequest) *NullableCommunityChannelHistoryMessageListRequest {
	return &NullableCommunityChannelHistoryMessageListRequest{value: val, isSet: true}
}

func (v NullableCommunityChannelHistoryMessageListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommunityChannelHistoryMessageListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


