/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.0
Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CommunityChannelMessageMetadataDeleteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommunityChannelMessageMetadataDeleteRequest{}

// CommunityChannelMessageMetadataDeleteRequest struct for CommunityChannelMessageMetadataDeleteRequest
type CommunityChannelMessageMetadataDeleteRequest struct {
	MessageId string `json:"messageId"`
	UserId string `json:"userId"`
	ChannelId string `json:"channelId"`
	// Should match the subchannel used when the message was sent.
	SubchannelId *string `json:"subchannelId,omitempty"`
	Keys []string `json:"keys"`
}

type _CommunityChannelMessageMetadataDeleteRequest CommunityChannelMessageMetadataDeleteRequest

// NewCommunityChannelMessageMetadataDeleteRequest instantiates a new CommunityChannelMessageMetadataDeleteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommunityChannelMessageMetadataDeleteRequest(messageId string, userId string, channelId string, keys []string) *CommunityChannelMessageMetadataDeleteRequest {
	this := CommunityChannelMessageMetadataDeleteRequest{}
	this.MessageId = messageId
	this.UserId = userId
	this.ChannelId = channelId
	this.Keys = keys
	return &this
}

// NewCommunityChannelMessageMetadataDeleteRequestWithDefaults instantiates a new CommunityChannelMessageMetadataDeleteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommunityChannelMessageMetadataDeleteRequestWithDefaults() *CommunityChannelMessageMetadataDeleteRequest {
	this := CommunityChannelMessageMetadataDeleteRequest{}
	return &this
}

// GetMessageId returns the MessageId field value
func (o *CommunityChannelMessageMetadataDeleteRequest) GetMessageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MessageId
}

// GetMessageIdOk returns a tuple with the MessageId field value
// and a boolean to check if the value has been set.
func (o *CommunityChannelMessageMetadataDeleteRequest) GetMessageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MessageId, true
}

// SetMessageId sets field value
func (o *CommunityChannelMessageMetadataDeleteRequest) SetMessageId(v string) {
	o.MessageId = v
}

// GetUserId returns the UserId field value
func (o *CommunityChannelMessageMetadataDeleteRequest) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *CommunityChannelMessageMetadataDeleteRequest) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *CommunityChannelMessageMetadataDeleteRequest) SetUserId(v string) {
	o.UserId = v
}

// GetChannelId returns the ChannelId field value
func (o *CommunityChannelMessageMetadataDeleteRequest) GetChannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value
// and a boolean to check if the value has been set.
func (o *CommunityChannelMessageMetadataDeleteRequest) GetChannelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelId, true
}

// SetChannelId sets field value
func (o *CommunityChannelMessageMetadataDeleteRequest) SetChannelId(v string) {
	o.ChannelId = v
}

// GetSubchannelId returns the SubchannelId field value if set, zero value otherwise.
func (o *CommunityChannelMessageMetadataDeleteRequest) GetSubchannelId() string {
	if o == nil || IsNil(o.SubchannelId) {
		var ret string
		return ret
	}
	return *o.SubchannelId
}

// GetSubchannelIdOk returns a tuple with the SubchannelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityChannelMessageMetadataDeleteRequest) GetSubchannelIdOk() (*string, bool) {
	if o == nil || IsNil(o.SubchannelId) {
		return nil, false
	}
	return o.SubchannelId, true
}

// HasSubchannelId returns a boolean if a field has been set.
func (o *CommunityChannelMessageMetadataDeleteRequest) HasSubchannelId() bool {
	if o != nil && !IsNil(o.SubchannelId) {
		return true
	}

	return false
}

// SetSubchannelId gets a reference to the given string and assigns it to the SubchannelId field.
func (o *CommunityChannelMessageMetadataDeleteRequest) SetSubchannelId(v string) {
	o.SubchannelId = &v
}

// GetKeys returns the Keys field value
func (o *CommunityChannelMessageMetadataDeleteRequest) GetKeys() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Keys
}

// GetKeysOk returns a tuple with the Keys field value
// and a boolean to check if the value has been set.
func (o *CommunityChannelMessageMetadataDeleteRequest) GetKeysOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Keys, true
}

// SetKeys sets field value
func (o *CommunityChannelMessageMetadataDeleteRequest) SetKeys(v []string) {
	o.Keys = v
}

func (o CommunityChannelMessageMetadataDeleteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommunityChannelMessageMetadataDeleteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["messageId"] = o.MessageId
	toSerialize["userId"] = o.UserId
	toSerialize["channelId"] = o.ChannelId
	if !IsNil(o.SubchannelId) {
		toSerialize["subchannelId"] = o.SubchannelId
	}
	toSerialize["keys"] = o.Keys
	return toSerialize, nil
}

func (o *CommunityChannelMessageMetadataDeleteRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"messageId",
		"userId",
		"channelId",
		"keys",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommunityChannelMessageMetadataDeleteRequest := _CommunityChannelMessageMetadataDeleteRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCommunityChannelMessageMetadataDeleteRequest)

	if err != nil {
		return err
	}

	*o = CommunityChannelMessageMetadataDeleteRequest(varCommunityChannelMessageMetadataDeleteRequest)

	return err
}

type NullableCommunityChannelMessageMetadataDeleteRequest struct {
	value *CommunityChannelMessageMetadataDeleteRequest
	isSet bool
}

func (v NullableCommunityChannelMessageMetadataDeleteRequest) Get() *CommunityChannelMessageMetadataDeleteRequest {
	return v.value
}

func (v *NullableCommunityChannelMessageMetadataDeleteRequest) Set(val *CommunityChannelMessageMetadataDeleteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCommunityChannelMessageMetadataDeleteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCommunityChannelMessageMetadataDeleteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommunityChannelMessageMetadataDeleteRequest(val *CommunityChannelMessageMetadataDeleteRequest) *NullableCommunityChannelMessageMetadataDeleteRequest {
	return &NullableCommunityChannelMessageMetadataDeleteRequest{value: val, isSet: true}
}

func (v NullableCommunityChannelMessageMetadataDeleteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommunityChannelMessageMetadataDeleteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


