/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the ChannelTypeNotificationSetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelTypeNotificationSetRequest{}

// ChannelTypeNotificationSetRequest struct for ChannelTypeNotificationSetRequest
type ChannelTypeNotificationSetRequest struct {
	// Session / channel type as a string (`1` to `10` as accepted by the server).
	ChannelType string `json:"channelType"`
	// User ID whose channel-type notification setting is updated.
	RequestId string `json:"requestId"`
	// Do-not-disturb level for the specified channel type.
	NoDisturbLevel int32 `json:"noDisturbLevel"`
	AdditionalProperties map[string]interface{}
}

type _ChannelTypeNotificationSetRequest ChannelTypeNotificationSetRequest

// NewChannelTypeNotificationSetRequest instantiates a new ChannelTypeNotificationSetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelTypeNotificationSetRequest(channelType string, requestId string, noDisturbLevel int32) *ChannelTypeNotificationSetRequest {
	this := ChannelTypeNotificationSetRequest{}
	this.ChannelType = channelType
	this.RequestId = requestId
	this.NoDisturbLevel = noDisturbLevel
	return &this
}

// NewChannelTypeNotificationSetRequestWithDefaults instantiates a new ChannelTypeNotificationSetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelTypeNotificationSetRequestWithDefaults() *ChannelTypeNotificationSetRequest {
	this := ChannelTypeNotificationSetRequest{}
	return &this
}

// GetChannelType returns the ChannelType field value
func (o *ChannelTypeNotificationSetRequest) GetChannelType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelType
}

// GetChannelTypeOk returns a tuple with the ChannelType field value
// and a boolean to check if the value has been set.
func (o *ChannelTypeNotificationSetRequest) GetChannelTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelType, true
}

// SetChannelType sets field value
func (o *ChannelTypeNotificationSetRequest) SetChannelType(v string) {
	o.ChannelType = v
}

// GetRequestId returns the RequestId field value
func (o *ChannelTypeNotificationSetRequest) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *ChannelTypeNotificationSetRequest) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *ChannelTypeNotificationSetRequest) SetRequestId(v string) {
	o.RequestId = v
}

// GetNoDisturbLevel returns the NoDisturbLevel field value
func (o *ChannelTypeNotificationSetRequest) GetNoDisturbLevel() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NoDisturbLevel
}

// GetNoDisturbLevelOk returns a tuple with the NoDisturbLevel field value
// and a boolean to check if the value has been set.
func (o *ChannelTypeNotificationSetRequest) GetNoDisturbLevelOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NoDisturbLevel, true
}

// SetNoDisturbLevel sets field value
func (o *ChannelTypeNotificationSetRequest) SetNoDisturbLevel(v int32) {
	o.NoDisturbLevel = v
}

func (o ChannelTypeNotificationSetRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelTypeNotificationSetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channelType"] = o.ChannelType
	toSerialize["requestId"] = o.RequestId
	toSerialize["noDisturbLevel"] = o.NoDisturbLevel

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ChannelTypeNotificationSetRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channelType",
		"requestId",
		"noDisturbLevel",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChannelTypeNotificationSetRequest := _ChannelTypeNotificationSetRequest{}

	err = json.Unmarshal(data, &varChannelTypeNotificationSetRequest)

	if err != nil {
		return err
	}

	*o = ChannelTypeNotificationSetRequest(varChannelTypeNotificationSetRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "channelType")
		delete(additionalProperties, "requestId")
		delete(additionalProperties, "noDisturbLevel")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableChannelTypeNotificationSetRequest struct {
	value *ChannelTypeNotificationSetRequest
	isSet bool
}

func (v NullableChannelTypeNotificationSetRequest) Get() *ChannelTypeNotificationSetRequest {
	return v.value
}

func (v *NullableChannelTypeNotificationSetRequest) Set(val *ChannelTypeNotificationSetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelTypeNotificationSetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelTypeNotificationSetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelTypeNotificationSetRequest(val *ChannelTypeNotificationSetRequest) *NullableChannelTypeNotificationSetRequest {
	return &NullableChannelTypeNotificationSetRequest{value: val, isSet: true}
}

func (v NullableChannelTypeNotificationSetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelTypeNotificationSetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


