/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CommunityChannelMuteListAddRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommunityChannelMuteListAddRequest{}

// CommunityChannelMuteListAddRequest struct for CommunityChannelMuteListAddRequest
type CommunityChannelMuteListAddRequest struct {
	ChannelId string `json:"channelId"`
	SubchannelId *string `json:"subchannelId,omitempty"`
	UserIds []string `json:"userIds"`
}

type _CommunityChannelMuteListAddRequest CommunityChannelMuteListAddRequest

// NewCommunityChannelMuteListAddRequest instantiates a new CommunityChannelMuteListAddRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommunityChannelMuteListAddRequest(channelId string, userIds []string) *CommunityChannelMuteListAddRequest {
	this := CommunityChannelMuteListAddRequest{}
	this.ChannelId = channelId
	this.UserIds = userIds
	return &this
}

// NewCommunityChannelMuteListAddRequestWithDefaults instantiates a new CommunityChannelMuteListAddRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommunityChannelMuteListAddRequestWithDefaults() *CommunityChannelMuteListAddRequest {
	this := CommunityChannelMuteListAddRequest{}
	return &this
}

// GetChannelId returns the ChannelId field value
func (o *CommunityChannelMuteListAddRequest) GetChannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value
// and a boolean to check if the value has been set.
func (o *CommunityChannelMuteListAddRequest) GetChannelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelId, true
}

// SetChannelId sets field value
func (o *CommunityChannelMuteListAddRequest) SetChannelId(v string) {
	o.ChannelId = v
}

// GetSubchannelId returns the SubchannelId field value if set, zero value otherwise.
func (o *CommunityChannelMuteListAddRequest) GetSubchannelId() string {
	if o == nil || IsNil(o.SubchannelId) {
		var ret string
		return ret
	}
	return *o.SubchannelId
}

// GetSubchannelIdOk returns a tuple with the SubchannelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityChannelMuteListAddRequest) GetSubchannelIdOk() (*string, bool) {
	if o == nil || IsNil(o.SubchannelId) {
		return nil, false
	}
	return o.SubchannelId, true
}

// HasSubchannelId returns a boolean if a field has been set.
func (o *CommunityChannelMuteListAddRequest) HasSubchannelId() bool {
	if o != nil && !IsNil(o.SubchannelId) {
		return true
	}

	return false
}

// SetSubchannelId gets a reference to the given string and assigns it to the SubchannelId field.
func (o *CommunityChannelMuteListAddRequest) SetSubchannelId(v string) {
	o.SubchannelId = &v
}

// GetUserIds returns the UserIds field value
func (o *CommunityChannelMuteListAddRequest) GetUserIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.UserIds
}

// GetUserIdsOk returns a tuple with the UserIds field value
// and a boolean to check if the value has been set.
func (o *CommunityChannelMuteListAddRequest) GetUserIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UserIds, true
}

// SetUserIds sets field value
func (o *CommunityChannelMuteListAddRequest) SetUserIds(v []string) {
	o.UserIds = v
}

func (o CommunityChannelMuteListAddRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommunityChannelMuteListAddRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channelId"] = o.ChannelId
	if !IsNil(o.SubchannelId) {
		toSerialize["subchannelId"] = o.SubchannelId
	}
	toSerialize["userIds"] = o.UserIds
	return toSerialize, nil
}

func (o *CommunityChannelMuteListAddRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channelId",
		"userIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommunityChannelMuteListAddRequest := _CommunityChannelMuteListAddRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCommunityChannelMuteListAddRequest)

	if err != nil {
		return err
	}

	*o = CommunityChannelMuteListAddRequest(varCommunityChannelMuteListAddRequest)

	return err
}

type NullableCommunityChannelMuteListAddRequest struct {
	value *CommunityChannelMuteListAddRequest
	isSet bool
}

func (v NullableCommunityChannelMuteListAddRequest) Get() *CommunityChannelMuteListAddRequest {
	return v.value
}

func (v *NullableCommunityChannelMuteListAddRequest) Set(val *CommunityChannelMuteListAddRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCommunityChannelMuteListAddRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCommunityChannelMuteListAddRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommunityChannelMuteListAddRequest(val *CommunityChannelMuteListAddRequest) *NullableCommunityChannelMuteListAddRequest {
	return &NullableCommunityChannelMuteListAddRequest{value: val, isSet: true}
}

func (v NullableCommunityChannelMuteListAddRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommunityChannelMuteListAddRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


