/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
)

// checks if the OpenChannelHistoryMessageRecord type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenChannelHistoryMessageRecord{}

// OpenChannelHistoryMessageRecord struct for OpenChannelHistoryMessageRecord
type OpenChannelHistoryMessageRecord struct {
	// Channel identifier of the stored message.
	ChannelId *string `json:"channelId,omitempty"`
	// Sender user ID of the stored message.
	FromUserId *string `json:"fromUserId,omitempty"`
	// Unique message ID.
	MessageId *string `json:"messageId,omitempty"`
	// Message send timestamp in milliseconds.
	SentAt *int64 `json:"sentAt,omitempty"`
	// Message type of the stored message.
	MessageType *string `json:"messageType,omitempty"`
	// Raw message content payload as stored by the service.
	Content *string `json:"content,omitempty"`
	// Quoted message details as a JSON string containing msgUID, objectName and fromUserId. Omitted for messages without a quote.
	Quote *string `json:"quote,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OpenChannelHistoryMessageRecord OpenChannelHistoryMessageRecord

// NewOpenChannelHistoryMessageRecord instantiates a new OpenChannelHistoryMessageRecord object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenChannelHistoryMessageRecord() *OpenChannelHistoryMessageRecord {
	this := OpenChannelHistoryMessageRecord{}
	return &this
}

// NewOpenChannelHistoryMessageRecordWithDefaults instantiates a new OpenChannelHistoryMessageRecord object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenChannelHistoryMessageRecordWithDefaults() *OpenChannelHistoryMessageRecord {
	this := OpenChannelHistoryMessageRecord{}
	return &this
}

// GetChannelId returns the ChannelId field value if set, zero value otherwise.
func (o *OpenChannelHistoryMessageRecord) GetChannelId() string {
	if o == nil || IsNil(o.ChannelId) {
		var ret string
		return ret
	}
	return *o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelHistoryMessageRecord) GetChannelIdOk() (*string, bool) {
	if o == nil || IsNil(o.ChannelId) {
		return nil, false
	}
	return o.ChannelId, true
}

// HasChannelId returns a boolean if a field has been set.
func (o *OpenChannelHistoryMessageRecord) HasChannelId() bool {
	if o != nil && !IsNil(o.ChannelId) {
		return true
	}

	return false
}

// SetChannelId gets a reference to the given string and assigns it to the ChannelId field.
func (o *OpenChannelHistoryMessageRecord) SetChannelId(v string) {
	o.ChannelId = &v
}

// GetFromUserId returns the FromUserId field value if set, zero value otherwise.
func (o *OpenChannelHistoryMessageRecord) GetFromUserId() string {
	if o == nil || IsNil(o.FromUserId) {
		var ret string
		return ret
	}
	return *o.FromUserId
}

// GetFromUserIdOk returns a tuple with the FromUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelHistoryMessageRecord) GetFromUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.FromUserId) {
		return nil, false
	}
	return o.FromUserId, true
}

// HasFromUserId returns a boolean if a field has been set.
func (o *OpenChannelHistoryMessageRecord) HasFromUserId() bool {
	if o != nil && !IsNil(o.FromUserId) {
		return true
	}

	return false
}

// SetFromUserId gets a reference to the given string and assigns it to the FromUserId field.
func (o *OpenChannelHistoryMessageRecord) SetFromUserId(v string) {
	o.FromUserId = &v
}

// GetMessageId returns the MessageId field value if set, zero value otherwise.
func (o *OpenChannelHistoryMessageRecord) GetMessageId() string {
	if o == nil || IsNil(o.MessageId) {
		var ret string
		return ret
	}
	return *o.MessageId
}

// GetMessageIdOk returns a tuple with the MessageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelHistoryMessageRecord) GetMessageIdOk() (*string, bool) {
	if o == nil || IsNil(o.MessageId) {
		return nil, false
	}
	return o.MessageId, true
}

// HasMessageId returns a boolean if a field has been set.
func (o *OpenChannelHistoryMessageRecord) HasMessageId() bool {
	if o != nil && !IsNil(o.MessageId) {
		return true
	}

	return false
}

// SetMessageId gets a reference to the given string and assigns it to the MessageId field.
func (o *OpenChannelHistoryMessageRecord) SetMessageId(v string) {
	o.MessageId = &v
}

// GetSentAt returns the SentAt field value if set, zero value otherwise.
func (o *OpenChannelHistoryMessageRecord) GetSentAt() int64 {
	if o == nil || IsNil(o.SentAt) {
		var ret int64
		return ret
	}
	return *o.SentAt
}

// GetSentAtOk returns a tuple with the SentAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelHistoryMessageRecord) GetSentAtOk() (*int64, bool) {
	if o == nil || IsNil(o.SentAt) {
		return nil, false
	}
	return o.SentAt, true
}

// HasSentAt returns a boolean if a field has been set.
func (o *OpenChannelHistoryMessageRecord) HasSentAt() bool {
	if o != nil && !IsNil(o.SentAt) {
		return true
	}

	return false
}

// SetSentAt gets a reference to the given int64 and assigns it to the SentAt field.
func (o *OpenChannelHistoryMessageRecord) SetSentAt(v int64) {
	o.SentAt = &v
}

// GetMessageType returns the MessageType field value if set, zero value otherwise.
func (o *OpenChannelHistoryMessageRecord) GetMessageType() string {
	if o == nil || IsNil(o.MessageType) {
		var ret string
		return ret
	}
	return *o.MessageType
}

// GetMessageTypeOk returns a tuple with the MessageType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelHistoryMessageRecord) GetMessageTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MessageType) {
		return nil, false
	}
	return o.MessageType, true
}

// HasMessageType returns a boolean if a field has been set.
func (o *OpenChannelHistoryMessageRecord) HasMessageType() bool {
	if o != nil && !IsNil(o.MessageType) {
		return true
	}

	return false
}

// SetMessageType gets a reference to the given string and assigns it to the MessageType field.
func (o *OpenChannelHistoryMessageRecord) SetMessageType(v string) {
	o.MessageType = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *OpenChannelHistoryMessageRecord) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelHistoryMessageRecord) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *OpenChannelHistoryMessageRecord) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *OpenChannelHistoryMessageRecord) SetContent(v string) {
	o.Content = &v
}

// GetQuote returns the Quote field value if set, zero value otherwise.
func (o *OpenChannelHistoryMessageRecord) GetQuote() string {
	if o == nil || IsNil(o.Quote) {
		var ret string
		return ret
	}
	return *o.Quote
}

// GetQuoteOk returns a tuple with the Quote field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenChannelHistoryMessageRecord) GetQuoteOk() (*string, bool) {
	if o == nil || IsNil(o.Quote) {
		return nil, false
	}
	return o.Quote, true
}

// HasQuote returns a boolean if a field has been set.
func (o *OpenChannelHistoryMessageRecord) HasQuote() bool {
	if o != nil && !IsNil(o.Quote) {
		return true
	}

	return false
}

// SetQuote gets a reference to the given string and assigns it to the Quote field.
func (o *OpenChannelHistoryMessageRecord) SetQuote(v string) {
	o.Quote = &v
}

func (o OpenChannelHistoryMessageRecord) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenChannelHistoryMessageRecord) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ChannelId) {
		toSerialize["channelId"] = o.ChannelId
	}
	if !IsNil(o.FromUserId) {
		toSerialize["fromUserId"] = o.FromUserId
	}
	if !IsNil(o.MessageId) {
		toSerialize["messageId"] = o.MessageId
	}
	if !IsNil(o.SentAt) {
		toSerialize["sentAt"] = o.SentAt
	}
	if !IsNil(o.MessageType) {
		toSerialize["messageType"] = o.MessageType
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.Quote) {
		toSerialize["quote"] = o.Quote
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OpenChannelHistoryMessageRecord) UnmarshalJSON(data []byte) (err error) {
	varOpenChannelHistoryMessageRecord := _OpenChannelHistoryMessageRecord{}

	err = json.Unmarshal(data, &varOpenChannelHistoryMessageRecord)

	if err != nil {
		return err
	}

	*o = OpenChannelHistoryMessageRecord(varOpenChannelHistoryMessageRecord)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "channelId")
		delete(additionalProperties, "fromUserId")
		delete(additionalProperties, "messageId")
		delete(additionalProperties, "sentAt")
		delete(additionalProperties, "messageType")
		delete(additionalProperties, "content")
		delete(additionalProperties, "quote")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOpenChannelHistoryMessageRecord struct {
	value *OpenChannelHistoryMessageRecord
	isSet bool
}

func (v NullableOpenChannelHistoryMessageRecord) Get() *OpenChannelHistoryMessageRecord {
	return v.value
}

func (v *NullableOpenChannelHistoryMessageRecord) Set(val *OpenChannelHistoryMessageRecord) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenChannelHistoryMessageRecord) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenChannelHistoryMessageRecord) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenChannelHistoryMessageRecord(val *OpenChannelHistoryMessageRecord) *NullableOpenChannelHistoryMessageRecord {
	return &NullableOpenChannelHistoryMessageRecord{value: val, isSet: true}
}

func (v NullableOpenChannelHistoryMessageRecord) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenChannelHistoryMessageRecord) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


