/*
Nexconn Server API

OpenAPI specification aligned with the current Nexconn public documentation, PDF source documents, and generated SDK requirements.

API version: 0.1.1
Contact: customercare@nexconn.ai
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ncsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CommunityUserSubchannelListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommunityUserSubchannelListRequest{}

// CommunityUserSubchannelListRequest struct for CommunityUserSubchannelListRequest
type CommunityUserSubchannelListRequest struct {
	ChannelId string `json:"channelId"`
	UserId string `json:"userId"`
	Page *int32 `json:"page,omitempty"`
	PageSize *int32 `json:"pageSize,omitempty"`
}

type _CommunityUserSubchannelListRequest CommunityUserSubchannelListRequest

// NewCommunityUserSubchannelListRequest instantiates a new CommunityUserSubchannelListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommunityUserSubchannelListRequest(channelId string, userId string) *CommunityUserSubchannelListRequest {
	this := CommunityUserSubchannelListRequest{}
	this.ChannelId = channelId
	this.UserId = userId
	var pageSize int32 = 10
	this.PageSize = &pageSize
	return &this
}

// NewCommunityUserSubchannelListRequestWithDefaults instantiates a new CommunityUserSubchannelListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommunityUserSubchannelListRequestWithDefaults() *CommunityUserSubchannelListRequest {
	this := CommunityUserSubchannelListRequest{}
	var pageSize int32 = 10
	this.PageSize = &pageSize
	return &this
}

// GetChannelId returns the ChannelId field value
func (o *CommunityUserSubchannelListRequest) GetChannelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value
// and a boolean to check if the value has been set.
func (o *CommunityUserSubchannelListRequest) GetChannelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChannelId, true
}

// SetChannelId sets field value
func (o *CommunityUserSubchannelListRequest) SetChannelId(v string) {
	o.ChannelId = v
}

// GetUserId returns the UserId field value
func (o *CommunityUserSubchannelListRequest) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *CommunityUserSubchannelListRequest) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *CommunityUserSubchannelListRequest) SetUserId(v string) {
	o.UserId = v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *CommunityUserSubchannelListRequest) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityUserSubchannelListRequest) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *CommunityUserSubchannelListRequest) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *CommunityUserSubchannelListRequest) SetPage(v int32) {
	o.Page = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *CommunityUserSubchannelListRequest) GetPageSize() int32 {
	if o == nil || IsNil(o.PageSize) {
		var ret int32
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommunityUserSubchannelListRequest) GetPageSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *CommunityUserSubchannelListRequest) HasPageSize() bool {
	if o != nil && !IsNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given int32 and assigns it to the PageSize field.
func (o *CommunityUserSubchannelListRequest) SetPageSize(v int32) {
	o.PageSize = &v
}

func (o CommunityUserSubchannelListRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommunityUserSubchannelListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channelId"] = o.ChannelId
	toSerialize["userId"] = o.UserId
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.PageSize) {
		toSerialize["pageSize"] = o.PageSize
	}
	return toSerialize, nil
}

func (o *CommunityUserSubchannelListRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channelId",
		"userId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommunityUserSubchannelListRequest := _CommunityUserSubchannelListRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCommunityUserSubchannelListRequest)

	if err != nil {
		return err
	}

	*o = CommunityUserSubchannelListRequest(varCommunityUserSubchannelListRequest)

	return err
}

type NullableCommunityUserSubchannelListRequest struct {
	value *CommunityUserSubchannelListRequest
	isSet bool
}

func (v NullableCommunityUserSubchannelListRequest) Get() *CommunityUserSubchannelListRequest {
	return v.value
}

func (v *NullableCommunityUserSubchannelListRequest) Set(val *CommunityUserSubchannelListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCommunityUserSubchannelListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCommunityUserSubchannelListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommunityUserSubchannelListRequest(val *CommunityUserSubchannelListRequest) *NullableCommunityUserSubchannelListRequest {
	return &NullableCommunityUserSubchannelListRequest{value: val, isSet: true}
}

func (v NullableCommunityUserSubchannelListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommunityUserSubchannelListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


